### ISSUE TITLE
Documentation: installation instructions

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CUDA.jl#1]
Information on how to install CUDA, troubleshoot common problems, make sure Julia CUDA works, etc.

**Comment by dnabanita7** [comment]
Can I take this? I just compiled it and came through few errors.

**Comment by maleadt** [comment]
Oh sure, no need to ask for permission :-) There's a category for installation-related documentation: https://github.com/JuliaGPU/CUDA.jl/tree/master/docs/src/installation

**Comment by dnabanita7** [comment]
Thanks! I will start working on it.
