### ISSUE TITLE
Relax restriction on types allowed in kernels?

### ISSUE THREAD

**Issue by jw3126** [JuliaGPU/CUDA.jl#1005]
Not all types are valid to pass to a CUDA kernel. Bitstypes are okay. And AFAICT putting stuff that is okay in a `Tuple`, `NamedTuples` or `CuArray` is also okay. This is already an awesome abstraction. However, putting ok stuff in a custom struct is not always okay.
Would it be possible to allow custom structs as another combinator here?

# Example
This would be useful for many things. To give at least one concrete example:

I have a library [LinearInterpolations.jl](https://github.com/jw3126/LinearInterpolations.jl). It has an API like this:
```julia
itp = Interpolate(data...) # construct interpolate, typically done only few times
itp(pt) # eval at new point typically called a lot
```
In this code the `Interpolate(data...)` does a lot of validation and is not suitable for GPU. But `itp(pt)` could in theory run on GPU (no exceptions/no allocs/no dynamic dispatch etc.). So in a perfect world, I could just do:
```julia
itp = adapt(CuArray, itp))
pts = StructArray(...)
itp.(pts)
```
But this is not allowed. The only workarounds I see add quite some boilerplate and involve changing the source code of the [LinearInterpolations.jl](https://github.com/jw3126/LinearInterpolations.jl) package.

**Comment by maleadt** [comment]
>  Would it be possible to allow custom structs as another combinator here?

It is already allowed, as long as the resulting type is a bits type again. If that doesn't work, e.g. because on the host side you have a complicated mutable structure containing, say, a CuArray, you can instead define a device-side counterpart and use Adapt rules to convert. Also note that you can also keep both structures the same by introducing type parameters.

Does this not work for this specific use case?

**Comment by jw3126** [comment]
Thanks a lot! That sounds very much like it might work in my use case. Sadly I failed so far. Is there some docs or example I should take a look at? 
Which `adapt` method do I need to overload? `adapt(::Type{CuDeviceArray}, itp::Interpolate)`?
If so how to get a `CuDeviceArray` from a `CuArray`? Here is an MWE:
```julia
using CUDA

struct Interpolate{A}
    xs::A
    ys::A
end

function (itp::Interpolate)(x)
    i = searchsortedfirst(itp.xs, x)
    i = clamp(i, firstindex(itp.ys), lastindex(itp.ys))
    @inbounds itp.ys[i]
end

xs = sort!(CUDA.randn(10))
ys = CUDA.randn(10)
itp = Interpolate(xs, ys)

pts = CUDA.randn(100)
itp.(pts) # fails
```

**Comment by maleadt** [comment]
```julia
julia> using Adapt

julia> Adapt.adapt_structure(to, x::Interpolate) = Interpolate(adapt(to, x.xs), adapt(to, x.ys))

julia> itp.(pts)
100-element CuArray{Float32, 1}:
...
```

**Comment by jw3126** [comment]
Awesome that works for me. If you want I can turn this example into a little "Using custom structs in kernels" tutorial. Not sure, now it seems clear from the Adapt.jl README, but before I spent maybe 30min searching the CUDA.jl docs.

**Comment by maleadt** [comment]
That would be much appreciated!
