### ISSUE TITLE
Broadcasted setindex! triggers scalar setindex!

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaGPU/CUDA.jl#101]
```julia
using CuArrays
CuArrays.allowscalar(false)
J = cu(zeros(30,30))
rows_index, cols_index, colorvec, cols_index, color_i = (1:30, 1:30, 1:30, 1:30, 1)
vecdx = cu(Float32[-2.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
@. setindex!((J,),getindex((J,),rows_index, cols_index) + (getindex((colorvec,),cols_index) == color_i) * getindex((vecdx,),rows_index),rows_index, cols_index)
```

**Comment by mbauman** [comment]
So the reason that tuples aren't working is that CUDA isn't grabbing tuples of CuArrays as being a `CuArrayStyle`:

```Julia
julia> typeof(Broadcast.broadcasted(void(setindex!), Ref(A), 1))
Base.Broadcast.Broadcasted{CUDA.CuArrayStyle{0}, Nothing, var"#1#2"{typeof(setindex!)}, Tuple{Base.RefValue{CuArray{Int64, 1, CUDA.Mem.DeviceBuffer}}, Int64}}

julia> typeof(Broadcast.broadcasted(void(setindex!), (A,), 1))
Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple}, Nothing, var"#1#2"{typeof(setindex!)}, Tuple{Tuple{CuArray{Int64, 1, CUDA.Mem.DeviceBuffer}}, Int64}}
```

I'm not sure off-hand what the magic would be to ensure that `Tuple{<:CuArray}` gets flagged as a CuArrayStyle, but that'll do the ticket here.  It's a little tricky because we typically only look at the _outermost_ containers in determining what the array style should be.

**Comment by ChrisRackauckas** [comment]
Why does `Ref` work then?

**Comment by maleadt** [comment]
> Why does `Ref` work then?

Because we special-case it here:

https://github.com/JuliaGPU/GPUArrays.jl/blob/caff08e88cd0579c5cfa7faa4d8e1e5dad8c153c/src/host/broadcast.jl#L25-L29



> So the reason that tuples aren't working is that CUDA isn't grabbing tuples of CuArrays as being a `CuArrayStyle`:

Right, but we don't want that or the following starts to return a device array:

```julia
julia> BroadcastStyle(::Type{Tuple{AT}}) where {AT<:AbstractGPUArray} = typeof(BroadcastStyle(AT))(Val(1))

julia> julia> size.((CUDA.rand(1),))
1-element CuArray{Tuple{Int64}, 1, CUDA.Mem.DeviceBuffer}:
 (1,)
```

**Comment by ChrisRackauckas** [comment]
Looks like this has adequate solutions now.
