### ISSUE TITLE
\ does not work for least squares

### ISSUE THREAD

**Issue by kazimuth** [JuliaGPU/CUDA.jl#104]
Currently `\` only works for square matrices. If I try to solve an overdetemined system (i.e. using least squares), it gives an error.

Example:
```
A = randn(Float32, 6, 5)
y = randn(Float32, 6)
A \ y # works
gpu(A) \ gpu(y) # gives DimensionMismatch("LU factored matrix A must be square!")
```

Ideally this should "just work" like it does for normal arrays.

**Comment by just-cameron** [comment]
Any movement on this issue?

**Comment by maleadt** [comment]
Nobody has fixed this, no.

**Comment by cossio** [comment]
Running into this too. Any hints as to where in the source code should one look to attempt to fix this?

**Comment by amontoison** [comment]
> Running into this too. Any hints as to where in the source code should one look to attempt to fix this?

I think that the culprit is [here](https://github.com/JuliaGPU/CUDA.jl/blob/master/lib/cusolver/linalg.jl#L30-L34).

**Comment by maleadt** [comment]
This seems to work now.
