### ISSUE TITLE
test Cuda fails on gpuarrays\reductions/minimum maximum 

### ISSUE THREAD

**Issue by billybrickner** [JuliaGPU/CUDA.jl#1043]
**Sanity checks (read this first, then remove this section)**

- [x] Make sure you're reporting *a bug*; for general questions, please use Discourse or
  Slack.

- [x] If you're dealing with a performance issue, make sure you **disable scalar iteration**
  (`CUDA.allowscalar(false)`). Only file an issue if that shows scalar iteration happening
  in CUDA.jl or Base Julia, as opposed to your own code.

- [x] If you're seeing an error message, **follow the error message instructions**, if any
  (e.g. `inspect code with @device_code_warntype`). If you can't solve the problem using
  that information, make sure to post it as part of the issue.

- [x] Always ensure you're using the latest version of CUDA.jl, and if possible, please
  check the master branch to see if your issue hasn't been resolved yet.

If your bug is still valid, please go ahead and fill out the template below.

**Describe the bug**

Fresh install of julia on windows 11 insider preview dev build with choco install Julia
running 
```Julia
]add CUDA
test CUDA
```
fails gpuarrays\reductions/minimum maximum

**To reproduce**

The Minimal Working Example (MWE) for this bug:

```julia
test CUDA
...
[ Info: Testing using 1 device(s): 0. NVIDIA GeForce GTX 1660 (UUID 89395e51-32e3-13d6-b166-f6b3716aefd0)
                                          |          | ---------------- GPU ---------------- | ---------------- CPU ---------------- |
Test                             (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB) | GC (s) | GC % | Alloc (MB) | RSS (MB) |
...
      From worker 2:
      From worker 2:    Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
      From worker 2:    Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ffc7ee9903a -- RtlVirtualUnwind at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
      From worker 2:    in expression starting at none:1
      From worker 2:
      From worker 2:    Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
      From worker 2:    Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ffc7ee9903a -- RtlVirtualUnwind at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
      From worker 2:    in expression starting at none:1
Worker 2 terminated.
gpuarrays\reductions/minimum maximum  (2) |         failed at 2021-07-09T21:39:45.016
```

<details><summary>Manifest.toml</summary>
<p>

```
Paste your Manifest.toml here, or accurately describe which version of CUDA.jl and its dependencies (GPUArrays.jl, GPUCompiler.jl, LLVM.jl) you are using.
```
I dunno, this is the output at the beginning of the test?
┌ Info: System information:
│ CUDA toolkit 11.3.1, artifact installation
│ CUDA driver 11.4.0
│ NVIDIA driver 470.76.0
│
│ Libraries:
│ - CUBLAS: 11.5.1
│ - CURAND: 10.2.4
│ - CUFFT: 10.4.2
│ - CUSOLVER: 11.1.2
│ - CUSPARSE: 11.6.0
│ - CUPTI: 14.0.0
│ - NVML: 11.0.0+470.76
│ - CUDNN: 8.20.0 (for CUDA 11.3.0)
│ - CUTENSOR: 1.3.0 (for CUDA 11.2.0)
│
│ Toolchain:
│ - Julia: 1.6.1
│ - LLVM: 11.0.1
│ - PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
│ - Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80
│
│ 1 device:
└   0: NVIDIA GeForce GTX 1660 (sm_75, 5.269 GiB / 6.000 GiB **available)**

</p>
</details>

**Expected behavior**

The test to pass

**Version info**

Details on Julia:

```
# please post the output of:
versioninfo()
```
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD Ryzen 5 2600X Six-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, znver1)

Details on CUDA:

```
# please post the output of:
CUDA.versioninfo()
```
CUDA toolkit 11.3.1, artifact installation
CUDA driver 11.4.0
NVIDIA driver 470.76.0

Libraries:
- CUBLAS: 11.5.1
- CURAND: 10.2.4
- CUFFT: 10.4.2
- CUSOLVER: 11.1.2
- CUSPARSE: 11.6.0
- CUPTI: 14.0.0
- NVML: 11.0.0+470.76
- CUDNN: 8.20.0 (for CUDA 11.3.0)
- CUTENSOR: 1.3.0 (for CUDA 11.2.0)

Toolchain:
- Julia: 1.6.1
- LLVM: 11.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
- Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80

1 device:
  0: NVIDIA GeForce GTX 1660 (sm_75, 5.070 GiB / 6.000 GiB available)

**Additional context**

Add any other context about the problem here.]

I don't know that this urgently impacts what I'm doing, but I got a message to report it. Good Luck and I hope you are having a wonderful day.

**Comment by maleadt** [comment]
Thanks, but there's not enough info in your report to fix this. For one, the actual backtrace is missing. Does the error reproduce consistently? Can you try reducing?

**Comment by billybrickner** [comment]
Unfortunately I just rebuilt my computer so that hardware/software configuration is lost to time. Feel free to close it.

**Comment by maleadt** [comment]
Yeah, sadly we'll need a way to reproduce this. Please reopen if you run into this again!
