### ISSUE TITLE
Legacy cuIpc* APIs incompatible with stream-ordered allocator

### ISSUE THREAD

**Issue by christophernhill** [JuliaGPU/CUDA.jl#1053]
Using CUDA aware MPI with recent CUDA.jl generates 

```
The call to cuIpcGetMemHandle failed. This means the GPU RDMA protocol
cannot be used.
  cuIpcGetMemHandle return value:   1

```

from the MPI layer.  

The reason looks to be due to using cuMemCreate to manage memory in CUDA.jl is not consistent with using cuIpc* in OpenMPI on that memory. 

According to this post https://developer.nvidia.com/blog/introducing-low-level-gpu-virtual-memory-management/ (see near end)

```
Operating system native interprocess communication

The new CUDA virtual memory management functions do not support the legacy cuIpc* functions with their memory. Instead, they expose a new mechanism for interprocess communication that works better with each supported platform. This new mechanism is based on manipulating system–specific handles. On Windows, these are of type HANDLE or D3DKMT_HANDLE, while on Linux-based platforms, these are file descriptors. 

To get one of these operating system–specific handles, the new function cuMemExportToShareableHandle is introduced. The appropriate request handle types must be passed to cuMemCreate. By default, memory is not exportable, so shareable handles are not available with the default properties.

After exporting the allocation to an OS-specific handle, you can transfer the handle to another process in the usual way: Linux can use Unix-domain sockets, Windows can use DuplicateHandle. The other process may then use cuMemImportFromShareableHandle and get back a CUmemGenericAllocationHandle value that the rest of the CUDA virtual memory management functions can work with.

The CUDA sample  shows how this works in practice. This sample works on all Linux and Windows platforms that support the CUDA virtual memory management functions.
```

On test systems the result is that communication fallback to non- GPU <-> GPU direct mechanisms. On AC922 IBM system the memory bandwidth drops from 90+GB/s to more in the region of 8GB/s etc.. and latencies appear to increase. 

This "MWE" ( https://github.com/christophernhill/onan-jcon2021-bits/blob/00704dd28462a7688fcdb7484b2eaa560c1e869b/src/test_ca.jl#L1 ) will exhibit the behavior on a system with OpenMPI built with CUDA aware MPI enabled. The "MWE" also tries the using pool allocation kwargs ( https://github.com/christophernhill/onan-jcon2021-bits/blob/00704dd28462a7688fcdb7484b2eaa560c1e869b/src/test_ca.jl#L27 ) feature to see if that changes anything. The kwargs feature is not enough as the problem still exists.

**Comment by vchuravy** [comment]
On CUDA 3.3 and prior we still support the Julia managed mempools.

So I for now the workaround is to specify the environment flag:

`JULIA_CUDA_MEMORY_POOL=binned` 

#1015 removed that support and so we need a better solution for CUDA 3.4 (not yet released)

**Comment by christophernhill** [comment]
👍

**Comment by maleadt** [comment]
Let's wait and see what NVIDIA/Mellanox thinks of this. I'd rather not reinstate support for the old allocator, because that also requires restoring the old memory pools for it to perform well. But maybe, with how KA.jl manages its own buffers, `JULIA_CUDA_MEMORY_POOL=none` (which only uses the old allocator, without the old memory pools) is sufficient?

**Comment by vchuravy** [comment]
> But maybe, with how KA.jl manages its own buffers,

KA doesn't do any buffer management.
But yes the pool allocation is much less important for HPC style apps that allocate once and then reuse buffers

**Comment by maleadt** [comment]
>  But yes the pool allocation is much less important for HPC style apps that allocate once and then reuse buffers

Maybe a task-local allocation policy then? We might need something like that anyway for unified memory support.

**Comment by maleadt** [comment]
IIUC this seems to be fixed now, and UCX supports the stream-ordered allocator: https://github.com/openucx/ucx/pull/8623
