### ISSUE TITLE
Is it possible to copy any data into GPU via recursive `CuDeviceArray` construction?

### ISSUE THREAD

**Issue by GuoHaoxuan** [JuliaGPU/CUDA.jl#1057]
Only bitstype data and `CuArray` can be copied to GPU now. For non-bitstype, it could not be copied.

Non-bitstype has 2 origin:
1. `AbstractArray`
2. A struct warpped `AbstractArray`(s)

So, only if solved the `AbstractArray`s, all the data could be converted into bitstyle. Then, all the data could be copied to GPU.

But, how can we convert `AbstractArray` to a bitstyle one? `CuDeviceArray` may be an answer. 

Here is a ugly (manual) example, but is shows the principle.

```julia
using CUDA

# Construct a complex data
struct SampleType{T <: AbstractArray}
    a::T
end
origin_data = SampleType([[1,2,3], [4.0, 5.0, 6.0]])  # this will be copied to GPU

not_to_gc = [cu(x) for x in origin_data.a]  # make a reference before convert to `CuDeviceArray` to avoid GC.
part_copied_data = SampleType([cudaconvert(x) for x in not_to_gc])  # make the inside array to CuDeviceArray to ensure it is bitstyle
full_copied_data = SampleType(CuArray(part_copied_data.a))  # copy outer array to GPU
bitstyle_data = SampleType(cudaconvert(full_copied_data.a))  # make it to bitstyle to passthrough the kernel function

function sample_kernel(res, a)
  res[1] = a.a[1][1]
  nothing
end

not_to_gc[1][1] = 9876  # modify a number to validate no GC occured
res = cu([1])
@cuda sample_kernel(res, bitstyle_data)
  
print(res[1])  # it shows `9876`
```

In fact the code above could be rewritten into a recursive version to be more elegant.

Maybe this method could pass through more data to GPU.

**Comment by maleadt** [comment]
Please only use the issue tracker for actual issues :slightly_smiling_face:
This recursive transformation is what Adapt.jl is for. There's a couple of examples on Discourse, e.g., https://discourse.julialang.org/t/strange-behavior-of-cudevicearrays/62568/4
