### ISSUE TITLE
CUDA doesn't compile after upgrade to Julia 1.6.2

### ISSUE THREAD

**Issue by HenriLaurie** [JuliaGPU/CUDA.jl#1065]
I'm on a Lenovo with mixed graphics, using Manjaro (had to install from minimal, the full install didn't complete). Under v1.6.1, CUDA tested fine, with IIRC just 1 broken and 8 warnings.

Upgraded to 1.6.2 from Manjaro repository yesterday. Since then, can't get several packages to precompile, CUDA is one but also LLVM, Flux, DiffEqFlux and some of their dependencies.

There seems to be missing artefacts. Here's the error message:

```
julia> using CUDA
[ Info: Precompiling CUDA [052768ef-5323-5732-b1bb-66c8b64840ba]
ERROR: LoadError: InitError: could not load library "/home/henri/.julia/artifacts/503611619dce439df9bf3428c01561723188769b/lib/libLLVMExtra-11.so"
libLLVM-11jl.so: cannot open shared object file: No such file or directory
 ```

**Comment by maleadt** [comment]
https://github.com/maleadt/LLVM.jl/issues/253
You are using Julia without Julia's version of LLVM (e.g. by installing Julia through the package manager). This is not supported, as LLVM isn't a library that can be vendored. Please download Julia from the home page instead.

**Comment by HenriLaurie** [comment]
Thanks! Will try to take it up in Manjaro forums, but I note it seems an upstream issue: Arch seems to enforce llvm 12

**Comment by maleadt** [comment]
> it seems an upstream issue: Arch seems to enforce llvm 12

It's a long-standing issue, and people know about it, but it's not easy to fix. So for now, just download Julia from the home page, or use e.g. `julia-bin` from the AUR.
