### ISSUE TITLE
Wrapping Thrust for sorting

### ISSUE THREAD

**Issue by kose-y** [JuliaGPU/CUDA.jl#107]
**Describe the solution you'd like**
It would be great to have some of the unimplemented algorithms from Thrust, most prominently sorting. Most of the other algorithms provided seem to be already available through CuArrays.

**Describe alternatives you've considered**
There is an alternative wrapping CUB, but it seems to be a long way there according to [this](https://discourse.julialang.org/t/gpu-sort-wip-gpu-1000x-faster-than-cpu-i-must-be-doing-something-wrong/20310) discourse discussion.

**Comment by maleadt** [comment]
We have a sort kernel now.
