### ISSUE TITLE
cublasHgemmStridedBatched

### ISSUE THREAD

**Issue by bjarthur** [JuliaGPU/CUDA.jl#1076]
i see [code](https://github.com/JuliaGPU/CUDA.jl/blob/master/lib/cublas/wrappers.jl#L985-L989) for `cublas{D,S,Z,C}gemmStridedBatched`, but the half precision [issue](https://github.com/JuliaGPU/CUDA.jl/issues/391) makes me think that simply adding another single line there to support half precision is not going to work.  perhaps at all.  or perhaps nvidia will just cast to single precision and it won't be any faster.  is it worth trying?  i'm more than willing to get my hands dirty with a little advice in the right direction.  thanks!

**Comment by maleadt** [comment]
Adding the H variety there is going to work, the issue you linked to is just an overview issue.

It might be better to explore switching to cublasGemmBatchedEx or cublasGemmStridedBatchedEx though, similar to how we switched from using the old cublasXgemm APIs to cublasGemmEx. Those functions allow for more combinations, and are simpler to interface with, although they require modelling the supported input types: https://github.com/JuliaGPU/CUDA.jl/blob/bb0d432c60ae04dac67de1205405b5e382d5c9d4/lib/cublas/wrappers.jl#L807-L877
