### ISSUE TITLE
CUBLASXT test errors

### ISSUE THREAD

**Issue by ArnoStrouwen** [JuliaGPU/CUDA.jl#112]
I can run some CuArrays code such as the tutorial
```
using CuArrays
x_d = CuArrays.fill(1.0f0, N)  # a vector stored on the GPU filled with 1.0 (Float32)
y_d = CuArrays.fill(2.0f0, N)  # a vector stored on the GPU filled with 2.0
y_d .+= x_d
```
But when testing the package most test fails, I copied the very long output here:
https://gist.githubusercontent.com/ArnoStrouwen/6bd2510b3de95619ad25dd1f3102b593/raw/5025190319d1dc4308dcd2c259ddb73ce263fd15/gistfile1.txt

Details on Julia:
```
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD A8-7600 Radeon R7, 10 Compute Cores 4C+6G
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, bdver3)
```
details on GPU:
```
NVIDIA GeForce GTX 960

Driver version:	25.21.14.2600
Driver date:	21/07/2019
DirectX version:	12 (FL 12.1)
Physical location:	PCI bus 1, device 0, function 0
```
Details on CUDA: `CUDA Toolkit 10.1 Update 2`

(I need CuArrays to get DiffEqGPU.jl to work, which tests also error
https://gist.github.com/ArnoStrouwen/619cff2c3e8e48af77d5e1da46fc77ed
)

**Comment by maleadt** [comment]
There were some issues with missing synchronizations in the CUBLASxt test suite; those have been added, and likely fix this issue.
