### ISSUE TITLE
Allow invalid GPU pointers not allowed in unsafe_wrap

### ISSUE THREAD

**Issue by Am386DX-40** [JuliaGPU/CUDA.jl#1125]
**Describe the bug**

The code below used to work up to version 3.3 of CUDA.jl. In version 3.4 it results in this error message: "ERROR: Could not identify the buffer type; are you passing a valid CUDA pointer to unsafe_wrap?"

**To reproduce**

The Minimal Working Example (MWE) for this bug:

```julia
using CUDA

function register(A)
    A_buf = Mem.register(Mem.Host, pointer(A), sizeof(A), Mem.HOSTREGISTER_DEVICEMAP)
    A_gpuptr = convert(CuPtr{Float64}, A_buf)
    return unsafe_wrap(CuArray, A_gpuptr, size(A));
end

nx = 512*512*1024;
A = zeros(nx);
A_d = register(A);
```

The code was copied from: https://discourse.julialang.org/t/cudanative-register-host-memory-for-pinned-memory-access/23046/20

**Comment by omlins** [comment]
This is also used in ImplicitGlobalGrid.jl:
https://github.com/eth-cscs/ImplicitGlobalGrid.jl/blob/master/src/shared.jl#L110

Could that use case make it to the CUDA.jl unit tests?
Thanks!!

**Comment by omlins** [comment]
@maleadt , could you soon tag a new release? ImplicitGlobalGrid.jl fails due to this bug with version 3.4...

**Comment by maleadt** [comment]
Yes, I was preparing to create a release this week.

**Comment by omlins** [comment]
> Yes, I was preparing to create a release this week.

Great, thanks!
