### ISSUE TITLE
Scalar Indexing error in the Introduction docs

### ISSUE THREAD

**Issue by Dsantra92** [JuliaGPU/CUDA.jl#1127]
`CUDA.fill` does not support scalar indexing, so a part of code in the [docs](https://github.com/JuliaGPU/CUDA.jl/blob/master/docs/src/tutorials/introduction.jl#L132-133) does not work. Simply chaging the line from 
```julia
CUDA.fill(1.0f0, N)
```` 
to 
```julia
CUDA.fill(1.0f0, N, 1)
```
does the job. 
Is there something from the tutorial I am missing here? or is there a planned support for scalar indexes in future? If not, I can make a pr to fix the docs if you are interested.

**Comment by maleadt** [comment]
Works fine?

```
julia> CUDA.allowscalar(false)

julia> N = 2^20
1048576

julia> x_d = CUDA.fill(1.0f0, N)
1048576-element CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}:
```
