### ISSUE TITLE
stackoverflow when printing a custom subtype of AbstractCuSparseMatrix

### ISSUE THREAD

**Issue by Roger-luo** [JuliaGPU/CUDA.jl#1128]
one would get a stackoverflow error when subtyping `AbstractCuSparseMatrix` with custom sparse matrix format

```julia
julia> CuSparseMatrixBCSR(dA)
5×6 CuSparseMatrixBCSR{Float64} with 14 stored entries:Error showing value of type CuSparseMatrixBCSR{Float64}:
ERROR: StackOverflowError:
Stacktrace:
  [1] get_have_color()
    @ Base ./ttyhascolor.jl:19
  [2] get
    @ ./ttyhascolor.jl:27 [inlined]
  [3] unwrapcontext
    @ ./show.jl:235 [inlined]
  [4] IOContext
    @ ./show.jl:239 [inlined]
  [5] convert
    @ ./show.jl:243 [inlined]
  [6] show(io::IOContext{Base.TTY}, S::CuSparseMatrixBCSR{Float64}) (repeats 32454 times)
    @ CUDA.CUSPARSE ~/.julia/packages/CUDA/VGl9W/lib/cusparse/array.jl:408
  [7] show(io::IOContext{Base.TTY}, #unused#::MIME{Symbol("text/plain")}, S::CuSparseMatrixBCSR{Float64})
    @ CUDA.CUSPARSE ~/.julia/packages/CUDA/VGl9W/lib/cusparse/array.jl:416
  [8] (::REPL.var"#38#39"{REPL.REPLDisplay{REPL.LineEditREPL}, MIME{Symbol("text/plain")}, Base.RefValue{Any}})(io::Any)
    @ REPL /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:220
```

this is because when the CUDA sparse type doesn't define `Base.show`, the program would go to this line

https://github.com/JuliaGPU/CUDA.jl/blob/master/lib/cusparse/array.jl#L416

however, Julia's `show(io, x)` method would fallback to `show(io, ::MIME"text/plain", x)` so it would stackoverflow, I'm not sure the best way to fix this, but I think the CUDA sparse types should just forward
`Base.show(io, ::MIME"text/plain", x)` to corresponding CPU printings instead of forwarding `Base.show(io, x)`?

**Comment by maleadt** [comment]
Not a bug, since this only triggers with custom sparse array types, but I'll have a look at improving this.
