### ISSUE TITLE
missing `rand` methods

### ISSUE THREAD

**Issue by bjarthur** [JuliaGPU/CUDA.jl#1138]
`rand(CUDA.default_rng(), 3)` emits an error, and `rand(CUDA.default_rng(), Float32, 3)` returns a Vector not a CuVector.  the same methods for CURAND.default_rng() work just fine.

**Comment by bjarthur** [comment]
relatedly, `Random.seed!(CUDA.default_rng())` is missing a method while `Random.seed!(CURAND.default_rng())` works fine.

**Comment by maleadt** [comment]
Ah, interesting, Also fixed in the linked PR, which I had forgotten about; I'll merge it as soon as it passes CI.
