### ISSUE TITLE
Specifying eltype and buffer type when adapting to `CuArray`?

### ISSUE THREAD

**Issue by ToucheSir** [JuliaGPU/CUDA.jl#1171]
**Is your feature request related to a problem? Please describe.**

Currently, converting a normal (dense) array into a CuArray through Adapt can take 1 of 2 paths: https://github.com/JuliaGPU/CUDA.jl/blob/v3.4.2/src/array.jl#L426-L437 allows one to specify a buffer type but may modify the eltype to its liking. https://github.com/JuliaGPU/CUDA.jl/blob/v3.4.2/src/array.jl#L325 passes through the eltype but ignores the buffer type.

**Describe the solution you'd like**

`adapt_storage` method(s) that take both eltype `T` and buffer type `B`. Either `CuArrayAdaptor` or `CuArray` would be workable for this.

**Describe alternatives you've considered**

We could implement these methods downstream, but risk duplicating CUDA internal logic that might drift over time. Maintaining the eltype but unconditionally moving into device buffers would hardly be a regression given how new the unified memory support is, but I imagine this might be more important moving forward.

**Additional context**

This came up in the context of brainstorming what good AD rules for CPU <-> GPU movement might be. I sketched out a draft in https://github.com/FluxML/Flux.jl/pull/1708#discussion_r717972053, but there are likely many edge cases that haven't been considered. For example, moving unified arrays back and forth could just involve a re-wrapping of the buffer(s) instead of a full copy, assuming of course the lack of a defensive copy is acceptable.

**Comment by maleadt** [comment]
> We could implement these methods downstream, but risk duplicating CUDA internal logic that might drift over time.

How so? You'd just be using `CuArray` constructors (while specifying the buffer type), so what kind of internal logic would you be duplicating? `CuArrayAdaptor` is just intended as a tool to support `cu`, and not something exported. Wouldn't it be easier to create your own adaptor?

**Comment by ToucheSir** [comment]
> You'd just be using `CuArray` constructors (while specifying the buffer type), so what kind of internal logic would you be duplicating?

I was hoping to avoid the constructor because I wasn't sure if AD would be able to reconstruct sparse arrays with just that one rule, but I'll have another try at it. Thanks for the suggestion!

**Comment by maleadt** [comment]
> I wasn't sure if AD would be able to reconstruct sparse arrays with just that one rule

I'm not too familiar with the AD stack, so if there's anything to improve in CUDA.jl I'm happy to accommodate where possible.
I'll close this for now, but feel free to re-open or create a new issue if you think that's the case.
