### ISSUE TITLE
Inefficient `lop3.lut` instructions generated

### ISSUE THREAD

**Issue by eschnett** [JuliaGPU/CUDA.jl#1172]
I want to combine ("merge") two integers depending on a bit mask, as in
```C
res = a & mask | b & ~mask
```
All values are `UInt32`. According to my understanding, this is possible with a single `lop3.b32` instruction; see e.g. here <https://stackoverflow.com/questions/37149662/how-to-write-lop3-based-instructions-for-maxwell-and-up-nvidia-architecture>. `mask` is known at compile time, it is e.g. `0x7f7f7f7f`.

I checked via `@device_code_ptx`, and the expression above is translated rather verbatim to PTX instructions for `and` and `or`. `@device_code_sass` then shows two `lop3.lut` instruction (not just one), the first calculating `a & mask`, the second calculating `... | b & ~mask`.

I want this to be translated to a single SASS instruction. Ideally, of course, LLVM would perform this optimization, but I don't know how to add the respective optimization. I would be happy with calling an intrinsic function or using `ccall`, but I cannot find an LLVM intrinsic for `lop.b32` (I checked `IntrinsicsNVVM.td` in LLVM).

What other options do I have? Is there e.g. a way to write PTX (or even SASS) code in Julia?

**Comment by maleadt** [comment]
> What other options do I have? Is there e.g. a way to write PTX (or even SASS) code in Julia?

Yes! You can write inline PTX code using LLVM's `@asmcall` (which follows https://llvm.org/docs/LangRef.html#inline-assembler-expressions). Inline SASS is not possible.

**Comment by eschnett** [comment]
Thanks!

For the record, this is how it looks like:
```Julia
using LLVM
function cuda_lop3(x::UInt32, y::UInt32, z::UInt32, op::UInt32)
    LLVM.Interop.@asmcall("lop3.b32 \$0, \$1, \$2, \$3, \$4;", "=r,r,r,r,i", UInt32, Tuple{UInt32,UInt32,UInt32,UInt32}, x, y, z,
                          op)
end
```

**Comment by maleadt** [comment]
Great! Does this affect performance significantly? If so, it might be worth keeping this open; we have an `upstream` issue label for that (in case somebody wants to work on LLVM-related issues that benefit Julia/CUDA.jl).

**Comment by eschnett** [comment]
I don't know yet whether it affects performance of my kernel. It's somewhat unlikely – our estimate says that this part of the kernel might be limited by warp shuffles. I'm still implementing the kernel, and I am looking at SASS mostly to ensure that the generated code "looks reasonable".

**Comment by maleadt** [comment]
If you're looking into kernel performance, you might be interested in https://github.com/JuliaGPU/CUDA.jl/pull/1153 (or at least the improved version in https://github.com/JuliaGPU/CUDA.jl/pull/1167). Using Int32 hardware indices has led to a 10% register reduction for some realistic kernels.

**Comment by eschnett** [comment]
Thanks for the pointers. I'm very careful in my code to use `Int32` wherever possible, and also making sure that the various `+1` and `-1` for Julia's array indexing cancel without a trace. On the GPUs I'm using, 64-bit operations are quite a bit more expensive than 32-bit operations, and Julia's default of using `Int64` is inconvenient and requires many explicit type annotations.

I like the `i32` idea.

**Comment by maleadt** [comment]
Yes, the `i32` constant is a gimmick, but it's nice. What's also interesting about that PR is that it ensures the `-1`/`+1` changes are canceled out in a way that keeps the 32-bit width of the hardware indices (it used to `zext`, making it impossible to generate `mad` instruction for array indexing), which required changes to `CuDeviceArray`. But maybe you weren't using the array types in your code.

**Comment by eschnett** [comment]
I am using `CuArray` for arrays. I found that this pattern works for me:
```Julia
idx = ... :: Int32
mem[1 + idx]
```
My array indices are small enough to fit into 32 bits, which speeds up their calculation. The actual array access extends to 64 bits, adds one, and the CuArray code then subtracts one, which cancels nicely.

It would be good if that optimization becomes more stable in the future (maybe the recent changes did that).
