### ISSUE TITLE
Synchronizing over blocks

### ISSUE THREAD

**Issue by glwagner** [JuliaGPU/CUDA.jl#1220]
Over at Oceananigans we're having issues with kernel launch overhead for a particular problem. To solve this problem, we want to fuse our kernels as much as possible. However, our algorithm requires synchronization over global memory (eg we to perform a global reduction _after_ performing arithemetic operations).

Here's an example that @simone-silvestri and I put together:

```julia
using CUDA

heavy_computation(one, zero) = exp(-one) * cos(zero) * cos(zero) * exp(cos(zero))^2

""" A kernel that requires device-wide synchronization. """
function test_kernel!(a, one, zero)

    i = (blockIdx().x - 1) * blockDim().x + threadIdx().x + 1 # 2:Nx+1
    j = (blockIdx().y - 1) * blockDim().y + threadIdx().y + 1 # 2:Ny+1

    a[i-1, j-1] = heavy_computation(one, zero)

    sync_threads()
    #CUDA.device_synchronize()
    #sync_threads()

    a[i, j] = a[i+1, j+1]

    return nothing
end

""" Determine whether `test_kernel` has a race condition. """
function find_race_condition(N=(32, 32), max_computations=1000)
    Nx, Ny = N

    blocks = Int64.(N ./ 32)
    threads = Int64.(N ./ blocks)
    a_device = CUDA.zeros(Float64, Nx+2, Ny+2)

    computations = 0

    @info "Race condition test with blocks $blocks and threads $threads"

    while computations < max_computations
        a_device .= 1
        computations += 1

        @cuda threads=threads blocks=blocks test_kernel!(a_device, 1.0, 0.0)

        a_test = Array(a_device)[2:Nx-1, 2:Ny-1]

        if any(a_test .== 1)
            idx = findfirst(a -> a == 1, a_test)
            @info """

                Race condition found at $idx after $computations attempt
                blocks = $blocks
                threads = $threads
            """
            return nothing
        end
    end

    return @info """

        No race condition found
        blocks = $blocks
        threads = $threads
    """
end

find_race_condition((32, 32)) # no race condition when sync_threads() is called
find_race_condition((64, 64)) # has race condition
```

On a Titan V we get

```julia
julia> include("cuda_test.jl")
[ Info: Race condition test with blocks (1, 1) and threads (32, 32)
┌ Info:
│     No race condition found
│     blocks = (1, 1)
└     threads = (32, 32)
[ Info: Race condition test with blocks (2, 2) and threads (32, 32)
┌ Info:
│     Race condition found at CartesianIndex(31, 1) after 1 attempt
│     blocks = (2, 2)
└     threads = (32, 32)
```
Here's a few observations:

* `device_synchronize()` does not solve the race condition
* If `device_synchronize()` is called _after_ `sync_threads()`, this prevents block-wide synchronization (ie, we get a race condition if we uncomment `device_synchronize()` in `test_kernel`

But from what I and @simone-silvestri understand there's no interface to `cudaDeviceSynchronize` (is this correct?)

Is there a way to synchronize _across blocks_ within a kernel? If not, we'd like that feature! Also: are we using `device_synchronize()` incorrectly, or making some other mistake?

**Comment by maleadt** [comment]
> But from what I and @simone-silvestri understand there's no interface to `cudaDeviceSynchronize` (is this correct?)

You're already calling this function:

https://github.com/JuliaGPU/CUDA.jl/blob/80a5978f2dd62c48f95a976024d0510868696b21/src/device/intrinsics/dynamic_parallelism.jl#L112

But it cannot be used to perform a grid synchronization, https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#synchronization-programming-interface

> The cudaDeviceSynchronize() function will synchronize on all work launched by any thread in the thread-block up to the point where cudaDeviceSynchronize() was called.

I guess you want to use cooperative groups for this, but our wrappers for that functionality is sparse. That said, requiring the grid to synchronize is very expensive, and could result in only a single SM being used (I'm not sure what the hardware actually supports for synchronizing across blocks on different SMs).

**Comment by vchuravy** [comment]
> I'm not sure what the hardware actually supports for synchronizing across blocks on different SMs

IIRC correctly from starting at the CG code, it's a barrier in global memory.

**Comment by maleadt** [comment]
I'll close this then, not much we can do except for extending the cooperative group wrappers. Please open another issue or PR if anything there is lacking: https://github.com/JuliaGPU/CUDA.jl/blob/5b74388a32b6bac6f1c12c550486f373a150ac4d/test/execution.jl#L1031-L1057
