### ISSUE TITLE
CUSPARSE typo

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CUDA.jl#1231]
This should be the other way around, probably: https://github.com/JuliaGPU/CUDA.jl/pull/904/files#diff-416606e9f5d8f57045482fc9fc855bccc8f31a27969e609160b17cc793501ae6R87

**Comment by kshyatt** [comment]
https://docs.nvidia.com/cuda/cusparse/index.html#cusparse-generic-function-spmv I don't think so?

**Comment by maleadt** [comment]
So older versions of cuSPARSE _did_ support uniform Float16 spMV while current versions don't?

**Comment by kshyatt** [comment]
I think so, yeah.
