### ISSUE TITLE
Calling Flux.gpu on a view dumps core

### ISSUE THREAD

**Issue by jessebett** [JuliaGPU/CUDA.jl#125]
```
using MLDataUtils
using CuArrays
using Flux

x = rand(4,10)
x_b = batchview(x,7)
x_g = gpu.(x_b) # works

x_g = gpu(x_b) # aborts with core dumped
```

Not clear if this is a CuArrays problem or a `Flux.gpu` issue, but if you call `gpu` on a view, like provided by `MLDataUtils.batchview` broadcasted it will abort with `(core dumped)`

**Comment by maleadt** [comment]
Going to close this stale issue. If something like this still happens, please open a new issue with updated information
