### ISSUE TITLE
three CUDA.@atomic in a row result in out-of-bounds error

### ISSUE THREAD

**Issue by bjarthur** [JuliaGPU/CUDA.jl#1254]
but only on a 1080Ti.  works fine on an A100.  if i delete one of them, it also works.  a minimum broken example would take some time to write.  wanted to inquire whether this is a known issue before i investigate further.  kernel as it is now looks like this:

```
function kernel(bspike,
                w0Index, w0Weights, forwardInputsE, forwardInputsI,
                wpIndexOut, wpWeightOut, forwardInputsP)
    i = threadIdx().x + (blockIdx().x - 1) * blockDim().x
    j = threadIdx().y + (blockIdx().y - 1) * blockDim().y

    if bspike[j]
        if i<=size(w0Index,1)
            CUDA.@atomic forwardInputsE[0x1 + w0Index[i,j]] += max(w0Weights[i,j], 0)
            CUDA.@atomic forwardInputsI[0x1 + w0Index[i,j]] += min(w0Weights[i,j], 0)
        end
        if i<=size(wpIndexOut,1)
            CUDA.@atomic forwardInputsP[0x1 + wpIndexOut[i,j]] += wpWeightOut[i,j]
        end
    end
    return nothing
end
```

this is with julia 1.7-rc2, CUDA.jl 3.5.0, and CUDA 11.2 for the 1080Ti and 11.4 for the A100.  thanks.

**Comment by bjarthur** [comment]
oh, and it works on a 2080Ti too with 11.4.  so maybe it's just broken for 11.2??

**Comment by maleadt** [comment]
Define 'broken'? Please include at least a stack trace or compiler error. Generally this would require a MWE, I don't see what shouldn't work about multiple `@atomic` invocations.

**Comment by bjarthur** [comment]
i can't reproduce now.  sorry.  will re-open if/when i can.
