### ISSUE TITLE
Get back `unsafe_copyto!`methods for unified<-unified and unified<->device

### ISSUE THREAD

**Issue by danielwe** [JuliaGPU/CUDA.jl#1263]
Follow-up on https://github.com/JuliaGPU/CUDA.jl/pull/1177#issuecomment-988368726, which was misplaced and should have been a comment on #1176.

As acknowledged in the TODO comment linked below, #1176 made `unsafe_copyto!` methods more specific, thus leaving out certain combinations including copies from unified memory to regular CuArrays in device memory.

https://github.com/JuliaGPU/CUDA.jl/pull/1176/commits/cda026fa9b2f1ed9f3f00fcb316c37ac1e42422c#diff-e9f2a6b99d3b555edce8867c798cc88f2d6416b1f170225ec159a2af7cf30c8eR473

I can come back with an MWE tomorrow, but I think the TODO comment is clear enough about what kinds of copies are currently missing: unified<-unified, unified<-device, and device<-unified. My questions are:

* Are there plans to resolve this TODO in the near future?
* Were such copies safe before #1176, or have they only worked by accident?

Apologies for posting my original comment to the wrong PR and creating confusion.

**Comment by maleadt** [comment]
I've just expanded the existing definitions for unoptimized combinations (like the ones mentioned in the TODO); the API should handle it fine, although there could be better ways to perform such copies. Please verify this fixes your issue.

**Comment by danielwe** [comment]
Thanks! With the fix, the copies work as long as the unified and device arrays were created within the same context. However, contexts are device-specific, so this is quite constraining for unified memory use cases, and still breaks the code I had. As far as I understand this constraint is unnecessary, since unified memory lives in a shared address space that can be accessed from any device and hence any context. The more fundamental issue is perhaps that wrapping a buffer in a `CuArray` necessarily associates a context with it, even when the buffer is in unified memory.

MWE to trigger the issue:

```julia
using CUDA

function unified_cuarray(::Type{T}, dims::NTuple{N}) where {T, N}
    buf = Mem.alloc(Mem.Unified, prod(dims) * sizeof(T))
    array = unsafe_wrap(CuArray{T, N}, convert(CuPtr{T}, buf), dims)
    finalizer(_ -> Mem.free(buf), array)
    return array
end

device!(0)
A = CUDA.rand(5, 5)
device!(1)
U = unified_cuarray(Float32, (5, 5))
device!(0)
copyto!(U, A)
```

```
julia> copyto!(U, A)
ERROR: ArgumentError: copying between arrays from different contexts
Stacktrace:
 [1] unsafe_copyto!(dest::CuArray{Float32, 2, CUDA.Mem.UnifiedBuffer}, doffs::Int64, src::CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, soffs::Int64, n::Int64)
   @ CUDA ~/.julia/packages/CUDA/rErlr/src/array.jl:423
 [2] copyto!
   @ ~/.julia/packages/CUDA/rErlr/src/array.jl:370 [inlined]
 [3] copyto!(dest::CuArray{Float32, 2, CUDA.Mem.UnifiedBuffer}, src::CuArray{Float32, 2, CUDA.Mem.DeviceBuffer})
   @ CUDA ~/.julia/packages/CUDA/rErlr/src/array.jl:374
 [4] top-level scope
   @ REPL[11]:1
 [5] top-level scope
   @ ~/.julia/packages/CUDA/rErlr/src/initialization.jl:52
```

This seems very specific to `copyto!`. Kernels work as expected, and in particular, this does the trick:

```julia
U .= A
```

I'd prefer to be able to use the API for straight copies though. Compiling a kernel for this (which is what happens behind the scenes here, right?) feels pretty wasteful and takes a lot of time for the first copy.

---

Edit: added trace

**Comment by danielwe** [comment]
Based on the above, which still represents a regression for the code I was using, I think this issue warrants reopening (totally understand it's probably not your top priority though).

**Comment by maleadt** [comment]
Thanks for the example, I think I have that covered in https://github.com/JuliaGPU/CUDA.jl/pull/1277 now.

**Comment by maleadt** [comment]
Please let me know if that covers your use case, I'd like to release a new version this week.

**Comment by danielwe** [comment]
It works now. Fantastic, thanks! Apologies for my long turnaround time.

The unified arrays still have a context kind of arbitrarily attached to them, but I guess that does little harm and would be annoying to change. One thing I thought about was letting `U.storage.ctx === nothing`---that would be sure to raise an error anytime someone tries to use the context of unified storage, but I don't know how much of the existing code would break.

**Comment by maleadt** [comment]
> The unified arrays still have a context kind of arbitrarily attached to them

Is it arbitrary? Can we allocate in one context and free in another? The memory being accessible in either doesn't imply all operations are context insensitive.

**Comment by danielwe** [comment]
Oh, perhaps not. I did my best to read and understand https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#um-unified-memory-programming-hd when figuring out what was going on here, and all it says about contexts is in the context of global unified variables, which doesn't seem relevant to CUDA.jl. But this is really way above my pay grade and you can safely disregard my clumsy comment above.
