### ISSUE TITLE
sparse-sparse and sparse-constant multiplication lose sparsity (output dense matrix)

### ISSUE THREAD

**Issue by learning-chip** [JuliaGPU/CUDA.jl#1264]
**Describe the bug**

Multiplication of two `CuSparseMatrixCSC` returns a dense `Matrix` on CPU. With `CUDA.allowscalar(false)`, such operation is disallowed. Same problem when `CuSparseMatrixCSC` times a constant.

Related:  #528 (sparse-sparse add), #1120 (dense-sparse add and mul), #829 (sparse element-wise mul)

**To reproduce**

```julia
using SparseArrays, CUDA.CUSPARSE, CUDA
A_cpu = spdiagm(ones(3))
A_gpu = CuSparseMatrixCSC(A_cpu)

CUDA.allowscalar(true)  # if false, disables following operations
A_gpu * A_gpu  # output 3×3 Matrix{Float64} on CPU
A_gpu * 2.0  # output 3×3 Matrix{Float64} on CPU
A_gpu .* 2.0  # same as above
A_gpu + A_gpu  # UndefVarError: geam not defined, see issue #528
```

For the CPU array `A_cpu`, the equivalent operations output sparse matrices with correct sparsity patterns.

<details><summary>Manifest.toml</summary>
<p>

```
[[CUDA]]
deps = ["AbstractFFTs", "Adapt", "BFloat16s", "CEnum", "CompilerSupportLibraries_jll", "ExprTools", "GPUArrays", "GPUCompiler", "LLVM", "LazyArtifacts", "Libdl", "LinearAlgebra", "Logging", "Printf", "Random", "Random123", "RandomNumbers", "Reexport", "Requires", "SparseArrays", "SpecialFunctions", "TimerOutputs"]
git-tree-sha1 = "2c8329f16addffd09e6ca84c556e2185a4933c64"
uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
version = "3.5.0"

[[GPUArrays]]
deps = ["Adapt", "LinearAlgebra", "Printf", "Random", "Serialization", "Statistics"]
git-tree-sha1 = "7772508f17f1d482fe0df72cabc5b55bec06bbe0"
uuid = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
version = "8.1.2"

[[GPUCompiler]]
deps = ["ExprTools", "InteractiveUtils", "LLVM", "Libdl", "Logging", "TimerOutputs", "UUIDs"]
git-tree-sha1 = "6cf994358b3821ea446c43dea08c38aceb60a0cc"
uuid = "61eb1bfa-7361-4325-ad38-22787b887f55"
version = "0.13.8"

[[LLVM]]
deps = ["CEnum", "LLVMExtra_jll", "Libdl", "Printf", "Unicode"]
git-tree-sha1 = "7cc22e69995e2329cc047a879395b2b74647ab5f"
uuid = "929cbde3-209d-540e-8aea-75f648917ca0"
version = "4.7.0"
```

</p>
</details>

**Expected behavior**

The behavior of `CuSparseMatrixCSC` shoud match that of CPU `SparseMatrixCSC`, which keeps sparsity and minimizes compute&memory costs.

For reference, the PyTorch 1.9 [`torch.sparse.mm`](https://pytorch.org/docs/stable/generated/torch.sparse.mm.html) keeps sparsity on GPU (and allows autodiff). Given that PyTorch also calls cuSPARSE for almost all sparse ops, I think CUDA.jl can follow the same approach. A minimal example:

```python
import torch
i = [[0, 1, 2],
     [0, 1, 2]]
v =  [1, 1, 1]
A = torch.sparse_coo_tensor(
    i, v, (3, 3), dtype=torch.float64, device=torch.device('cuda:0')
)
torch.sparse.mm(A, A)  # works correctly
```

**Version info**

Details on Julia:

```
Julia Version 1.6.3
Commit ae8452a9e0 (2021-09-23 17:34 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) Platinum 8180 CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake-avx512)
```

Details on CUDA:

```
CUDA toolkit 11.4, artifact installation
NVIDIA driver 460.91.3, for CUDA 11.2
CUDA driver 11.4

Libraries: 
- CUBLAS: 11.5.4
- CURAND: 10.2.5
- CUFFT: 10.5.1
- CUSOLVER: 11.2.0
- CUSPARSE: 11.6.0
- CUPTI: 14.0.0
- NVML: 11.0.0+460.91.3
- CUDNN: 8.20.2 (for CUDA 11.4.0)
- CUTENSOR: 1.3.0 (for CUDA 11.2.0)

Toolchain:
- Julia: 1.6.3
- LLVM: 11.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
- Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80
```

**Comment by maleadt** [comment]
Most of this is covered in https://github.com/JuliaGPU/CUDA.jl/issues/1113 already. Did you try the master branch? There's been a couple of improvements already.

**Comment by learning-chip** [comment]
I think #1113 is about `dense * sparse` but here the case is `sparse * sparse`

**Comment by maleadt** [comment]
These operations are not supported by CUSPARSE. The only available ones are SpMM from the generic API, `The function performs the multiplication of a sparse matrix matA and a dense matrix matB`, and the Level 3 BLAS APIs which provide `sparse linear algebra functions that perform operations between sparse and (usually tall) dense matrices`. Or is there an API you have in mind?

Since we can't reasonably promote any of the sparse inputs to a dense matrix, I don't think we can solve this without implementing sparse matrix multiplication ourselves. That's a considerable effort I'm not planning to spend time on, but anybody is welcome to create a PR.

In the meantime, I don't think we should keep this issue open.

**Comment by learning-chip** [comment]
> These operations are not supported by CUSPARSE.

They are supported -- `sparse * sparse` is done by `csrgemm` & `csrgemm2`, and `sparse + sparse` is by `csrgeam` & `csrgeam2`. You can find the implementations in:

- CuPy source code [cusparse.py](https://github.com/cupy/cupy/blob/v10.0.0/cupy/cusparse.py), search for `csrgemm`/`csrgeam` function
- PyTorch source code [ATen/native/sparse/cuda/SparseMatMul.cu](https://github.com/pytorch/pytorch/blob/v1.10.0/aten/src/ATen/native/sparse/cuda/SparseMatMul.cu), search for `sparse_sparse_matmul_cuda_kernel` function
- For autograd (backed by cusparse), see [torch/csrc/autograd/FunctionsManual.cpp](https://github.com/pytorch/pytorch/blob/v1.10.0/torch/csrc/autograd/FunctionsManual.cpp), search for `sparse_sparse_matmul_backward` function

So this issue is different from #1271 (which targets other unsupported operations). I think it should be reopen.

**Comment by maleadt** [comment]
Ah yes, I missed those. `csrgemm` is deprecated though, that needs to be `cusparseSpGEMM()`. `csrgeam2` is still available.

**Comment by maleadt** [comment]
Fixed by https://github.com/JuliaGPU/CUDA.jl/pull/1285
