### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by mo8it** [JuliaGPU/CUDA.jl#1276]
**Problem**

Latest CUDA.jl 3.5.0 holds SpecialFunctions.jl 2.0 back which causes a dependency hell when using other packages.

**To reproduce**

Add CUDA and SpecialFunctions@2 in a new environment.

**Expected behavior**

CUDA should not hold SpecialFunctions.jl 2.0 back.

I know that version 2 is in the `Project.toml`. But please, release a (minor) new version to apply the dependency update. Thanks!

**Comment by maleadt** [comment]
I'll release a new version this week.

**Comment by maleadt** [comment]
v3.5.0 has been released.

**Comment by devmotion** [comment]
> v3.5.0 has been released.

3.5.0 was released on October 11 it seems. I noticed that you updated the version number in Project.toml to 3.6.0 but it's not available in the registry yet (https://github.com/JuliaRegistries/General/blob/master/C/CUDA/Versions.toml) and I couldn't find any PR to the registry. Are you sure it is released?

**Comment by maleadt** [comment]
Oh oops, I did the version bump last Friday -- https://github.com/JuliaGPU/CUDA.jl/commit/fd68d9d5f507b1e01ccbd61192b28e4404a684d0 -- but forgot to invoke the Registrator. Let me do that today.
