### ISSUE TITLE
`__init_driver__` not called in 3.5

### ISSUE THREAD

**Issue by mwarusz** [JuliaGPU/CUDA.jl#1280]
I noticed a substantial slowdown (30%) of one of my codes after upgrading CUDA.jl to 3.5.
I bisected it to 0bc11915e9f4a165c86e4259d3bb4850d7e6e0c2.
It seems that after this commit the `__init_driver__` function is no longer called and the
`-nvptx-fma-level=1` LLVM option is not set, inhibiting fma generation.

@lcw

**Comment by maleadt** [comment]
Thanks for the bisect! Re-introduced the call in https://github.com/JuliaGPU/CUDA.jl/pull/1287.
