### ISSUE TITLE
reduce_block error on Complex type

### ISSUE THREAD

**Issue by mloubout** [JuliaGPU/CUDA.jl#1289]
**Sanity checks (read this first, then remove this section)**

**Describe the bug**

The modification introduced in this [commit](https://github.com/JuliaGPU/CUDA.jl/commit/35d81474a419b70a89e962549d1a70d4f090c6d0)  are leading to kernel errors in some cases. In particular in makes the norm error on `Complex{Int16}` for example.

**To reproduce**

The Minimal Working Example (MWE) for this bug:

```julia
using CUDA, LinearAlgebra
 norm(cu( rand(Complex{Int16}.(1:10), (2,))), 1)
```
To reproduce this bug, two main components are needed:
- CUDA.jl#master
- https://github.com/JuliaGPU/GPUArrays.jl/pull/382 : This pull request fixes the return type of norms for complex-valued arrays. This PR is currently block in failing CI due to failing norms with the bugdescribed here.

**Expected behavior**

The previous implementation `offset+len > dynamic_smem_size()` does not error but the new check `offset+sz > dynamic_smem_size()` does

**Version info**

Details on Julia:

```
Julia Version 1.7.0
Commit 3bf9d17731 (2021-11-30 12:12 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1270 v6 @ 3.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_CUDA_USE_BINARYBUILDER = false
  JULIA_BINDIR = /home/mlouboutin3/GATechBundle/Julia/julia-1.7.0/bin
  JULIA_NUM_THREADS = auto
```

Details on CUDA:

```
CUDA toolkit 11.2, local installation
NVIDIA driver 460.84.0, for CUDA 11.2
CUDA driver 11.4

Libraries: 
- CUBLAS: 11.4.1
- CURAND: 10.2.3
- CUFFT: 10.4.0
- CUSOLVER: 11.1.0
- CUSPARSE: 11.4.0
- CUPTI: 14.0.0
- NVML: 11.0.0+460.84
- CUDNN: 8.30.1 (for CUDA 11.5.0)
- CUTENSOR: 1.2.2 (for CUDA 11.1.0)

Toolchain:
- Julia: 1.7.0
- LLVM: 12.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
- Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80

Environment:
- JULIA_CUDA_USE_BINARYBUILDER: false

1 device:
  0: Quadro P1000 (sm_61, 3.685 GiB / 3.932 GiB available) 
```

**Comment by maleadt** [comment]
> The previous implementation `offset+len > dynamic_smem_size()` does not error but the new check `offset+sz > dynamic_smem_size()` does

Then the amount of dynamic shared memory configured somewhere is wrong.

**Comment by mloubout** [comment]
The amount of share memory is correct. This is a weird corner case of norm where the result is higher type. Closing this as not an actual issue and will push fix to 
https://github.com/JuliaGPU/GPUArrays.jl/pull/382

**Comment by maleadt** [comment]
So it isn't related to the boundscheck conditional?

**Comment by mloubout** [comment]
No. The boundscheck conditional is correct and was rightfully erroring since it was allocating memory for a `Complex{Int16}` and trying to write a `Float64` into it because that's what `f` (in maprduce) was returning. So it was an issue in `norm` that wasn't defining the correct type for the output leading to this memory size mismatch. WIth norm fixed it's now all good.
