### ISSUE TITLE
Support to find the first k eigenvalues of a sparse matrix

### ISSUE THREAD

**Issue by albertomercurio** [JuliaGPU/CUDA.jl#1292]
I need a feature in which I can set the number of eigenvalues to return for a sparse hermitian matrix.

As I noticed reading the source code (since there isn't a documentation), the actual `CUSOLVER.csreigvsi` function is what I search. However it returns only one eigenvalue (with its associate eigenvector), and it seems there is no way to get k nearest eigenvalues instead than only one.

Is there a way to do that?

Moreover, I noticed that the arguments of the function are in this order:
- The sparse CSR matrix
- The sigma shift for the shift-inverse method
- The initial guess vector
- The tolerance
- The number of maximum iterations
- And a character (I used only 'O')

what is the rule of 'O' argument?

**Comment by maleadt** [comment]
> what is the rule of 'O' argument?

The indexing base, 0 or 1 indexed. Refer to the CUSOLVER documentation.

**Comment by albertomercurio** [comment]
> > what is the rule of 'O' argument?
> 
> The indexing base, 0 or 1 indexed. Refer to the CUSOLVER documentation.

I read the documentation, but I still don't understand what they are. The only thing written is "_**The CSR or CSC format requires either zero-based or one-based index for a sparse matrix A. The GLU library supports only zero-based indexing. Otherwise, both one-based and zero-based indexing are supported in cuSolver.**_"

Aside from this indexing detail, can we have a method to derive multiple eigenvalues from a sparse hermitian matrix?

**Comment by maleadt** [comment]
The method you're referring to is a sparse matrix method, so it takes an array of indices. Those can be either zero or one-based.

It seems like what you're asking for is not supported by CUSOLVER, e.g. https://forums.developer.nvidia.com/t/using-cusolver-to-find-all-eigenvectors-values-of-a-sparse-matrix/58397. But refer to the NVIDIA library documentation for more details, I'm not familiar with the entire extent of those libraries. There are no plans for the CUSOLVER/CUSPARSE modules in CUDA.jl to go beyond what the respective NVIDIA libraries have to offer, so you could try filing a bug or feature request with NVIDIA for this feature.

These kind of questions also are better suited for Slack or Discourse than for the CUDA.jl issue tracker.
