### ISSUE TITLE
`CUDA.@atomic` deadlocks when overwriting `NaN`

### ISSUE THREAD

**Issue by guyvdbroeck** [JuliaGPU/CUDA.jl#1299]
```julia
f(x,y) = 3x + 2y

function g(x)
    CUDA.@atomic x[1] = f(x[1],42f0) 
    nothing
end

@cuda g(CuArray([0f0])) # works fine
@cuda g(CuArray([NaN32])) # device loops forever (on the second invocation?)
```

I believe this is due to the equality comparison in the generic `atomic_op!` and the fact that `NaN == NaN` is false.

**Comment by maleadt** [comment]
Ah, interesting! Thanks for the fix. Is `===` the best choice here, or should be use `isequal` (which treads NaN/NaN and missing/missing as equal)?
