### ISSUE TITLE
`mul!` is missing for `plan_fft!`

### ISSUE THREAD

**Issue by JeffFessler** [JuliaGPU/CUDA.jl#1311]
**Describe the bug**

`mul!` is not yet implemented for `plan_fft!` (though it is fine for `plan_fft`)

**To reproduce**

The Minimal Working Example (MWE) for this bug:

```julia
using CUDA: cu
using CUDA.CUFFT
using LinearAlgebra: mul!

x = cu(ones(ComplexF32, 8, 9))
p1 = plan_fft(x) # forward plan (non in-place)
y1 = similar(x)
mul!(y1, p1, x) # works fine

p2 = plan_fft!(x) # in-place plan
y2 = copy(x)
mul!(y2, p2, y2) # error: no method
```

<details><summary>Manifest.toml</summary>
<p>

```
Paste your Manifest.toml here, or accurately describe which version of CUDA.jl and its dependencies (GPUArrays.jl, GPUCompiler.jl, LLVM.jl) you are using.
```

The Manifest is irrelevant I think because this is a method issue.  I'm using CUDA `v3.6.3` on linux in julia 1.7.1.

</p>
</details>

**Expected behavior**

I expect the second `mul!` above to produce the same result as the first one does, just like when using FFTW on non-GPU arrrays.
The problem is that the following line is either too restrictive due to the `false` (which restricts it to non-in-place types) or another appropriate method needs to be added:
https://github.com/JuliaGPU/CUDA.jl/blob/9c77666208cf58b2f647ee172de4aff2648af7a9/lib/cufft/fft.jl#L491

If "in place" is impossible to do in CUDA FFT, then perhaps `mul!` should report an error, or at least somewhere this departure from the AbstractFFT API could be documented.  I think it should be possible since `plan_fft!` exists and `y3 = p2 * x` works fine.

**Version info**

Details on Julia:

```
# please post the output of:
versioninfo()
```

Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) Silver 4214 CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, cascadelake)
Environment:
  JULIA_NUM_THREADS = 48

Details on CUDA:

```
# please post the output of:
CUDA.versioninfo()
```

CUDA toolkit 11.5, artifact installation
NVIDIA driver 440.82.0, for CUDA 10.2
CUDA driver 11.4

Libraries: 
- CUBLAS: 11.7.4
- CURAND: 10.2.7
- CUFFT: 10.6.0
- CUSOLVER: 11.3.2
- CUSPARSE: 11.7.0
- CUPTI: 16.0.0
- NVML: 10.0.0+440.82
- CUDNN: 8.30.1 (for CUDA 11.5.0)
- CUTENSOR: 1.3.3 (for CUDA 11.4.0)

Toolchain:
- Julia: 1.7.1
- LLVM: 12.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
- Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80

4 devices:
  0: Quadro RTX 5000 (sm_75, 14.742 GiB / 15.747 GiB available)
  1: Quadro RTX 5000 (sm_75, 15.736 GiB / 15.747 GiB available)
  2: Quadro RTX 5000 (sm_75, 15.736 GiB / 15.747 GiB available)
  3: Quadro RTX 5000 (sm_75, 6.341 GiB / 15.747 GiB available)

**Additional context**

Looks like @maleadt provided the nicely working method at the line number above :)

**Comment by maleadt** [comment]
`mul!` with an in-place plan, but apparently FFTW allows it (detecting misuses at run time by doing a pointer comparison), so I guess we'll allow it...

**Comment by marius311** [comment]
The fix in the linked PR seems to break this case though, was that intentional? 

```julia
using CUDA: cu
using CUDA.CUFFT
using LinearAlgebra: mul!

x = cu(ones(8, 9))
p1 = plan_fft(x)
y1 = similar(p1 * x)
mul!(y1, p1, x) # error

ERROR: MethodError: no method matching mul!(::CUDA.CuArray{ComplexF32, 2, CUDA.Mem.DeviceBuffer}, ::CUDA.CUFFT.cCuFFTPlan{ComplexF32, -1, false, 2}, ::CUDA.CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}, ::Bool, ::Bool)
```

**Comment by maleadt** [comment]
That also fails before that PR. The `mul!(y::DenseCuArray{Ty}, p::CuFFTPlan{T,K,false}, x::DenseCuArray{T})` we used to have cannot match your `(ComplexF32, ComplexF32, Float32)`

**Comment by marius311** [comment]
Ahh sorry typo, that was supposed to be a `plan_rfft` above, not `plan_fft`. The above code with `plan_rfft` seems to fail on 3.7 but works on 3.6.4 at least.

**Comment by maleadt** [comment]
https://github.com/JuliaGPU/CUDA.jl/pull/1341 should fix this

**Comment by JeffFessler** [comment]
Just tested the above in v3.8.0 and they work now - thanks so much!
