### ISSUE TITLE
Syncronization how to?

### ISSUE THREAD

**Issue by Cvikli** [JuliaGPU/CUDA.jl#1324]
Dear CUDA Julianners!

I looked into a lot of resources but I just don't understand what do I do wrong with the syncronization?

The example code I wrote to test:
```
using BenchmarkTools
using CUDA
cudatestSync(c, a, b, X) = begin
	I = ((blockIdx().x - 1) * blockDim().x + threadIdx().x)
	I > size(c,1) * size(c,2) && return
	ca = CUDA.Const(a)
	cb = CUDA.Const(b)
	for i in 1:20
		c[I] += ca[I] + cb[I] 
	end
	sync_threads()
	# CUDA.device_synchronize()
	# sync_threads()
	# device_synchronize()
	if I <= size(c,1) 
		for j in 1:size(c,2)
			X[I] += c[I,j]
		end
	end
	return
end
nth=512	
N = 1000
cf,af,bf=CUDA.randn(Float32, N, N),CUDA.randn(Float32, N, N),CUDA.randn(Float32, N, N)
C,A,B = copy(cf),copy(af),copy(bf); X=CUDA.zeros(Float32,N)
@time CUDA.@sync @cuda threads=nth blocks=cld(N*N, nth) cudatestSync(C,A,B,X)cudatestSync(C,A,B,X))
@show sum(cf .+ 20 .* (af .+ bf) ; dims=2)[1:10]
@show X[1:10]
@assert all(sum(cf .+ 20 .* (af .+ bf) ; dims=2) .≈ X) "sync doesn't WORK!"
```

I tried `@sync`... but that just does something else I guess? 
How to do syncronization?

**Comment by maleadt** [comment]
You synchronize by calling the `synchronize()` function. See the introductory tutorial: https://cuda.juliagpu.org/stable/tutorials/introduction/#Introduction

Also, the bug tracker isn't meant for support questions. Please use Discourse or Slack for that. Thanks!

**Comment by Cvikli** [comment]
Sorry, to reopen it, I tried synchronize but it didn't work for me. (I actually tried discourse, but there were no answer.) 
For me synchronize actually crashes the whole kernel. 
In the introduction synchronize was used outside of the kernel, while I was trying to fuse the kernels and use device_synchronize inside. 

Isn't it possible to use only 1 kernel and run the whole algorithm? If no, may I ask, are you planning to implement it in the future or there is something that blocks it?

**Comment by maleadt** [comment]
> I actually tried discourse, but there were no answer.

I'm watching the gpu category, and did not see a message.

> For me synchronize actually crashes the whole kernel.
> In the introduction synchronize was used outside of the kernel, while I was trying to fuse the kernels and use device_synchronize inside.

Those are two very different calls. Synchronization within the kernel makes threads wait on one another, given that different threads within a bock can execute differently. Synchronization outside of the kernel makes the host wait for the GPU to finish. 

> Isn't it possible to use only 1 kernel and run the whole algorithm? If no, may I ask, are you planning to implement it in the future or there is something that blocks it?

How you implement your algorithm and whether that's possible using a single kernel as opposed to multiple kernels does not depend on any CUDA.jl feature, but on how you implement your kernel. Furthermore, there's no synchronization needed between each kernel, as they are stream ordered.

I have the feeling you're missing some GPU programming experience, so would advise you to read up a little, e.g., the excellent book CUDA By Example. CUDA.jl's kernel programming features are as low-level (in terms of programming abstractions) as CUDA C, so you need to understand how the programming model works and how to write GPU kernels equally well as in CUDA C. Only the array programming interfaces are intended to be used with minimal GPU programming experience.

**Comment by Cvikli** [comment]
Hey, thank you for your answers.

> I'm watching the gpu category, and did not see a message.

I posted it here, but it was with KernelAbstractions, that is why I didn't added gpu category, sorry about that. https://discourse.julialang.org/t/kernelabstractions-nested-task-error-undefvarerror-variable-not-defined/73342

> Those are two very different calls. Synchronization within the kernel makes threads wait on one another, given that different threads within a bock can execute differently. Synchronization outside of the kernel makes the host wait for the GPU to finish.

So I want to do 6-15 aritmetic operation on an array elementwise and then want to do a "mean" on the array. That is why I want the whole array to be synchronized. I need to synchronize every thread. Isn't it possible to do a sync it on the whole array in the kernel? 

> I have the feeling you're missing some GPU programming experience, so would advise you to read up a little, e.g., the excellent book CUDA By Example. CUDA.jl's kernel programming features are as low-level (in terms of programming abstractions) as CUDA C, so you need to understand how the programming model works and how to write GPU kernels equally well as in CUDA C. Only the array programming interfaces are intended to be used with minimal GPU programming experience.

I had courses on the GPU programming but just faced with julia CUDA.jl last year and don't know how to do global synchronization between threads. I just wanted to ask weather there is a way to do it inside a kernel. (I know I could start a kernel and start another kernel, but don't really want to start new and new kernels only to be able to synchronize "outside" if there is an option to synchronize "inside" the kernel. 



I think I want to do this:
A call to ‘threadfence’ will ensure that a write to global memory is visible to all threads on the device.

But not sure how to do it as threadfence() or threadfence_block() for me doesn't synchronize. :(

**Comment by maleadt** [comment]
That's not what `threadfence` is for; it's a barrier, which is very different from synchronization.

> global synchronization between threads

You generally can't do that in CUDA. This is not a restriction of CUDA.jl.

> So I want to do 6-15 aritmetic operation on an array elementwise and then want to do a "mean" on the array.

Just use a separate kernel for the mean. That's how it's supposed to be done. You don't need synchronization between the arithmetic operations and the mean, as kernel launches are stream-ordered.

**Comment by Cvikli** [comment]
> You generally can't do that in CUDA. This is not a restriction of CUDA.jl.

Wow. Thank you! I was scared from that answer. Also read a lot and just saw there are some hacky solution that maybe can do it like that...

So I have to waste resources like that and start new and new kernels, damn. :( 

Thank you for all the answers @maleadt !

**Comment by maleadt** [comment]
> So I have to waste resources like that and start new and new kernels, damn. :(

If your elementwise-kernel takes long enough, the time wasted on the CPU launching the second kernel is going to be overlapping with the first kernel, so there may not be any cost. It is however likely that using two kernels has a cost in terms of temporaries, but implementing `mean` isn't trivial so it's probable that your hand-rolled version would perform worse than our existing kernel anyway.

**Comment by Cvikli** [comment]
Yeah. That could be the way to go I see it too. 

> but implementing mean isn't trivial so it's probable that your hand-rolled version would perform worse than our existing kernel anyway.

You know I actually tested sum function here. [Interesting timing](https://github.com/JuliaGPU/CUDA.jl/issues/1323#issuecomment-1013629616). I was expecting to do the mean with sum/N like a mean(..., dims=2) = sum(..., dims=2) / N ... so I would like to know why is that mysum faster then the builtin. (I would guessed it that mine is optimised on dims=2 and that hardwiring is really great. Or the builtin doesn't use the CUDA.Const, which is actually expectable if there is no custom code.

**Comment by Cvikli** [comment]
Hey @maleadt,
I checked my algorithm and it will have like 1_000_000 kernel launch, which is pretty drastic and really have to figure out weather the kernel fusion possible. I really only need a simple reduce_sum or any kind of simple sum algorithm to be implemented with a sync. 

I just saw you implemented these features:
```
https://docs.juliahub.com/CUDA/oWw5k/1.3.3/autodocs/#CUDA.sync_grid-Tuple{Any}
https://docs.juliahub.com/CUDA/oWw5k/1.3.3/autodocs/#CUDA.this_grid-Tuple{}
added flag: cooperative=true 
```

I tried to use it, but no luck there. 
`ERROR: LoadError: CUDA error: too many blocks in cooperative launch (code 720, ERROR_COOPERATIVE_LAUNCH_TOO_LARGE)`

Can you suggest me an example or point me to a direction on how to use it to implement a reduce_sum?

**Comment by maleadt** [comment]
There's plenty of info on cooperative groups on NVIDIA's devblogs and documentation. I personally don't have experience with it.
And _please_ don't keep using the issue tracker for support questions.
