### ISSUE TITLE
Distributions.jl with CuArrays

### ISSUE THREAD

**Issue by luigifala** [JuliaGPU/CUDA.jl#1347]
I am having problems passing CuArrays to get cumulative distribution functions with package Distributions.jl. 

Is there any built-in function in CUDA allowing to compute Multivariate Normal cdf?

**Comment by maleadt** [comment]
No, that doesn't currently exist.

Please use Slack or Discourse for questions like this, we try to keep the issue tracker for technical issues :slightly_smiling_face:
