### ISSUE TITLE
SpecialFunctions ^1.8 compat entry?

### ISSUE THREAD

**Issue by navidcy** [JuliaGPU/CUDA.jl#1354]
So how come 1.8 is not here?
https://github.com/JuliaGPU/CUDA.jl/blob/d794d26e5c2e4fb5f937335f651e8deadcb7979a/Project.toml#L42
Is this on purpose? Just wondering.

**Comment by maleadt** [comment]
"1.3" implies version 1.3 and higher up to 2.0, so 1.8 is supported:

```
julia> v"1.8" in Pkg.Types.semver_spec("1.3, 2")
true
```

**Comment by navidcy** [comment]
thanks for that ;)
