### ISSUE TITLE
sparseCSC-dense matrix multiplication yields unstable results

### ISSUE THREAD

**Issue by exaexa** [JuliaGPU/CUDA.jl#1368]
**Describe the bug**

In a specific case when multiplying CuSparseMatrixCSC with a dense cuda matrix, it seems there is some kind of a race condition in adding the numbers (← my speculation) and the results vary between the runs. I suppose this is a specific bug with the CSC form, because it doesn't happen e.g. with CuSparseMatrixCSR.

**To reproduce**

The Minimal Working Example (MWE) for this bug:

Setup where I saw the bug:
```julia
julia> typeof(S)
CUDA.CUSPARSE.CuSparseMatrixCSC{Float32, Int32}     #created with cu(sparse(somedata)), roughly 5% non-zeros

julia> typeof(pts)
CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}

julia> size(S), size(pts)
((72, 95), (95, 5000))

julia> X = cu(collect(S));

julia> typeof(X)
CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}
```

The problem:
```julia
julia> sum(S*pts)
0.012372578f0

julia> sum(S*pts)
0.0133146215f0

julia> sum(S*pts)
0.01152225f0

julia> sum(S*pts)
0.012095073f0
```

Actual expected result was `0.013805009f0`, which was perfectly obtainable by converting the matrix to dense on the GPU and multiplying it as such.

`sum` is not to blame -- the actual results differ even in if I retry just `S*pts`, I used `sum` just for brevity.

I will supply code for generating reasonable `S` and `pts` for testing ASAP.

**Expected behavior**

All attempts to compute `sum(S*pts)` return the same number.

**Version info**

CUDA.jl was installed on fresh Julia 1.7 from official repository with `]add CUDA` yesterday. The system is amd64 debian bookworm on intel CPU, updated yesterday (julia is not from APT). GPU is GTX 1650 Ti. CUDA toolkit is version 11.4.3-2, nvidia driver 470.103.01-1, kernel is 5.15.15-2.

I'll supply the versioninfo()s ASAP (not on the same machine now, posting this from a transcript :D ). Also will also ask a colleague to try on his setup.

```
versioninfo() #TODO
CUDA.versioninfo() #TODO
```

**Comment by maleadt** [comment]
I cannot reproduce:

```julia
julia> S = CuSparseMatrixCSC(sprand(Float32, 72, 95, 0.05));

julia> pts = CUDA.rand(Float32, 95, 5000);

julia> sum(S*pts)
436100.72f0

julia> sum(S*pts)
436100.72f0

julia> sum(S*pts)
436100.72f0

julia> sum(S*pts)
436100.72f0

julia> sum(S*pts)
436100.72f0
```

**Comment by exaexa** [comment]
Adding the version info from the colleague (thanks @stelmo! :D )

```
julia> versioninfo()
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, tigerlake)

julia> CUDA.versioninfo()
CUDA toolkit 11.6, artifact installation
NVIDIA driver 461.92.0, for CUDA 11.2
CUDA driver 11.2

Libraries:
- CUBLAS: 11.8.1
- CURAND: 10.2.9
- CUFFT: 10.7.0
- CUSOLVER: 11.3.2
- CUSPARSE: 11.7.1
- CUPTI: 16.0.0
- NVML: 11.0.0+461.92
  Downloaded artifact: CUDNN
- CUDNN: 8.30.2 (for CUDA 11.5.0)
  Downloaded artifact: CUTENSOR
- CUTENSOR: 1.4.0 (for CUDA 11.5.0)

Toolchain:
- Julia: 1.7.2
- LLVM: 12.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
- Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80

1 device:
  0: GeForce RTX 3050 Ti Laptop GPU (sm_86, 3.801 GiB / 4.000 GiB available)
```

a small "working" example that we found:
```
Random.seed!(1)
A=cu(sparse(max.(0,randn(72,95).-1.5)))
B=cu(randn(95,5000))
sum(A*B)
```

Result:
```
julia> sum(A*B)
739.03906f0

julia> sum(A*B)
739.039f0

julia> sum(A*B)
739.03894f0
```

I'll happily provide any further details.

**Comment by maleadt** [comment]
> julia> sum(A*B)
> 739.039f0
> 
> julia> sum(A*B)
> 739.03894f0

That looks well within the margin of acceptable error due to the GPU's nondeterministic execution.

**Comment by exaexa** [comment]
> GPU's nondeterministic execution

this is far beyond the acceptable rounding error for float32.

Maybe we can rephrase as "why would CSC-dense multiplication be nondeterministic if CSR-dense and dense-dense is perfectly deterministic?"

It seems to me much more like an update conflict on adding to accumulators -- the result is always a tiny bit smaller than the expected one (instead of oscillating around, which is what I'd expect with rounding errors).

**Comment by exaexa** [comment]
PS. I'm suspecting this might just as well be a problem in CUSPARSE, is there any easy way to check if CUSPARSE answers that are getting to Julia are right?

**Comment by maleadt** [comment]
> this is far beyond the acceptable rounding error for float32.

```
julia> 739.039f0 ≈ 739.03894f0
true
```

Your original issue looks worse, but I can't reproduce that.



> I'm suspecting this might just as well be a problem in CUSPARSE, is there any easy way to check if CUSPARSE answers that are getting to Julia are right?

For this operation, CUDA.jl only uses CUSPARSE, we don't have native implementations of sparse operations.

**Comment by exaexa** [comment]
> Your original issue looks worse, but I can't reproduce that.

the original data is a stoichiometry and a sample out of metabolic model, the numbers there are supposed to "cancel out" so there's certainly some amplification of the error going on, but I honestly didn't expect it to be _that_ big and one-sided.

> For this operation, CUDA.jl only uses CUSPARSE

Good to know. I guess we can blame this to CUSPARSE behavior. :D I'll try to have a look at whether I can reproduce the same with just CUSPARSE from C++ and let you know, hopefully closing this as upstream problem :]

**Comment by maleadt** [comment]
> Good to know. I guess we can blame this to CUSPARSE behavior. :D I'll try to have a look at whether I can reproduce the same with just CUSPARSE from C++ and let you know, hopefully closing this as upstream problem :]

You can replace the ccalls in `libcusparse.jl` with `@debug_ccall` to see what's being called. Depending on your CUDA version, we probably use `cusparseSpMM`. That call also has an `alg` parameter to select an algorithm, maybe some selection there suits your use case better?

**Comment by exaexa** [comment]
> That call also has an `alg` parameter

Oh nice, place for experimentation. :) Thanks a lot! I'll report back if I find something faulty to blame.

In the meantime, let's just assume this is a CUSPARSE and algorithm choice problem-- I'm closing the issue, will reopen in case I find some simple change that could prevent this imprecision and improve CUDA.jl.
