### ISSUE TITLE
"errormonitor" undefined in julia1.6

### ISSUE THREAD

**Issue by etibarg** [JuliaGPU/CUDA.jl#1375]
### Description
When running the following command: `rgbin_gpu = map(RGB{Float16}, GpuArray(rgbin))`, I came across the following error message:
```
ERROR: LoadError: UndefVarError: errormonitor not defined
Stacktrace:
  [1] pool_mark(dev::CUDA.CuDevice)
    @ CUDA C:\Users\admin\.julia\packages\CUDA\t62lT\src\pool.jl:93
  [2] macro expansion
    @ C:\Users\admin\.julia\packages\CUDA\t62lT\src\pool.jl:187 [inlined]
  [3] macro expansion
    @ .\timing.jl:287 [inlined]
  [4] #_alloc#194
    @ C:\Users\admin\.julia\packages\CUDA\t62lT\src\pool.jl:183 [inlined]
  [5] #alloc#193
    @ C:\Users\admin\.julia\packages\CUDA\t62lT\src\pool.jl:169 [inlined]
  [6] alloc
    @ C:\Users\admin\.julia\packages\CUDA\t62lT\src\pool.jl:165 [inlined]
  [7] CUDA.CuArray{RGB{N0f8}, 2, CUDA.Mem.DeviceBuffer}(#unused#::UndefInitializer, dims::Tuple{Int64, Int64})
    @ CUDA C:\Users\admin\.julia\packages\CUDA\t62lT\src\array.jl:44
  [8] CuArray
    @ C:\Users\admin\.julia\packages\CUDA\t62lT\src\array.jl:287 [inlined]
  [9] CuArray
    @ C:\Users\admin\.julia\packages\CUDA\t62lT\src\array.jl:292 [inlined]
 [10] CuArray
    @ C:\Users\admin\.julia\packages\CUDA\t62lT\src\array.jl:301 [inlined]
```

As per [git blame](https://github.com/JuliaLang/julia/commit/aa4bf234f6e318e4a997a1f4784155f43af4ada4), `errormonitor` has been added in Julia v1.7.

v1.6 is LTS. So, I understand this is either a bug, or a missing condition on Julia (or CUDA.jl?) version.

(of course, my code has *also* a bug I need to fix :)  )

### Some details

Setup:
```
julia> versioninfo()
Julia Version 1.6.5
Commit 9058264a69 (2021-12-19 12:30 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, tigerlake)
Environment:
  JULIA_PKG_DEVDIR = C:/Users/admin/OneDrive - Stratos-Solution/Git
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 8
```

CUDA.jl version:
```
[[CUDA]]
deps = ["AbstractFFTs", "Adapt", "BFloat16s", "CEnum", "CompilerSupportLibraries_jll", "ExprTools", "GPUArrays", "GPUCompiler", "LLVM", "LazyArtifacts", "Libdl", "LinearAlgebra", "Logging", "Printf", "Random", "Random123", "RandomNumbers", "Reexport", "Requires", "SparseArrays", "SpecialFunctions", "TimerOutputs"]
git-tree-sha1 = "200a493fcffb79c1bdb52d92df7a980aebc0b0a6"
uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
version = "3.8.1"
```

**Comment by etibarg** [comment]
Btw, switching back to 3.8.0, I get the following ("expected", shall I say?) error message:
```
ERROR: LoadError:     Can not partition kernel!

    You created a dynamically sized kernel, but forgot to provide runtime
    parameters for the kernel. Either provide them statically if known
    or dynamically.
    NDRange(Static):  KernelAbstractions.NDIteration.DynamicSize
    NDRange(Dynamic): nothing
    Workgroupsize(Static):  KernelAbstractions.NDIteration.DynamicSize
    Workgroupsize(Dynamic): nothing
```

**Comment by prog900** [comment]
got the same error on basic example
```
using CUDA
N = 2^20
x_d = CUDA.fill(1.0f0, N)  # a vector stored on the GPU filled with 1.0 (Float32)
y_d = CUDA.fill(2.0f0, N)  # a vector stored on the GPU filled with 2.0
y_d .+= x_d
@test all(Array(y_d) .== 3.0f0)
```
UndefVarError: errormonitor not defined

Stacktrace:
  [1] pool_mark(dev::CuDevice)
    @ CUDA C:\Users\Evgeny\.julia\packages\CUDA\t62lT\src\pool.jl:93
  [2] macro expansion
    @ C:\Users\Evgeny\.julia\packages\CUDA\t62lT\src\pool.jl:187 [inlined]
  [3] macro expansion
    @ .\timing.jl:287 [inlined]
  [4] #_alloc#194
    @ C:\Users\Evgeny\.julia\packages\CUDA\t62lT\src\pool.jl:183 [inlined]
  [5] #alloc#193
    @ C:\Users\Evgeny\.julia\packages\CUDA\t62lT\src\pool.jl:169 [inlined]
  [6] alloc
    @ C:\Users\Evgeny\.julia\packages\CUDA\t62lT\src\pool.jl:165 [inlined]
  [7] CuArray
    @ C:\Users\Evgeny\.julia\packages\CUDA\t62lT\src\array.jl:44 [inlined]
  [8] CuArray
    @ C:\Users\Evgeny\.julia\packages\CUDA\t62lT\src\array.jl:125 [inlined]
  [9] CuArray
    @ C:\Users\Evgeny\.julia\packages\CUDA\t62lT\src\array.jl:136 [inlined]
 [10] CuArray
    @ C:\Users\Evgeny\.julia\packages\CUDA\t62lT\src\array.jl:138 [inlined]
 [11] fill(v::Float32, dims::Int64)
    @ CUDA C:\Users\Evgeny\.julia\packages\CUDA\t62lT\src\array.jl:555
 [12] top-level scope
    @ In[2]:4
 [13] eval
    @ .\boot.jl:360 [inlined]
 [14] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
    @ Base .\loading.jl:1116

//--------------
CUDA toolkit 11.6, artifact installation
Unknown NVIDIA driver, for CUDA 11.5
CUDA driver 11.5

Libraries: 
- CUBLAS: 11.8.1
- CURAND: 10.2.9
- CUFFT: 10.7.0
- CUSOLVER: 11.3.2
- CUSPARSE: 11.7.1
- CUPTI: 16.0.0
- NVML: missing
- CUDNN: 8.30.2 (for CUDA 11.5.0)
- CUTENSOR: 1.4.0 (for CUDA 11.5.0)

Toolchain:
- Julia: 1.6.4
- LLVM: 11.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
- Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80

1 device:
  0: NVIDIA GeForce GTX 1060 6GB (sm_61, 5.106 GiB / 6.000 GiB available)

os windows 10 x64.  Drivers from official nvidia website - 497.09-desktop-win10-win11-64bit-international-dch-whql

**Comment by vchuravy** [comment]
Can you try #1378? It seems we are missing a test for this.
