### ISSUE TITLE
\ on qr factorization objects gives a method error

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaGPU/CUDA.jl#138]
MWE:

```julia
A = cu(-rand(3,3)); b = cu(rand(3))
_qr = qr(A)
_qr \ A
```

QR factorization already works, and https://github.com/JuliaGPU/CuArrays.jl/pull/165 handled the `\` for Triangular, so all of the pieces are there to define this. In fact,

```julia
_x = vec(UpperTriangular(_qr.R) \ (_qr.Q' * reshape(b,length(b),1)))
```

works, since JuliaGPU/CuArrays.jl#165 requires a matrix, so it's not that far off. Using this a `\` can be defined which would solve https://github.com/JuliaGPU/CuArrays.jl/issues/103

**Comment by maleadt** [comment]
This works now.
