### ISSUE TITLE
Conversion by `cu` casts Float64 to Float32 but not Int64 to Int32

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGPU/CUDA.jl#1388]
Is there any particular reason for downcasting Float64 to Float32 but not Int64 to Int32? Should this be made more consistent? 
```julia
julia> Float64[1, 2] |> cu
2-element CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}:
 1.0
 2.0

julia> Int64[1, 2] |> cu
2-element CuArray{Int64, 1, CUDA.Mem.DeviceBuffer}:
 1
 2
```

Sorry if this has been already asked, it's hard to search for this specific issue.

**Comment by maleadt** [comment]
This is intended. Only Float32 vs Float64 manifests in a great performance difference, so integers are left alone. If your GPU behaves differently, perform the conversion yourself.

Ref https://github.com/JuliaGPU/CuArrays.jl/pull/576
