### ISSUE TITLE
`@cudnnDescriptor` is not threadsafe

### ISSUE THREAD

**Issue by DhairyaLGandhi** [JuliaGPU/CUDA.jl#1421]
**Describe the bug**

There are intermittent failures related to accessing undefined references in the multi GPU training around https://github.com/JuliaGPU/CUDA.jl/blob/e49fb9db46bf788103b0719bcf5df6188024c930/lib/cudnn/descriptors.jl#L31

My understanding is something is getting freed and accessed later (but it happens in the forward pass of the model), so the issue seems to be the threadsafety of `@cudnnDescriptor` since the training runs require several threads to be spun up.

**To reproduce**

Unfortunately, due to the intermittent nature of the issue, it is tough to minimise the code required to run into the bug. To reproduce, one would need to Start Julia with multiple threads, and call into CUDNN until the finaliser cleans up the GPU pointer before the device is done with it. One way to run into it is to train a model from Metalhead with ImageNet - this is nontrivial to set up to test a bug though. I will try to minimise the working example, maybe its sufficient to call into CUDNN often enough with multiple devices. This is the stack trace I see for the error.

```julia
 nested task error: UndefRefError: access to undefined reference
    Stacktrace:
      [1] getindex
        @ ./array.jl:861 [inlined]
      [2] ht_keyindex2!(h::Dict{Tuple, CUDA.CUDNN.cudnnTensorDescriptor}, key::Tuple{CUDA.CUDNN.cudnnTensorFormat_t, CUDA.CUDNN.cu
dnnDataType_t, Int32, Vector{Int32}})
        @ Base ./dict.jl:327
      [3] get!(default::CUDA.CUDNN.var"#1097#1099"{Tuple{CUDA.CUDNN.cudnnTensorFormat_t, CUDA.CUDNN.cudnnDataType_t, Int32, Vector
{Int32}}}, h::Dict{Tuple, CUDA.CUDNN.cudnnTensorDescriptor}, key::Tuple{CUDA.CUDNN.cudnnTensorFormat_t, CUDA.CUDNN.cudnnDataType_t
, Int32, Vector{Int32}})
        @ Base ./dict.jl:459
      [4] CUDA.CUDNN.cudnnTensorDescriptor(::CUDA.CUDNN.cudnnTensorFormat_t, ::Vararg{Any})
        @ CUDA.CUDNN ~/.julia/packages/CUDA/VLpoV/lib/cudnn/descriptors.jl:31
      [5] cudnnBNForward!(y::CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, g::CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, b::CuArray
{Float32, 1, CUDA.Mem.DeviceBuffer}, x::CuArray{Float32, 4, CUDA.Mem.DeviceBuffer}, running_mean::CuArray{Float32, 1, CUDA.Mem.Dev
iceBuffer}, running_var::CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}, momentum::Float32; cache::Nothing, alpha::Int64, beta::Int64,
 eps::Float32, training::Bool)
        @ NNlibCUDA ~/.julia/packages/NNlibCUDA/IeeBk/src/cudnn/batchnorm.jl:47
      [6] #batchnorm#73
        @ ~/.julia/packages/NNlibCUDA/IeeBk/src/cudnn/batchnorm.jl:31 [inlined]
      [7] #adjoint#1
        @ ~/mhead/Flux.jl/src/cuda/cudnn.jl:15 [inlined]
```
<p>
This is happening on both the latest released v3.8.2 and master. 

</p>
</details>

**Expected behavior**

The error only happens intermittently - and in this case it is seen with the forward pass of the Inception model. But this is unrelated to where the error is thrown, specifically because it seems to be related to the codegen for mapping the descriptors to CUDNN.

**Version info**

Details on Julia:

```
# please post the output of:
julia> versioninfo()
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD EPYC 7513 32-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, znver3)
```

Details on CUDA:

```
# please post the output of:
julia> CUDA.versioninfo()
CUDA toolkit 11.6, artifact installation
NVIDIA driver 495.29.5, for CUDA 11.5
CUDA driver 11.5

Libraries:
- CUBLAS: 11.8.1
- CURAND: 10.2.9
- CUFFT: 10.7.0
- CUSOLVER: 11.3.2
- CUSPARSE: 11.7.1
- CUPTI: 16.0.0
- NVML: 11.0.0+495.29.5
- CUDNN: 8.30.2 (for CUDA 11.5.0)
  Downloaded artifact: CUTENSOR
- CUTENSOR: 1.4.0 (for CUDA 11.5.0)

Toolchain:
- Julia: 1.7.1
- LLVM: 12.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
- Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80

4 devices:
  0: Tesla V100-PCIE-32GB (sm_70, 25.720 GiB / 31.749 GiB available)
  1: Tesla V100-PCIE-32GB (sm_70, 30.634 GiB / 31.749 GiB available)
  2: Tesla V100-PCIE-32GB (sm_70, 30.634 GiB / 31.749 GiB available)
  3: Tesla V100-PCIE-32GB (sm_70, 30.634 GiB / 31.749 GiB available)
```

**Additional context**

This requires running with the main branch of https://github.com/DhairyaLGandhi/ResNetImageNet.jl

**Comment by ToucheSir** [comment]
Surprised this hasn't come up earlier! I think the offending line is https://github.com/JuliaGPU/CUDA.jl/blob/e49fb9db46bf788103b0719bcf5df6188024c930/lib/cudnn/descriptors.jl#L29, which instantiates a global, non thread safe Dict for each descriptor type. Similar global caches may be found scattered around the lib/cudnn, see e.g. https://github.com/JuliaGPU/CUDA.jl/blob/master/lib/cudnn/convolution.jl#L172.
