### ISSUE TITLE
cuda with julia 1.8 not working on windows (working fine(?) on wsl2)

### ISSUE THREAD

**Issue by machineko** [JuliaGPU/CUDA.jl#1436]
**Describe the bug**

**To reproduce**

```julia
cu([1]) .+ 2
```

<details><summary>Manifest.toml</summary>
<p>

```
CUDA v3.8.3
```

</p>
</details>

**Expected behavior**

**Version info**

Details on Julia:

```
Julia Version 1.8.0-beta1
Commit 7b711ce699 (2022-02-23 15:09 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 20 × 12th Gen Intel(R) Core(TM) i7-12700K
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, goldmont)
  Threads: 1 on 20 virtual cores
```

Details on CUDA:

```
CUDA v3.8.3
```

nvidia-smi
` NVIDIA-SMI 511.79       Driver Version: 511.79       CUDA Version: 11.6`

**Comment by maleadt** [comment]
You've ignored the bug filing template and not provided crucial information, like what the issue even is or how the backtrace looks. We cannot help you when you do not provide such information.

**Comment by machineko** [comment]
Ahh sorry my bad it was late when i was doing it.
Error message -> `CUDA error: an illegal memory access was encountered (code 700, ERROR_ILLEGAL_ADDRESS)`

**Comment by maleadt** [comment]
Ah, you are using 1.8. There's a known bug, https://github.com/JuliaGPU/GPUCompiler.jl/issues/309, so let's close this in favour of that issue.
