### ISSUE TITLE
Optional CPU cpu kernel call with @cuda 

### ISSUE THREAD

**Issue by Cvikli** [JuliaGPU/CUDA.jl#1443]
Dear CUDA.jl developer,

I would like to ask weather it is possible to implement a method to test the kernel function on CPU. 

Pretty much similar to KernelAbstraction, so you could switch between CPU and nvidia GPU run. 

Something like: 
`@cuda **testonhost=true** threads=nth blocks=blks cudakernelfn(a,b,c)`

`@cuda` is a macro, if the data and the kernel could be replaced a little, it would sound really nice. 
I guess the `I = (blockIdx().x - 1) * blockDim().x + threadIdx().x` in certain scenarios it would be trivial to just replace the run with a 
```
for I in 1:threads*blocks
   cudakernelfn(a,b,c, I)
end
```

Is this something possible? This would be beneficial a lot of time during development and out of bound or just locating special errors in many-many scenario.

**Comment by maleadt** [comment]
Sorry, but this is out of scope of CUDA.jl. Superficially such a mode is like the loop you describe, but to support actual GPU kernels (which use shared memory, PTX intrinsics, etc) *much* more functionality is required. This used to be supported via GPUOcelot, but that project died.

As an alternative, write your kernels in a dialect that _can_ be lowered to something for the CPU, i.e., KernelAbstractions or GPUArray or Tullio or ... But CPU execution of actual CUDA.jl kernels is not going to happen.
