### ISSUE TITLE
Add library/artifact management for NCCL

### ISSUE THREAD

**Issue by ToucheSir** [JuliaGPU/CUDA.jl#1446]
**Is your feature request related to a problem? Please describe.**

I noticed https://github.com/JuliaPackaging/Yggdrasil/pull/3073 was merged a while back, so in theory there are now NCCL artifacts. What would be required to integrate NCCL to the point where one can start calling wrapped functions? 

**Describe the solution you'd like**

As a first step, it would be nice to get all the prerequisites in line for running https://github.com/JuliaGPU/CUDA.jl/tree/master/res/wrap.
Getting the wrapped functions themselves would be a bonus.

**Describe alternatives you've considered**

N/A

**Additional context**

I wouldn't know where to begin with doing this, unfortunately.

**Comment by vchuravy** [comment]
There is https://github.com/JuliaGPU/NCCL.jl

**Comment by ToucheSir** [comment]
Is there a guide of how to make an external library like that work with the CUDA artifact system? The whole lazy artifacts and library discovery part is quite confusing to me.

**Comment by maleadt** [comment]
There isn't. The hope is that CUDA.jl's artifact management will be superseded by regular JLLs, but they aren't flexible enough yet. So the interim solution would be to package NCCL in a JLL, add it to CUDA.jl's binary artifact management, exposing a simple `nccl()` function, and have NCCL.jl use that.

**Comment by ToucheSir** [comment]
Thanks both, I've updated the title to reflect that step. My understanding is that the first step is already done because https://github.com/JuliaBinaryWrappers/NCCL_jll.jl exists, but how might one go about this?
> add it to CUDA.jl's binary artifact management, exposing a simple `nccl()` function

**Comment by maleadt** [comment]
I'll first update the JLL and include it here then.
