### ISSUE TITLE
CUSPARSE: Diagonal + CSC/CSR gives dense array

### ISSUE THREAD

**Issue by Roger-luo** [JuliaGPU/CUDA.jl#1469]
I'm not sure if this is a bug or enhancement, but I think this should be a bug... so currently if you add a sparse matrix with a diagonal the broadcast will think their result is dense. e.g

<details>

```julia
julia> sprand(10, 10, 0.1) + Diagonal(rand(10))
10×10 SparseMatrixCSC{Float64, Int64} with 17 stored entries:
 0.231037   ⋅        …   ⋅         ⋅ 
 0.172736  0.362504      ⋅         ⋅ 
  ⋅         ⋅            ⋅         ⋅ 
  ⋅         ⋅           0.400551   ⋅ 
  ⋅         ⋅           0.13433    ⋅ 
  ⋅         ⋅        …   ⋅         ⋅ 
  ⋅         ⋅            ⋅         ⋅ 
  ⋅         ⋅            ⋅         ⋅ 
  ⋅         ⋅           0.362257   ⋅ 
  ⋅         ⋅            ⋅        0.545874

julia> cu(sprand(10, 10, 0.1)) + cu(Diagonal(rand(10)))
10×10 CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}:
 0.948874  0.0       …  0.0      0.0
 0.0       0.149517     0.0      0.0
 0.0       0.0          0.0      0.0
 0.0       0.0          0.0      0.0
 0.0       0.0          0.0      0.0
 0.0       0.0       …  0.0      0.146771
 0.0       0.0          0.0      0.0
 0.0       0.0          0.0      0.0
 0.486828  0.0          1.58939  0.468612
 0.0       0.0          0.0      0.832776
```

</details>

I guess this might due to some misconfig of the broadcast implementation on inferring the sparse structure. In `SparseArrays`, it seems to be handled by a specific broadcast style at this line
https://github.com/JuliaSparse/SparseArrays.jl/blob/main/src/higherorderfns.jl#L78

I'm not sure what would be the right way to do it with `CuSparseMatrix` types however

**Comment by maleadt** [comment]
> I'm not sure what would be the right way to do it with `CuSparseMatrix` types however

I think by selecting a compatible broadcast style: https://github.com/JuliaGPU/CUDA.jl/blob/778f7fa21f3f73841a2dada57767e358f80e5997/lib/cusparse/broadcast.jl#L29-L31=

**Comment by maleadt** [comment]
Works for me:

```
julia> CUDA.allowscalar(false)

julia> cu(sprand(10, 10, 0.1)) + cu(Diagonal(rand(10)))
10×10 CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}:
 0.372961  0.0       0.0       0.0       0.0       0.0         0.0       0.0       0.0       0.0
 0.52647   0.928075  0.0       0.0       0.0       0.00939758  0.0       0.0       0.0       0.0
 0.0       0.0       0.716248  0.0       0.0       0.0         0.0       0.422652  0.0       0.0
 0.0       0.0       0.0       0.22815   0.0       0.0         0.0       0.0       0.0       0.0
 0.0       0.0       0.0       0.0       0.366832  0.0         0.0       0.0       0.0       0.0
 0.0       0.0       0.467712  0.0       0.0       0.316855    0.0       0.0       0.0       0.0
 0.0       0.0       0.0       0.0       0.0       0.0         0.731482  0.0       0.0       0.0
 0.0       0.0       0.0       0.0       0.0       0.0         0.0       0.675298  0.0       0.0
 0.0       0.0       0.0       0.034966  0.674623  0.0         0.0       0.0       0.915939  0.0
 0.0       0.0       0.0       0.0       0.345603  0.293177    0.53271   0.0       0.0       0.978598
```

**Comment by maleadt** [comment]
Ah no, sorry, misinterpreted the issue.

**Comment by maleadt** [comment]
We currently don't have the same automatic promotion to sparse inputs as Base have, so we special case e.g. the addition with UniformScaling: https://github.com/JuliaGPU/CUDA.jl/blob/6b6aa9ad7edce9b7436e76554830fd37d972c7dc/lib/cusparse/interfaces.jl#L184-L212=. Either this use with Diagonal requires a similar special case, or we need to add some promotion-to-sparse machinery as well. The sparse broadcast implementation should properly handle multiple sparse inputs.
