### ISSUE TITLE
mul! falls back to generic implementation

### ISSUE THREAD

**Issue by rveltz** [JuliaGPU/CUDA.jl#148]
**Describe the bug**
Calling `mul!` falls back to generic implementation unlike calling `rmul!`

**To Reproduce**
The Minimal Working Example (MWE) for this bug:
```julia
using CuArrays, LinearAlgebra
CuArrays.allowscalar(false)
rhs = rand(1000000)
rhs_d = cu(rhs)
#this works:
rmul!(rhs_d,1.0)

#this fails:
mul!(rhs_d,rhs_d,1.0)
```

**Environment details (please complete this section)**
Details on Julia:
```
# please post the output of:
versioninfo()
```
julia> versioninfo()
Julia Version 1.0.3
Commit 099e826241* (2018-12-18 01:34 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Xeon(R) CPU E5-2637 v4 @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
```

**Comment by maleadt** [comment]
This works now.
