### ISSUE TITLE
Errors when broadcasting random number generators

### ISSUE THREAD

**Issue by Tuebel** [JuliaGPU/CUDA.jl#1480]
Thanks for this great library, I really love, how most of it is just Julia!

I am trying to create random numbers for arrays distributions on the GPU and the nicest way I have found to do this is using broadcasting. This allows me to use the same distribution on the CPU as well as the GPU.

```julia
using CUDA, Random
struct MyExponential{T<:Real}
    λ::T
end
Base.rand(rng::AbstractRNG, d::MyExponential{T}) where T = -log(rand(rng, T)) / d.λ


D = [MyExponential(Float32(i)) for i in 1:3] |> CuArray
A = CuArray{Float32}(undef,3,2)
A .= rand.((Random.GLOBAL_RNG,), D)
```

In case of the `GLOBAL_RNG` it works fine. Different RNGs give me different Errors:

```julia
A .= rand.((Random.default_rng(),), D)

ERROR: InvalidIRError: compiling kernel broadcast_kernel(CUDA.CuKernelContext, CuDeviceMatrix{Float32, 1}, Base.Broadcast.Broadcasted{CUDA.CuArrayStyle{2}, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}, typeof(rand), Tuple{Tuple{TaskLocalRNG}, Base.Broadcast.Extruded{CuDeviceVector{MyExponential{Float32}, 1}, Tuple{Bool}, Tuple{Int64}}}}, Int64) resulted in invalid LLVM IR
Reason: unsupported call to an unknown function (call to julia.get_pgcstack)
Stacktrace:
 [1] _broadcast_getindex_evalf
   @ ./broadcast.jl:670
 [2] _broadcast_getindex
   @ ./broadcast.jl:643
 [3] getindex
   @ ./broadcast.jl:597
 [4] broadcast_kernel
   @ ~/.julia/packages/GPUArrays/Zecv7/src/host/broadcast.jl:67
```

```julia
A .= rand.((CUDA.default_rng(),), D)

ERROR: GPU compilation of kernel broadcast_kernel(CUDA.CuKernelContext, CuDeviceMatrix{Float32, 1}, Base.Broadcast.Broadcasted{CUDA.CuArrayStyle{2}, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}, typeof(rand), Tuple{Tuple{CUDA.RNG}, Base.Broadcast.Extruded{CuDeviceVector{MyExponential{Float32}, 1}, Tuple{Bool}, Tuple{Int64}}}}, Int64) failed
KernelError: passing and using non-bitstype argument

Argument 4 to your kernel function is of type Base.Broadcast.Broadcasted{CUDA.CuArrayStyle{2}, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}, typeof(rand), Tuple{Tuple{CUDA.RNG}, Base.Broadcast.Extruded{CuDeviceVector{MyExponential{Float32}, 1}, Tuple{Bool}, Tuple{Int64}}}}, which is not isbits:
  .args is of type Tuple{Tuple{CUDA.RNG}, Base.Broadcast.Extruded{CuDeviceVector{MyExponential{Float32}, 1}, Tuple{Bool}, Tuple{Int64}}} which is not isbits.
    .1 is of type Tuple{CUDA.RNG} which is not isbits.
      .1 is of type CUDA.RNG which is not isbits.
```

**Expected behavior**
I would have expected the latter examples to work like the one using GLOBAL_RNG.
This issue is not too critical, since I am able to work around it, by generating random primitives beforehand and transforming them later:

```julia
transform_rand(d::MyExponential, x) = -log(x) / d.λ
rand!(Random.default_rng(), A)
A .= transform_rand.(D, A)
```
It is only a bit tedious for mixtures of distributions, since I need to generate multiple arrays of random numbers beforehand (e.g. using `randn` instead of `rand` for normal distributions). 

**Version info**

Details on Julia:

```
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
```

Details on CUDA: CUDA.jl v3.9.0.

```
CUDA toolkit 11.6, artifact installation
NVIDIA driver 510.54.0, for CUDA 11.6
CUDA driver 11.6

Libraries: 
- CUBLAS: 11.8.1
- CURAND: 10.2.9
- CUFFT: 10.7.0
- CUSOLVER: 11.3.2
- CUSPARSE: 11.7.1
- CUPTI: 16.0.0
- NVML: 11.0.0+510.54
  Downloaded artifact: CUDNN
- CUDNN: 8.30.2 (for CUDA 11.5.0)
  Downloaded artifact: CUTENSOR
- CUTENSOR: 1.4.0 (for CUDA 11.5.0)

Toolchain:
- Julia: 1.7.2
- LLVM: 12.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
- Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80

1 device:
  0: NVIDIA GeForce 940MX (sm_50, 1.904 GiB / 2.000 GiB available)
```

**Comment by vchuravy** [comment]
The issue is the separation of "device code" and "host code".  `CUDA.default_rng()` is the default rng for host side random number generation.

What I expected to have  worked is:

```
A .= rand.((Random.default_rng(),), D)
```
due to: https://github.com/JuliaGPU/CUDA.jl/blob/778f7fa21f3f73841a2dada57767e358f80e5997/src/device/random.jl#L95

but the issue is that we first create a tuple with `(Random.default_rng(),)` and then create a broadcast kernel, and the tuple is evaluated on the host.

```
julia> Meta.@lower A .= rand.((Random.default_rng(),), D)
:($(Expr(:thunk, CodeInfo(
    @ none within `top-level scope`
1 ─ %1 = Base.getproperty(Random, :default_rng)
│   %2 = (%1)()
│   %3 = Core.tuple(%2)
│   %4 = Base.broadcasted(rand, %3, D)
│   %5 = Base.materialize!(A, %4)
└──      return %5
))))
```

So I would expect:
```
 A .= ((d)->rand(Random.default_rng(), d)).(D)
```

to work.

**Comment by Tuebel** [comment]
Thanks for your quick reply, I would not have thought about the tuple wrapper beeing the issue. Using the anonymous function does work, indeed! But it does only work as long as `Random.default_rng()` is inside the broadcasted expression and replaced by `Philox2x32` on the device.

Providing an existing RNG still fails:
```julia
rng = Random.default_rng()
A .= ((d)->rand(rng, d)).(D)

ERROR: AssertionError: llvmtype(state_arg) == T_state
```
Digging deeper into the code, I realized, that only `Philox2x32`  is intended on-device random numbers. Other RNGs are executed on the CPU and copy the whole array to the GPU:
https://github.com/JuliaGPU/GPUArrays.jl/blob/7b65e1a13c8545e80f0191201804842be67b868c/src/host/random.jl#L113-L115

Here is what I ended up doing, in case anyone else has a similar issue. As I would like to use an existing seeded RNG I replicated the implementation of the rand kernel for a `CUDA.RNG`: 
https://github.com/JuliaGPU/CUDA.jl/blob/778f7fa21f3f73841a2dada57767e358f80e5997/src/random.jl#L38-L42

- `device_rng` is part of the kernel and `Random.default_rng()` gets converted, as you have stated.
- `barrier_rand!` is a function barrier and required, since `CUDA.RNG` is not isbits.
- `rand!` is pretty much the same as linked above, except no custom kernel is launched and I depend on broadcasting to get the job done.
```julia
using CUDA, Random
struct MyExponential{T<:Real}
    λ::T
end
Base.rand(rng::AbstractRNG, d::MyExponential{T}) where T = -log(rand(rng, T)) / d.λ

function device_rng(seed, counter)
    rng = Random.default_rng()
    @inbounds Random.seed!(rng, seed, counter)
    rng
end

function barrier_rand!(D, A, seed, counter)
    A .= (x -> rand(device_rng(seed, counter), x)).(D)
end

function Random.rand!(rng::CUDA.RNG, D::AbstractArray{<:MyExponential}, A)
    barrier_rand!(D, A, rng.seed, rng.counter)
    new_counter = Int64(rng.counter) + length(A)
    overflow, remainder = fldmod(new_counter, typemax(UInt32))
    rng.seed += overflow
    rng.counter = remainder
    return A
end

D = [MyExponential(Float32(i)) for i in 1:3] |> CuArray
A = CuArray{Float32}(undef,3,2)
rng = CUDA.RNG(1)
rand!(rng, D, A)
```
And the output is always the same for the same seed.
```
3×2 CuArray{Float32, 2, CUDA.Mem.DeviceBuffer}:
 1.59776  0.748921
 0.89599  0.827431
 1.12853  0.296111
```
