### ISSUE TITLE
CUBLAS: Multiplication of `UpperTriangular`/`LowerTriangular` not supported

### ISSUE THREAD

**Issue by Red-Portal** [JuliaGPU/CUDA.jl#1486]
**Describe the bug**

Matrix multiplications with `UpperTriangular` and `LowerTriangular` are outrageously slow.

```julia
using CUDA
using BenchmarkTools

julia> @benchmark U*U setup=(U=triu(CUDA.randn(1024, 1024)))
BenchmarkTools.Trial: 581 samples with 6 evaluations.
 Range (min … max):  5.993 μs … 148.436 ms  ┊ GC (min … max): 0.00% … 0.22%
 Time  (median):     6.445 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   1.026 ms ±  12.242 ms  ┊ GC (mean ± σ):  0.21% ± 0.02%

  █▇▄▆▂                                                        
  █████▄▆▅▄██▇██▁▅▄▆▆▇▆▇▇▁▆▆▆▄▄▅▅▆▁▆▅▄▁▆▆▄▄▁▄▄▁▄▁▁▁▁▁▁▁▁▄▄▁▁▄ ▇
  5.99 μs      Histogram: log(frequency) by time      22.4 μs <

 Memory estimate: 640 bytes, allocs estimate: 32.
```

```julia
julia> @benchmark U*U setup=(U=UpperTriangular(CUDA.randn(1024, 1024)))
BenchmarkTools.Trial: 2259 samples with 1 evaluation.
 Range (min … max):  26.422 μs … 135.895 ms  ┊ GC (min … max): 0.00% … 1.08%
 Time  (median):      1.942 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):    2.104 ms ±   5.660 ms  ┊ GC (mean ± σ):  0.12% ± 0.05%

  ▆                               █▅ ▅ ▂▅     ▁▂ ▂▂         ▃▁ ▁
  █▅▁▁▁▃▁▃▁▁▁▁▁▁▁▁▁▁▃▁▁▁▁▁▁▁▁▁▁▁▃▇██▇████▅▁▃▇▆██▆██▆▆▆▅▆▆▄▆███ █
  26.4 μs       Histogram: log(frequency) by time      3.51 ms <

 Memory estimate: 720 bytes, allocs estimate: 15.
```

```julia
julia> @benchmark U*U' setup=(U=UpperTriangular(CUDA.randn(1024, 1024)))
┌ Warning: Performing scalar indexing on task Task (runnable) @0x00007f5d2af14010.
│ Invocation of getindex resulted in scalar indexing of a GPU array.
│ This is typically caused by calling an iterating implementation of a method.
│ Such implementations *do not* execute on the GPU, but very slowly on the CPU,
│ and therefore are only permitted from the REPL for prototyping purposes.
│ If you did intend to index this array, annotate the caller with @allowscalar.
└ @ GPUArrays ~/.julia/packages/GPUArrays/Zecv7/src/host/indexing.jl:56
BenchmarkTools.Trial: 1 sample with 1 evaluation.
 Single result which took 16.270 s (0.41% GC) to evaluate,
 with a memory estimate of 966.18 MiB, over 6397082 allocations.
```

```julia
julia> @benchmark U'*U setup=(U=UpperTriangular(CUDA.randn(1024, 1024)))
BenchmarkTools.Trial: 2235 samples with 1 evaluation.
 Range (min … max):  27.548 μs … 150.721 ms  ┊ GC (min … max): 0.00% … 1.48%
 Time  (median):      1.925 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):    2.127 ms ±   5.825 ms  ┊ GC (mean ± σ):  0.15% ± 0.05%

  ▆                               ▃█ ▂▄▄▃▄▄▂▁  ▁▂▃▃▁   ▁▂▂     ▁
  █▆▁▄▁▁▁▁▁▁▁▁▃▃▁▁▁▁▁▃▁▁▁▁▁▁▁▁▁▁▁▃██▆████████▇██████▆▆▃████▆▆▆ █
  27.5 μs       Histogram: log(frequency) by time      3.42 ms <

 Memory estimate: 704 bytes, allocs estimate: 14.
```

```julia
julia> @benchmark U'*U' setup=(U=UpperTriangular(CUDA.randn(1024, 1024)))

BenchmarkTools.Trial: 1 sample with 1 evaluation.
 Single result which took 18.099 s (0.41% GC) to evaluate,
 with a memory estimate of 966.48 MiB, over 6402181 allocations.
```

* `U*U` is slow but works
* `U*L` is outrageous
* `L*U` is slow but works
* `L*L` is outrageous 
In general, using `UpperTriangular` and `LowerTriangular` for matrix multiplications is terribly slow. 
A quick workaround is to use `triu`, `tril` and then put the result back in the adaptors.

```
@v1.7) pkg> status
      Status `~/.julia/environments/v1.7/Project.toml`
  [6e4b80f9] BenchmarkTools v1.3.1
  [052768ef] CUDA v3.9.0
```

</p>
</details>

**Version info**

```
julia> versioninfo()
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 8
```
```
julia> CUDA.versioninfo()
CUDA toolkit 11.6, artifact installation
NVIDIA driver 510.60.2, for CUDA 11.6
CUDA driver 11.6

Libraries: 
- CUBLAS: 11.8.1
- CURAND: 10.2.9
- CUFFT: 10.7.0
- CUSOLVER: 11.3.2
- CUSPARSE: 11.7.1
- CUPTI: 16.0.0
- NVML: 11.0.0+510.60.2
- CUDNN: missing
```

**Comment by kshyatt** [comment]
It looks like the `U*U'` and `U'*U` are falling back to scalar indexing which explains the slowdown. I don't think CUBLAS has a built-in method for these kinds of multiplications, you might be better served by writing a method that dispatches to GEMM.

**Comment by Red-Portal** [comment]
Hi @kshyatt , I'm unsure what would be a good direction to handle this issue though. Do you think we should leave this as is and let the users handle it on their own, or should we add a specialization that falls back to `GEMM`?

**Comment by kshyatt** [comment]
I think adding a signature for `mul!(A::Transpose{UpperTriangular{CuMatrix}}, B::UpperTriangular{CuMatrix})` might be nice, if you had turned off scalar indexing support this would've errored. @maleadt any thoughts?

**Comment by maleadt** [comment]
Yeah this isn't a bug, but just a missing specialization. You should always disable scalar iteration, as the warning is pretty clear about.

I'm not sure it's worth adding a specialization to CUDA.jl though. Is this a common operation, and/or does Base have specific specializations?

**Comment by Red-Portal** [comment]
Hi @maleadt , I do think the missing specialization should be thought of as a performance bug though. Multiplication between triangular matrices is all over the derivatives of linear systems. So If we would like to differentiate efficiently through stuff like `cholesky` , we need to do something about the triangular matrices.

**Comment by maleadt** [comment]
I don't consider it a bug because there's always functionality that should be specialized for the GPU, and it depends on people having a need for that functionality and implementing it. So you could add such a method to CUDA.jl (probably in https://github.com/JuliaGPU/CUDA.jl/blob/master/lib/cublas/linalg.jl), based on the signature @kshyatt mentioned above, using functionality from CUBLAS (or just by using Julia's `mul!` on plain CuArrays which will take care of the dispatch to CUBLAS for you).
