### ISSUE TITLE
ResNet spending much time in CuArrays GC

### ISSUE THREAD

**Issue by KristofferC** [JuliaGPU/CUDA.jl#149]
I was profiling why a resnet model (https://github.com/KristofferC/resnet) was running extremely slow on Flux.

Sprinkling some sections using https://github.com/KristofferC/TimerOutputs.jl and training the model a little bit I got:

(edit: the timings below are stale due to changes in CuArrays, see https://github.com/JuliaGPU/CuArrays.jl/issues/273#issuecomment-461943376 for an update)

```
 ───────────────────────────────────────────────────────────────────────
                                Time                   Allocations
                        ──────────────────────   ───────────────────────
    Tot / % measured:        82.6s / 62.9%           9.09GiB / 3.32%

 Section        ncalls     time   %tot     avg     alloc   %tot      avg
 ───────────────────────────────────────────────────────────────────────
 gc true           468    47.8s  92.1%   102ms   4.88MiB  1.58%  10.7KiB
 crossentropy       32    1.91s  3.69%  59.8ms    159MiB  51.5%  4.98MiB
 conv            1.70k    1.61s  3.10%   948μs   85.6MiB  27.7%  51.7KiB
 dense              32    488ms  0.94%  15.2ms   59.1MiB  19.1%  1.85MiB
 gc false           32   81.0ms  0.16%  2.53ms    645KiB  0.20%  20.2KiB
 ───────────────────────────────────────────────────────────────────────
```

The `gc true` section refers to only this line:

https://github.com/JuliaGPU/CuArrays.jl/blob/61e25a2d239da77a5e8f3dc9746f9f62cd9e1380/src/memory.jl#L256

It seems this line is being called too often compared to how expensive a `gc(true)` call is.

**Comment by maleadt** [comment]
> Since the GC pressure from the cuda arrays is low, we will always end up in this situation (GPU memory being full) sooner or later?

Yes, and extending the main GC to keep track of additional memory pressure and/or separate object pools doesn't seem like it'll be happening. Maybe we could maintain our own pressure metric and occasionally call out to the GC during `alloc`, but that'd still be costly since it would be processing Julia objects too. So I'm hoping some careful memory management a la JuliaGPU/CuArrays.jl#270 will suffice.

**Comment by maleadt** [comment]
Let's close this, see https://github.com/JuliaGPU/CUDA.jl/issues/137#issuecomment-788867996. Please open new issues with updated MWEs if the issue persists.
