### ISSUE TITLE
CUTENSOR tests consume lots of memory, breaking other tests

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CUDA.jl#1501]
The CUTENSOR contraction tests consume _a lot_ of memory, and since we run two workers per GPU they tend to break other tests, ironically most of the time other CUTENSOR tests. For example, the `elementwise_trinary` tests fails when it's run together with the memory-intensive `contractions` test suite:

```
cutensor/elementwise_trinary                  (3) |         failed at 2022-05-09T08:36:27.381
cutensor/contractions                         (2) |    96.64 |   2.09 |  2.2 |   35492.05 |  4763.00 |   5.49 |  5.7 |    9436.69 | 11785.60 |
```

If they're scheduled differently, both pass:

```
cutensor/contractions                         (3) |    99.78 |   2.66 |  2.7 |   35492.05 |  4427.00 |   6.82 |  6.8 |    9497.41 | 11016.96 |
cutensor/elementwise_trinary                  (2) |    49.38 |   0.00 |  0.0 |      24.44 |   405.00 |   1.55 |  3.1 |    5175.42 | 14292.72 |
```

@kshyatt Since you wrote those tests, could you have a look at making `cutensor/contractions` consume less memory? If that's impossible, we should make sure we run those tests when no other test is active.

**Comment by kshyatt** [comment]
Yes, I'll take a look!

**Comment by maleadt** [comment]
Any update?

**Comment by kshyatt** [comment]
Sorry, I've been swamped by work and JuliaCon stuff. Let me set some time aside for this.B
