### ISSUE TITLE
Inconsistency of `==` and `isequal` for `CuArray`

### ISSUE THREAD

**Issue by JeffFessler** [JuliaGPU/CUDA.jl#1524]
**Describe the bug**

Inconsistent behavior between `==` and `isequal` for `CuArray`

**To reproduce**

The Minimal Working Example (MWE) for this bug:

```julia
using CUDA: CuArray
import CUDA

CUDA.allowscalar(false)

x = ones(2,3)
y = ones(6)
xc = CuArray(x)
yc = CuArray(y)
@assert !isequal(x, y)
@assert x !== y
@assert !isequal(xc, yc)
@assert xc == yc # huh?
```

<details><summary>Manifest.toml</summary>
<p>

CUDA v3.10.0
Julia 1.7.1

```
Paste your Manifest.toml here, or accurately describe which version of CUDA.jl and its dependencies (GPUArrays.jl, GPUCompiler.jl, LLVM.jl) you are using.
```

</p>
</details>

**Expected behavior**

I expect two arrays of different _dimensions_ to fail both `isequal` and `==`.
Regular arrays have that property, so should `CuArray`s, right?

**Version info**

Details on Julia:

```
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) Silver 4214 CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, cascadelake)
Environment:
  JULIA_NUM_THREADS = 48

```

Details on CUDA:

```
CUDA toolkit 11.7, artifact installation
NVIDIA driver 510.73.5, for CUDA 11.6
CUDA driver 11.7

Libraries: 
- CUBLAS: 11.10.1
- CURAND: 10.2.10
- CUFFT: 10.7.2
- CUSOLVER: 11.3.5
- CUSPARSE: 11.7.3
- CUPTI: 17.0.0
- NVML: 11.0.0+510.73.5
- CUDNN: 8.30.2 (for CUDA 11.5.0)
- CUTENSOR: 1.4.0 (for CUDA 11.5.0)

Toolchain:
- Julia: 1.7.1
- LLVM: 12.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
- Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80

4 devices:
  0: Quadro RTX 5000 (sm_75, 12.149 GiB / 16.000 GiB available)
  1: Quadro RTX 5000 (sm_75, 15.745 GiB / 16.000 GiB available)
  2: Quadro RTX 5000 (sm_75, 15.745 GiB / 16.000 GiB available)
  3: Quadro RTX 5000 (sm_75, 15.745 GiB / 16.000 GiB available)

```

**Additional context**

I am writing unit tests for another package to make it CUDA compatible
 https://github.com/JeffFessler/LinearMapsAA.jl/issues/43

**Comment by JeffFessler** [comment]
Possibly related to this comment in the code:
https://github.com/JuliaGPU/CUDA.jl/blob/2656e15a9dc286698245daabbe37d46778555e9e/lib/cudadrv/context.jl#L137

**Comment by maleadt** [comment]
That's comparison on contexts, unrelated to arrays.

**Comment by JeffFessler** [comment]
I just realized I can use `@which` to help determine the source of the difference.
`isequal` for two `CuArray`s reverts to the usual `isequal` for AbstractArrays in Base, which does an axes check as expected:
https://github.com/JuliaLang/julia/blob/742b9abb4dd4621b667ec5bb3434b8b3602f96fd/base/abstractarray.jl#L2525

But `==` for two `CuArray`s  is calling a method in `GPUArrays` that uses `mapreduce` with no axes check:
https://github.com/JuliaGPU/GPUArrays.jl/blob/fc0d327ecc2fd0b3b73427cf6f491591aa096b75/src/host/mapreduce.jl#L88

So this issue really belongs with `GPUArrays` and is related to https://github.com/JuliaGPU/GPUArrays.jl/pull/405.

After reading the manual more closely, I learned that `==` and `isequal` differ for arrays that have `missing` elements.  https://docs.julialang.org/en/v1/base/math/#Base.:==
