### ISSUE TITLE
The GPU compiler fails on a call to `maximum`

### ISSUE THREAD

**Issue by jonathan-laurent** [JuliaGPU/CUDA.jl#1548]
The GPU compiler fails on this code:

```julia
using CUDA
using JET

struct Node
    x::Int
end

function test(::Type{Arr}) where {Arr}
    tree = Arr([Node(0) for i in 1:2])
    indices = Arr(1:2)
    return map(indices) do i
        node = tree[i]
        return maximum(1:2) do j
            x = node.x  # Dead code but necessary to replicate
            return j > 1 ? 1 : 0
        end
    end
end

JET.@test_opt test(Array)  # No dynamic dispatch detected

test(Array)    # OK
test(CuArray)  # Fails with error below
```
#### Notes

- Note that the failure does not happen anymore when replacing `maximum` by `sum` or `argmax`.
- A possible fix is to add `init=0` as an argument to `maximum`. However, this should not be necessary (and it is not necessary for `argmax` despite the latter also failing on empty collections).

#### Error

```txt
ERROR: InvalidIRError: compiling kernel #broadcast_kernel#17(CUDA.CuKernelContext, CuDeviceVector{Int64, 1}, Base.Broadcast.Broadcasted{CUDA.CuArrayStyle{1}, Tuple{Base.OneTo{Int64}}, var"#150#153"{CuDeviceVector{Node, 1}}, Tuple{Base.Broadcast.Extruded{CuDeviceVector{Int64, 1}, Tuple{Bool}, Tuple{Int64}}}}, Int64) resulted in invalid LLVM IR
Reason: unsupported dynamic function invocation (call to mapreduce_empty_iter(f, op, itr, ItrEltype) in Base at reduce.jl:353)
Stacktrace:
  [1] _mapreduce
    @ ./reduce.jl:402
  [2] _mapreduce_dim
    @ ./reducedim.jl:330
  [3] #mapreduce#731
    @ ./reducedim.jl:322
  [4] mapreduce
    @ ./reducedim.jl:322
  [5] #_maximum#749
    @ ./reducedim.jl:894
  [6] _maximum
    @ ./reducedim.jl:894
  [7] #maximum#747
    @ ./reducedim.jl:890
  [8] maximum
    @ ./reducedim.jl:890
  [9] #150
    @ ~/AlphaZero.jl/redesign/private/gpu_compiler.jl:15
 [10] _broadcast_getindex_evalf
    @ ./broadcast.jl:670
 [11] _broadcast_getindex
    @ ./broadcast.jl:643
 [12] getindex
    @ ./broadcast.jl:597
 [13] broadcast_kernel
    @ ~/.julia/packages/GPUArrays/Zecv7/src/host/broadcast.jl:67
Hint: catch this exception as `err` and call `code_typed(err; interactive = true)` to introspect the erronous code
```

#### Config

I am using Julia 1.7.3 and CUDA 3.11.0.

**Comment by jonathan-laurent** [comment]
**Update:** similar problems can happen with `sum` and `argmax`, although not in this particular case. In general, there seems to be a problem with compiling `mapreduce` derivatives on GPU as the GPU compiler sometimes cannot handle the case where the collection is empty and an exception must be raised.

The reason the problem is hard to replicate may be that it is sometimes *inlined away* when using simple functions.

Still, I would argue that functions such as `sum`, `argmax` and `maximum` should be working on GPU without `init` being specified (`init` isn't even available for `argmax`). It remains to be determined whether the problem lies with their implementation in Base or with the GPU compiler.

**Comment by maleadt** [comment]
> [1] _mapreduce
>     @ ./reduce.jl:402
>   [2] _mapreduce_dim
>     @ ./reducedim.jl:330
>   [3] #mapreduce#731
>     @ ./reducedim.jl:322
>   [4] mapreduce
>     @ ./reducedim.jl:322
>   [5] #_maximum#749
>     @ ./reducedim.jl:894
>   [6] _maximum
>     @ ./reducedim.jl:894
>   [7] #maximum#747
>     @ ./reducedim.jl:890
>   [8] maximum
>     @ ./reducedim.jl:890
>   [9] #150
>     @ ~/AlphaZero.jl/redesign/private/gpu_compiler.jl:15
>  [10] _broadcast_getindex_evalf
>     @ ./broadcast.jl:670

You're calling `maximum` from within a kernel. Vectorized operations like that are not supported. Implementing them would only be possible using a single thread, and would kill performance.

**Comment by jonathan-laurent** [comment]
I agree that calling `maximum` from within a kernel would often be a red flag. However, I do not see why this is necessarily problematic. In my usecase, I am implementing some batched tree search on GPU and each thread is basically assigned to a single batch id. The maximum operation is computed within single threads but it is not a problem since the maximum is taken over a dozen elements at most whereas the batch size is of the order of several thousands.

In fact, AlphaGPU is already doing this and the performance is good:
https://github.com/fabricerosay/AlphaGPU/blob/master/mcts_gpu.jl#L120

The only difference is that AlphaGPU uses an explicit loop in their implementation. A call to `maximum` should be more readable and functionally equivalent .

**Comment by maleadt** [comment]
> I do not see why this is necessarily problematic.

`maximum` is implemented using `mapreduce`, as you can see in the stack trace. I don't think it's realistic to expect `Base.mapreduce` to compile within a kernel. If you care, you can create a GPU-compatible version of `maximum` (or `mapreduce`), implemented for `CuDeviceArray`.

**Comment by jonathan-laurent** [comment]
To be clear, `maximum` and `sum` already do compile within GPU kernels provided that one provides the `init` argument.

Also, I understand you are making the following argument: Because `maximum` and `sum` are implemented using `Base.mapreduce`, they do not necessarily compile into a naive for loop. Instead, they may compile into something fancier that leverages associativity. This fancier version may run faster than the naive one on CPU (by leveraging vectorized instructions) but slower on a single GPU thread. Therefore, I should just implement a for-loop version of `maximum` and `sum` and use those in my kernel instead. Am I getting this right?

**Comment by maleadt** [comment]
No, I'm considering the `Base.mapreducedim!` implementation way too complex to expect to compile for the GPU just like that. It does a whole bunch of things, e.g. lazily figuring out output types, size-based optimizations, etc. all of which depend on how good inference/the optimizer/LLVM was able to infer/optimize everything, because kernel code is expected to be fully static. That's just a very fragile situation, and I don't want to claim support for any of that.

**Comment by jonathan-laurent** [comment]
This makes sense, thanks. And although I ended up getting it to compile, I definitely observed this fragility you mentioned so this is not something I should be relying on.

But this opens the question: what operations am I allowed to use in code that may be run on GPU? Can I use `all` and `any` for example? More importantly, there is a huge appeal for me to write high-level code that could run with reasonable performances on both CPU and GPU. My impression was that Julia would shine on this thanks to multiple dispatch. However, not being able to use standard functions like `maximum` or `sum` in my device-agnostic code weakens this story. Could this be fixed by having CUDA implement specialized methods for those functions? What would the signature of such methods be?

(Admittedly, I am opening a wider debate here and so I would be happy to move this discussion elsewhere.)

**Comment by maleadt** [comment]
> My impression was that Julia would shine on this thanks to multiple dispatch. However, not being able to use standard functions like `maximum` or `sum` in my device-agnostic code weakens this story. Could this be fixed by having CUDA implement specialized methods for those functions? What would the signature of such methods be?

Multiple dispatch is exactly why we _can_ make this Just Work -- it's how CuArray specializes all kinds of operations for GPU execution -- as I suggested a couple of posts ago:

> If you care, you can create a GPU-compatible version of maximum (or mapreduce), implemented for CuDeviceArray.

Julia mapreduce doesn't have a clean internal API though, so choosing the level to implement is not trivial (you don't want to specialize `maximum` because that's too narrow, but implementing `Base._mapreduce_impl` is fragile and will break at the next Julia release). Look at CuArray/GPUArrays for inspiration.

**Comment by jonathan-laurent** [comment]
Actually, I have been thinking about it and I do not see how to define a new method for `Base.maximum` in such a way that makes the example in this issue work. The problem is that `maximum` does not receive any array as its argument. It is given two arguments: a range and a closure. The closure may be capturing some arrays but we cannot dispatch on those.

**Comment by maleadt** [comment]
Ah sorry, I glanced over that. You can use `@device_override` for that purpose, i.e., contextual dispatch.

**Comment by jonathan-laurent** [comment]
Thanks. This seems to be exactly what I was looking for. Is this documented anywhere?

Ultimately, I think it would be very nice if CUDA defined overriden GPU versions for operations such as `maximum` or `sum` but I guess I can do it myself for the moment. Also, as you said, it is not completely clear what function should be overriden exactly as `maximum` seems too narrow and `Base._mapreduce_impl` too fragile. What about I open a new issue about this once I have a proven usecase?

**Comment by maleadt** [comment]
> What about I open a new issue about this once I have a proven usecase?

Sounds good. Feel free to open a PR straight away, as `@device_override` currently isn't meant to be usable outside of CUDA.jl, so that definition would need to live here (and I agree that a GPU-compatible definition of `mapreduce` would be valuable).
