### ISSUE TITLE
versioninfo triggers artifact downloads

### ISSUE THREAD

**Issue by SimonWoods** [JuliaGPU/CUDA.jl#1549]
I don't use CUDNN or CUTENSOR but checking `versioninfo()` causes them both to be downloaded. I think it would be better to just show them as missing.

**Comment by maleadt** [comment]
This is intentional; I don't think showing them as missing would be an improvement.

**Comment by maleadt** [comment]
I'm going to close this. If you care greatly, feel free to open a PR that, e.g., adds a keyword argument to `versioninfo` not to download missing libraries.

**Comment by SimonWoods** [comment]
Thanks for clarifying. I suspect the no-download option would not be useful to the vast majority, so I'll just avoid using `versioninfo()`.
