### ISSUE TITLE
Window size in grid-stride loop

### ISSUE THREAD

**Issue by simsurace** [JuliaGPU/CUDA.jl#1573]
This was raised by @physicsjoke in https://github.com/JuliaGPU/BinomialGPU.jl/issues/24, which refers to an adaptation of the native `rand` kernel: Shouldn’t https://github.com/JuliaGPU/CUDA.jl/blob/aacfc36d14602ad10ae9535d2c04942713857ca8/src/random.jl#L48
read
```julia
window = blockDim().x * gridDim().x
```
instead? In other words, what is the reason for subtracting one?
The size by which the original array is partitioned seems to be the number of blocks times the number of threads per block, which seems to be equal to gridDim times blockDim. What am I missing?

**Comment by simsurace** [comment]
I also noted a difference with respect to https://github.com/JuliaGPU/CUDA.jl/blob/5efcee664ff50cfa1e14ad9ca4dfe6f600fabb10/lib/cublas/linalg.jl#L41

**Comment by maleadt** [comment]
> What am I missing?

Nothing, this looks like a bug :-)
