### ISSUE TITLE
Matrix multiplication works for primitive and non-primitive custom number types on the CPU, but it fails for primitive custom number types on the GPU.

### ISSUE THREAD

**Issue by tmbdev** [JuliaGPU/CUDA.jl#1574]
**Sanity checks (read this first, then remove this section)**

- [x ] Make sure you're reporting *a bug*; for general questions, please use Discourse or
  Slack.

- [x ] If you're dealing with a performance issue, make sure you **disable scalar iteration**
  (`CUDA.allowscalar(false)`). Only file an issue if that shows scalar iteration happening
  in CUDA.jl or Base Julia, as opposed to your own code.

- [x ] If you're seeing an error message, **follow the error message instructions**, if any
  (e.g. `inspect code with @device_code_warntype`). If you can't solve the problem using
  that information, make sure to post it as part of the issue.

- [x ] Always ensure you're using the latest version of CUDA.jl, and if possible, please
  check the master branch to see if your issue hasn't been resolved yet.

If your bug is still valid, please go ahead and fill out the template below.

**Describe the bug**

Matrix multiplication works for primitive and non-primitive custom number types on the CPU, but it fails for primitive custom number types on the GPU.

**To reproduce**

The Minimal Working Example (MWE) for this bug:

```julia
using Pkg
Pkg.activate(".")

using Cthulhu
using CUDA
CUDA.allowscalar(false)

##

versioninfo()
CUDA.versioninfo()

##

# n, m, k = 300, 400, 500
n, m, k = 3, 4, 5

##

# First, let's try matmul with a interval arithmetic

using IntervalArithmetic

println("interval arithmetic (CPU)")

ia = map(Interval, randn(n, m), randn(n, m));
ib = map(Interval, randn(m, k), randn(m, k));
@time ic = ia * ib;

println("interval arithmetic (GPU)")

cia = CuArray(ia);
cib = CuArray(ib);
@time cic = cia * cib;

##

# Define a primitive type using a tropical semiring

primitive type Tropical64 <: AbstractFloat 64 end
Tropical64(x::Float64) = reinterpret(Tropical64, x)
Tropical64(x::Int64) = reinterpret(Tropical64, Float64(x))
Float64(x::Tropical64) = reinterpret(Float64, x)
Base.show(io :: IO, x :: Tropical64) = Base.show(io, Float64(x))
import Base: +, *
+(x::Tropical64, y::Tropical64) = Tropical64(max(Float64(x), Float64(y)))
*(x::Tropical64, y::Tropical64) = Tropical64(Float64(x) + Float64(y))

@show (Tropical64(3) + Tropical64(4)) * Tropical64(5)

##

# Try it out on the CPU

println("regular matmul (CPU)")

a = randn(n, m);
b = randn(m, k);
@time c = a * b;

println("tropical matmul (CPU)")

a = reinterpret(reshape, Tropical64, a);
b = reinterpret(reshape, Tropical64, b);
@time c = a * b;

##

# Try it out on the GPU

println("regular matmul (GPU)")

a = CuArray(randn(n, m));
b = CuArray(randn(m, k));
@time c = a * b;

println("tropical matmul (GPU)")

ta = reinterpret(reshape, Tropical64, a);
tb = reinterpret(reshape, Tropical64, b);
try
    tc = ta * tb;
catch err
    code_typed(err, interactive = true)
end 

```

<details><summary>Manifest.toml</summary>
<p>

(attached as file)

</p>
</details>

**Expected behavior**

I expect matrix multiplication to work on both CPU and GPU, with Float64, Interval{Float64}, and Tropical64.

Actual output attached as file.

**Version info**

Details on Julia: 1.7.3+0.x64

```
# please post the output of:
versioninfo()
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 9 3900X 12-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, znver2)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 
```

Details on CUDA:

```
# please post the output of:
CUDA.versioninfo()
CUDA toolkit 11.7, artifact installation
NVIDIA driver 515.65.1, for CUDA 11.7
CUDA driver 11.7

Libraries: 
[Manifest.toml.txt](https://github.com/JuliaGPU/CUDA.jl/files/9287197/Manifest.toml.txt)
[output.txt](https://github.com/JuliaGPU/CUDA.jl/files/9287201/output.txt)
[Manifest.toml.txt](https://github.com/JuliaGPU/CUDA.jl/files/9287202/Manifest.toml.txt)

- CUBLAS: 11.10.1
- CURAND: 10.2.10
- CUFFT: 10.7.2
- CUSOLVER: 11.3.5
- CUSPARSE: 11.7.3
- CUPTI: 17.0.0
- NVML: 11.0.0+515.65.1
- CUDNN: 8.30.2 (for CUDA 11.5.0)
- CUTENSOR: 1.4.0 (for CUDA 11.5.0)

Toolchain:
- Julia: 1.7.3
- LLVM: 12.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
- Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80

1 device:
  0: NVIDIA RTX A6000 (sm_86, 47.304 GiB / 47.988 GiB available)
```
[Manifest.toml.txt](https://github.com/JuliaGPU/CUDA.jl/files/9287211/Manifest.toml.txt)
[output.txt](https://github.com/JuliaGPU/CUDA.jl/files/9287213/output.txt)

**Comment by tmbdev** [comment]
(If you have other suggestions for easily compiling custom CUDA kernels for matrix multiplication with different semirings, that would also be appreciated. I have written a CUDA kernel from scratch, but that is probably not as good as reusing existing kernels with different semirings.)

**Comment by maleadt** [comment]
Please just report the actual error, instead of a debug log that doesn't contain it.

```
ERROR: InvalidIRError: compiling kernel #50#51(CUDA.CuKernelContext, CuDeviceMatrix{Tropical64, 1}, CuDeviceMatrix{Tropical64, 1}, CuDeviceMatrix{Tropical64, 1}) resulted in invalid LLVM IR
Reason: unsupported dynamic function invocation (call to string(a::Union{Char, SubString{String}, String, Symbol}...) in Base at strings/substring.jl:219)
Stacktrace:
  [1] error
    @ ./error.jl:44
  [2] sametype_error
    @ ./promotion.jl:383
  [3] not_sametype
    @ ./promotion.jl:377
  [4] promote
    @ ./promotion.jl:360
  [5] <
    @ ./promotion.jl:428
  [6] signbit
    @ ./number.jl:137
  [7] copysign
    @ ./number.jl:209
  [8] *
    @ ./bool.jl:176
  [9] *
    @ ./bool.jl:178
 [10] #50
    @ ~/Julia/pkg/GPUArrays/src/host/linalg.jl:202
```

This comes from the fact that your type does not support multiplication with a boolean, which is used as the default value for alpha and beta in 5-arg mul!:

```
julia> Tropical64(1)*true
ERROR: promotion of types Tropical64 and Int64 failed to change any arguments
Stacktrace:
  [1] error(::String, ::String, ::String)
    @ Base ./error.jl:44
  [2] sametype_error(input::Tuple{Tropical64, Int64})
    @ Base ./promotion.jl:383
  [3] not_sametype(x::Tuple{Tropical64, Int64}, y::Tuple{Tropical64, Int64})
    @ Base ./promotion.jl:377
  [4] promote
    @ ./promotion.jl:360 [inlined]
  [5] <(x::Tropical64, y::Int64)
    @ Base ./promotion.jl:428
  [6] signbit(x::Tropical64)
    @ Base ./number.jl:137
  [7] copysign(x::Tropical64, y::Tropical64)
    @ Base ./number.jl:209
  [8] *(x::Bool, y::Tropical64)
    @ Base ./bool.jl:176
  [9] *(y::Tropical64, x::Bool)
    @ Base ./bool.jl:178
 [10] top-level scope
    @ REPL[57]:1
 [11] top-level scope
    @ ~/Julia/pkg/CUDA/src/initialization.jl:52
```

**Comment by tmbdev** [comment]
Thanks, that's very helpful. I'm not sure how I would be able to infer that Tropical*Bool is missing from that stack trace. It's also confusing to me why this would work on CPU but not on GPU. Neither `mul!` nor `*(x::Tropical64, y::Bool)` appear anywhere in the stack trace from the actual GPU error. Is this just something one has to know, or is there some way of getting more information on the context of the error? Could the error messages be improved?

**Comment by maleadt** [comment]
You should have been able to spot the issue by navigating to the error using Cthulhu, however in the log you attached you didn't descend deep enough:
```
Select a call to descend into or ↩ to ascend. [q]uit. [b]ookmark.
 %418  = invoke *(::Tropical64,::Bool)::Union{}
```

That call returned Union, which indicates an error and should hint to take a look at that code. But I agree it isn't trivial though, it's one of the disadvantages of shoehorning a dynamic language into a static compilation model (but we're improving here, I'm pretty sure JET.jl would have spotted this).



> It's also confusing to me why this would work on CPU but not on GPU.

Yeah it surprised me too, possible an invocation where the `MulAdd` struct detects default values for alpha/beta and doesn't perform those additions/multiplications.
