### ISSUE TITLE
FastMath sincos(), cis(), exp(im..) aren't as fast as C++

### ISSUE THREAD

**Issue by tkuraku** [JuliaGPU/CUDA.jl#1606]
sincos(), cis(), exp(im..) converts Float32 to and from double. This causes a big slowdown in cuda kernels. This issue isn't present when calling cos() and sin() individually.

I don't know if this is a bug with Julia or CUDA.jl. seems like if you call a trig function with Float32 it should do the calculation all in Float32 instead of converting to double.

Here is the related Discourse post.

<https://discourse.julialang.org/t/cuda-jl-kernel-is-half-as-fast-as-c-kernel/87651>

This is with Julia 1.8.1 and CUDA.jl 3.12.

**Comment by maleadt** [comment]
`sincos` at least shouldn't:

https://github.com/JuliaGPU/CUDA.jl/blob/79d84687a7ecb70a65b04e0bfb452a7bdf0360cd/src/device/intrinsics/math.jl#L37-L42

`cis` just uses `sincos`, so shouldn't either.

`exp(im)` relies on `exp(::Float32` and `sincos` (see above), and for `exp` we have:

https://github.com/JuliaGPU/CUDA.jl/blob/79d84687a7ecb70a65b04e0bfb452a7bdf0360cd/src/device/intrinsics/math.jl#L126

All this means that we shouldn't be falling back to Julia implementations, and that we're using NVIDIA's code here. Indeed, in your Discourse post your IR contains `__internal_trig_reduction_slowpath.exit` which is a tell for the NVIDIA bitcode libraries. So if doubles are still being introduced, that's because NVIDIA implemented it as such.

---

If you still want to avoid using doubles, have a look at the Base implementation for these operations. If `Base.sin` turns out faster than the libdevice one (e.g. because it doesn't use doubles), we could consider switching away from libdevice.

**Comment by tkuraku** [comment]
sin() and cos() don't use doubles, only sincos. Interesting if that is how Nvidia implemented it. Maybe there is no bug, but it surprising behavior from that there is much better performance to not use sincos().

**Comment by tkuraku** [comment]
Is it using the double precision sincos() instead of the single precision sincosf() for some reason?

**Comment by maleadt** [comment]
> Is it using the double precision sincos() instead of the single precision sincosf() for some reason?

I'm not sure, are you observing that? We are calling `sincosf` as you can see above.

If you're interested, you could try and benchmark the different options we have. If separate `sin` and `cos` calls are faster, or using `Base.sincos`, we could switch away from NVIDIA's `sincosf`.

**Comment by tkuraku** [comment]
I'll try and do some benchmarks of the various options and report back on a day or two.

**Comment by tkuraku** [comment]
I couldn't wait and did a couple benchmarks. This is with the kernel from the discourse post.

The code in the kernels was changed between these two variants

```c++
// C++
float a = cos(x);
float b = sin(x);
// Versus
float a,b;
sincos(x, &b, &a);
```

```Julia
# Julia
a = cos(2.0f0 * kc * r_theory)
b = sin(2.0f0 * kc * r_theory)
# Versus
b, a = sincos(2.0f0 * kc * r_theory)
```

|             | Julia  | c++     |
| ----------- | ------ | ------- |
| cos(),sin() | 980 ms | 780 ms  |
| sincos      | 1.25 s | 778 ms |

Not sure what the issue is but there is an issue with sincos in Julia that doesn't exists in the c++ version.

**Comment by tkuraku** [comment]
I get the same performance using Base.sincos(). It is almost like it isn't calling the nvidia function and is using Base.sincos even when using CUDA.sincos.

**Comment by maleadt** [comment]
Testing with:

```
julia> function kernel(a,b,c)
       @inbounds b[threadIdx().x], c[threadIdx().x] = sincos(a[threadIdx().x])
       return
       end
kernel (generic function with 2 methods)

julia> CUDA.code_XXX(kernel, NTuple{3,CuDeviceArray{Float32,1,AS.Global}})
```

I indeed see the same double in the LLVM IR as you reported on Discourse:

```llvm
__internal_trig_reduction_slowpath.exit.i.i.i:    ; preds = %52, %40
...
   %76 = sitofp i64 %75 to double
   %77 = fmul double %76, 0x3BF921FB54442D19
   %78 = fptrunc double %77 to float
```

Again, the lack of debug info and the name of the BB clearly tells us we're using libdevice here. This further compiles to the following PTX (with expectedly only 3 f64 ops):

```
	.reg .f64 	%fd<3>;

LBB0_7:                                 // %__internal_trig_reduction_slowpath.exit.i.i.i
...
	cvt.rn.f64.s64 	%fd1, %rd21;
	mul.f64 	%fd2, %fd1, 0d3BF921FB54442D19;
	cvt.rn.f32.f64 	%f11, %fd2;
```

Comparing to C++:

```c++
❯ cat test.cu
__global__ void kernel(float* a, float* b, float* c) {
int i = threadIdx.x;
sincos(a[i], &a[i], &b[i]);
return;
}

❯ nvcc -ptx test.cu -o -
```

```
	.reg .f64 	%fd<3>;

$L__BB0_6:
...
	cvt.rn.f64.s64 	%fd1, %rd24;
	mul.f64 	%fd2, %fd1, 0d3BF921FB54442D19;
	cvt.rn.f32.f64 	%f14, %fd2;
```

So I'm not seeing a difference here...

**Comment by tkuraku** [comment]
Hmm. Not sure what the issue is. Maybe it is something to do with my setup. Odd that somehow I have a performance regression with sincos in Julia. I really appreciate you taking the time to look it over.

**Comment by tkuraku** [comment]
Did a little more investigation and it looks like the difference is fast math. I was compiling the c++ cuda code with --use_fast_math. If you do that then there isn't any f64 in the ptx. In the discourse post I have @fastmath at the kernel declaration, but it doesn't seem to be doing the same optimization.

**Comment by maleadt** [comment]
Ah, that's interesting. `@fastmath` (please quote so that's you don't ping that user :-))  _is_ something that we should support: https://github.com/JuliaGPU/CUDA.jl/blob/79d84687a7ecb70a65b04e0bfb452a7bdf0360cd/src/device/intrinsics/math.jl#L22

**Comment by tkuraku** [comment]
Didn't even notice that i was pinging someone!  Thanks for your work on this. Let me know if there is anything else I can help with.

**Comment by maleadt** [comment]
Fix up in https://github.com/JuliaGPU/CUDA.jl/pull/1627, please have a look 🙂

**Comment by tkuraku** [comment]
nice job! Looks like that will probably do it. thank you for all your help!
