### ISSUE TITLE
backslash with gpu matrices crashes julia

### ISSUE THREAD

**Issue by jrebula** [JuliaGPU/CUDA.jl#161]
I'm trying to solve a system of linear equations on the GPU, but it crashes julia with no error message. My understanding of [a discussion](https://discourse.julialang.org/t/unified-interface-for-linear-solving/699/18) from a year or two ago was that backslash would be the way to access the cusolver routines. The simplest backslash attempt crashes julia with no error message, then since
it appears that cusolver has (a routine that solves a system with a triangular structure)[https://software.intel.com/en-us/mkl-developer-reference-c-trtrs], I tried to get to that by performing a QR decomposition on the cuarrays (which works fine), then solving the triangular version of the problem, with the same result. I couldn't find that routine wrapped in CuArrays.jl anyway though. Backslash seemed the most natural way to do this, but is there an accepted way to do this that I'm missing? 

```
using CuArrays
using LinearAlgebra

A, y = rand(3,4), rand(3)
cuA, cuY = cu(A), cu(y)
getQR(A) = begin
  QR = qr(A)
  return (QR.Q, QR.R)
end
Q, R = getQR(A)
cuQ, cuR = getQR(cuA)

actualSolution = A \ y
solutionFromQR = R \ (Q' * y)
@assert(all(abs.(actualSolution - solutionFromQR) .< 1e-4))
println("all is well thus far")
solutionFromCu = cuA \ cuY # crashes
solutionFromCuQR = cuR \ (cuQ' * cuY) # also crashes

```

if relevant:
```
julia> versioninfo()
Julia Version 1.0.1
Commit 0d713926f8 (2018-09-29 19:05 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)

julia> CUDAdrv.device()
CuDevice(0): GeForce GTX 1050
```

**Comment by maleadt** [comment]
These work now.
