### ISSUE TITLE
wrong type in wrapper of a cusolver function

### ISSUE THREAD

**Issue by jemiryguo** [JuliaGPU/CUDA.jl#1621]
In file libcusolver.jl:4254 `cusolverDnXgesvdr_bufferSize`, the parameter type of `workspaceInBytesOnDevice` (second from last) is `CuPtr{Csize_t}`. However, according to Nividia cusolver documatation https://docs.nvidia.com/cuda/cusolver/index.html#cuSolverDnXgesvdr, it should on CPU, and the right type shoule be `Ptr{Csize_t}`

**Comment by maleadt** [comment]
Good catch. Could you open a PR?

**Comment by jemiryguo** [comment]
PR #1626
