### ISSUE TITLE
Adding CUDNN support for 3D convolutions/cross-correlations

### ISSUE THREAD

**Issue by Marc-3d** [JuliaGPU/CUDA.jl#1631]
I am working with 3D microscopy data and I need to perform 3D cross-correlation of volumes as fast as possible. I have been looking at the CUDNN wrapper in CUDA.jl, and I have noticed that it does not include the "NCDWH" format, which allows to work with 3D volumes (technically 4D volumes if you include multiple channels). 

Is there a reason why the NCDHW format is not included in the CUDNN wrapper?

I am thinking of including it myself, and I was wondering if you had already run into problems while adding support for the 3D format.. and I can avoid running into them myself.

**Comment by maleadt** [comment]
> Is there a reason why the NCDHW format is not included in the CUDNN wrapper?

Not that I know, @denizyuret created the original wrappers so he may be able to elaborate.

**Comment by denizyuret** [comment]
@Marc-3d the reason is probably it didn't exist when we wrote the interface. libcudnn.jl does not include it as a constant, so the code needs updating. Have you had a chance to try it out?

**Comment by Marc-3d** [comment]
It turns out that CUDNN doesn't define the 3D formats explicitly. Instead one should know that 3D formats reuse their 2D counterparts. 

For example, NCDHW is just an extension of NCHW, and one should use`CUDA.CUDNN.CUDNN_TENSOR_NCHW`. Similarly, NDHWC is equivalent to `CUDA.CUDNN.CUDNN_TENSOR_NHWC`.

This is written in the [documentation](https://docs.nvidia.com/deeplearning/cudnn/developer-guide/index.html#fntarg_1), but only as a small note, so I missed it.
