### ISSUE TITLE
CUDA test failed 

### ISSUE THREAD

**Issue by lf28** [JuliaGPU/CUDA.jl#1690]
**Describe the bug**

I have just installed CUDA.jl. As a sanity check, I tried to run the test. But a lot of them failed in the end. 

To isolate the problem, I have also tried the test with a single thread (and also with sanitize option). The tests still fail. 

**To reproduce**

The Minimal Working Example (MWE) for this bug:

```julia
julia -e "using Pkg; using CUDA; Pkg.test(\"CUDA\");"
```

<details><summary>Manifest.toml</summary>
<p>

```
[052768ef] CUDA v3.12.0
[61eb1bfa] GPUCompiler v0.16.7
```

</p>
</details>

**Expected behavior**

All tests passed

**Version info**

Details on Julia: 1.8.3

```
# please post the output of:
Julia Version 1.8.3
Commit 0434deb161e (2022-11-14 20:14 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_CMDSTAN_HOME = /home/xx/cmdstan/
```

Details on CUDA:

```
# please post the output of:
CUDA toolkit 11.7, artifact installation
NVIDIA driver 525.60.11, for CUDA 12.0
CUDA driver 12.0

Libraries: 
- CUBLAS: 11.10.1
- CURAND: 10.2.10
- CUFFT: 10.7.2
- CUSOLVER: 11.3.5
- CUSPARSE: 11.7.3
- CUPTI: 17.0.0
- NVML: 12.0.0+525.60.11
- CUDNN: 8.30.2 (for CUDA 11.5.0)
- CUTENSOR: 1.4.0 (for CUDA 11.5.0)

Toolchain:
- Julia: 1.8.3
- LLVM: 13.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0, 7.1, 7.2
- Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80, sm_86

1 device:
  0: NVIDIA GeForce GTX 1060 6GB (sm_61, 5.925 GiB / 6.000 GiB available)
```

[log.txt](https://github.com/JuliaGPU/CUDA.jl/files/10179911/log.txt)

**Comment by maleadt** [comment]
> But a lot of them failed in the end.

You ran with `--quickfail`, so only 1 test failed, the others got interrupted.

The only actual failure:

```
gpuarrays/reductions/reducedim!: Test Failed at /home/lf28/.julia/packages/GPUArrays/fqD8z/test/testsuite/reductions.jl:24
  Expression: compare(((A, R)->begin
            Base.reducedim!(+, R, A)
        end), AT, rand(range, sz), zeros(ET, red))
```

To debug this, it would need to be reduced to a MWE that demonstrates the failure, this error report doesn't contain enough details.
