### ISSUE TITLE
`UndefVarError` when a binary is not found

### ISSUE THREAD

**Issue by Seelengrab** [JuliaGPU/CUDA.jl#1701]
https://github.com/JuliaGPU/CUDA.jl/blob/3729010513021308b0b840455458a604358db543/deps/discovery.jl#L161

The variable `path` doesn't exist there, it's a local variable in the loop.

**Comment by maleadt** [comment]
Thanks. This code isn't part of the master branch anymore.

**Comment by maleadt** [comment]
Oh, actually, I put that code in https://github.com/JuliaGPU/CUDA_Runtime_Discovery.jl. I'll fix it there 🙂

**Comment by Seelengrab** [comment]
Yes, it took quite some time to hunt this line down :) I just noticed that this was still part of the release here, that's how I found it.
