### ISSUE TITLE
Subarrays/views support

### ISSUE THREAD

**Issue by andreasnoack** [JuliaGPU/CUDA.jl#172]
I've been trying to make more of the highlevel linear algebra routines work similarly to the Base versions. For this to really work well, we'll need support for strided views where `stride(A,1)==1` but `stride(A,2)>size(A,1)`. Currently, I see two approaches to support `view` for `CuArrays`: 1) Make Base's `SubArray`s work for `CuArray` or 2) include strides information in the `CuArray` to support this.

The `CuArray` struct already includes a field for offset and it wraps a memory buffer so it might make sense to make `CuArray`s more general and add a strides field. The cost is that people working explicitly with the buffer would have to be more careful about the strides information. These views would also be less general than Base's `SubArray`s but I think they'll cover the more important cases.

Last night I tried the other approach, i.e. to just wrap `CuArray`s in `SubArray` but it doesn't work with `ccall` and it might require some controversial changes to how `CuArray`s are converted to `Ptr` if we want to go this direction. Basically, the problem is that `unsafe_convert(Ptr{T}, CuArray{T})` isn't defined and therefore you can't pass a `SubArray{CuArray}` to `ccall`.

What do people think? Which one is the better solution or have a missed a third better option? Personally, I lean towards including stride information in `CuArray`s since we already wrap a memory buffer and attach shape information so also doing this as part of a `SubArray` is kind of double wrapping.

**Comment by maleadt** [comment]
~This is implemented now.~
EDIT: false, only support for broadcast has been improved.

**Comment by maleadt** [comment]
> the problem is that `unsafe_convert(Ptr{T}, CuArray{T})` isn't defined and therefore you can't pass a `SubArray{CuArray}` to `ccall`.

This has been implemented now, e.g.: https://github.com/JuliaGPU/CUDA.jl/blob/bc0184eaba90c303e73c44a1768b6b7cb36ed669/lib/cublas/wrappers.jl#L89-L102
