### ISSUE TITLE
Use of linear operators in CUDA.jl

### ISSUE THREAD

**Issue by shakedregev** [JuliaGPU/CUDA.jl#1727]
Say I have a sparse matrices `$A$` and `$B=D*A^T$` and their product is dense. I want to solve systems with them using an iterative method from Krylov.jl. On a CPU, I can do
`opC =LinearOperator(A)*LinearOperator(B)`
`cg(opC,r)`
This works fine, but how do I do this with CUDA?

**Comment by maleadt** [comment]
That's not a topic for the **issue** tracker. Open a discussion on the Krylov.jl repo, or a thread on Discourse.
