### ISSUE TITLE
CUSOLVER: support eigendecomposition

### ISSUE THREAD

**Issue by hayatoikoma** [JuliaGPU/CUDA.jl#173]
I am currently trying to perform an eigendecomposition on GPU.
Is there any plan for `CuArrays.jl` to support it from CUSOLVER sometime soon?

**Comment by kshyatt** [comment]
With the merge of JuliaGPU/CuArrays.jl#170, we support these for sparse matrices - if you want the new dense solvers, I can try to add those?

**Comment by maleadt** [comment]
These seem implemented: https://github.com/JuliaGPU/CUDA.jl/blob/2a3cec926ba48f5bb4efbec5c9242259370963fa/lib/cusolver/linalg.jl#L113-L134
