### ISSUE TITLE
Trouble using nsight systems for profiling CUDA in Julia

### ISSUE THREAD

**Issue by JamieMair** [JuliaGPU/CUDA.jl#1779]
The [CUDA.jl documentation](https://cuda.juliagpu.org/stable/development/profiling/#NVIDIA-Nsight-Systems) suggests that we launch profiling with
```sh
nsys launch julia
```
But this results with "program not found: julia" so I have to specify the path manually:
```sh
nsys launch C:\Users\...\julia.exe
```
Once the path is fully specified it launches, but the profiling immediately ends with
```sh
application launched
Required property not found
```
Is this happening to others on Windows? I was able to launch profiling through the GUI running a script, but it would be much better to have an interactive experience and only profile part of the program. Is there any advice on this?

System Info:
Julia version: 1.9.0-beta4 (via Juliaup)
OS: Windows 11
NVIDIA Driver: 527.37
CUDA Version: 12.0
NVIDIA Nsight Systems version: 2022.5.1.82-32078057v0

**Comment by maleadt** [comment]
> application launched
> Required property not found

Are those the exact errors? I don't find anything relevant Googling them. In any case, no I haven't run into this, and I haven't seen reports of other users encountering these issues.

**Comment by JamieMair** [comment]
Unfortunately yes, this is the only output from `nsys`, I also had no luck finding any other similar errors/situations online

**Comment by maleadt** [comment]
I think your best bet is to file a bug with NVIDIA, they are typically very responsive as long as you provide a good reproducer. So a MWE where you download beta4 from a tarball and use the latest nsys would be best (i.e., no use of `juliaup`, no use of CUDA.jl, etc).

**Comment by maleadt** [comment]
Going to close this as this does seem like an upstream issue.
