### ISSUE TITLE
Suggestion - Disable AbstractArray indexing fallback by default

### ISSUE THREAD

**Issue by ViralBShah** [JuliaGPU/CUDA.jl#178]
If you mix CuArrays with Base Arrays, you get the slow version of things. I think this should best be disabled by default and give a nice error. Users should be able to opt in to enable it.

**Comment by dpsanders** [comment]
I think it would make sense to change the *default* to 

`CUDA.allowscalar(false)`

but still allow the user to specify

`CUDA.allowscalar(true)`,

i.e. the reverse of the current situation, since my guess is that the majority of codes out there start with `CUDA.allowscalar(false)`.

**Comment by ViralBShah** [comment]
Yes, that was basically what I was suggesting.

**Comment by maleadt** [comment]
A situation where this might degrade the experience:

```julia
julia> using CUDA
julia> sin.(CUDA.rand(Float32, 2))
2-element CuArray{Float32,1,Nothing}:
 0.08872609
 0.03352104
julia> sin.(CUDA.rand(Int, 2))
┌ Warning: Performing scalar operations on GPU arrays: This is very slow, consider disallowing these operations with `allowscalar(false)`
└ @ GPUArrays ~/.julia/packages/GPUArrays/HGtNV/src/host/indexing.jl:43
ERROR: MethodError: no method matching sin(::Int64)
You may have intended to import Base.sin
```

A failing broadcast falls back to scalar iteration -- disabling so would result in never seeing the MethodError.

We could make the warning scarier though.

**Comment by zhangcx93** [comment]
Can we have a global settings for disabling scaler index? like a environment variable?
I found in Pluto, using CUDA.allowscalar(false) doesn't have any effect. So I can put the `ENV["CUDAallowscalar"] = false` in startup.jl, and it'll do the job. And for those who want to make it default, it's a easy solution.

**Comment by zhangcx93** [comment]
Oh I found the ENV["JULIA_GPU_ALLOWSCALAR"] in source code... how about a doc for that?
