### ISSUE TITLE
Feature request: Integrating the latest CUDA library "cuLitho" into CUDA.jl

### ISSUE THREAD

**Issue by algorithmx** [JuliaGPU/CUDA.jl#1821]
Recently, Nvidia has released the library ["cuLitho"](https://developer.nvidia.com/culitho) to support computational lithography. Although this library only gets interests from a small community, but the support from CUDA.jl would be essential for certain companies and many hobbyists to quickly try out ideas in the area of computational lithography.

**Comment by maleadt** [comment]
Where can one download this library?

**Comment by maleadt** [comment]
cuLitho isn't public, so not much we can do here.
