### ISSUE TITLE
Windows Defender mis-labels artifacts as threat

### ISSUE THREAD

**Issue by rtdietrich** [JuliaGPU/CUDA.jl#1836]
I tried to install CUDA and got this warning under WIN11

![Virus-Warning-Screenshot 2023-03-26 235528](https://user-images.githubusercontent.com/13079745/227807089-a25057e8-f701-4269-a07c-68591c42bcad.png)

and this:
![Virus-Screenshot 2023-03-26 235944](https://user-images.githubusercontent.com/13079745/227807307-9b7cfee2-34e3-46dd-88de-06a17d4a1b54.png)

Any Help or Workaround?

**Comment by vchuravy** [comment]
Not really...

Which version of CUDA_Runtime_jll is it trying to install? The archives are here https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/tag/CUDA_Runtime-v0.2.4%2B0 and are auto-generated...

**Comment by rtdietrich** [comment]
Version? 

I have no idea. I just installed julia and typed "add CUDA" (I am a beginner with julia). I can of course disable the virus scanner, if you assure me that the file is clean, then the problem is also off the table.

I found this in another error message: https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+2/CUDA_Runtime.v0.4.0.x86_64-w64-mingw32-cuda+12.1.tar.gz
Hope this helps

![Detail-Screenshot 2023-03-27 004708](https://user-images.githubusercontent.com/13079745/227809605-ebaf32f1-7d23-4091-af4b-f89209c1f680.png)

**Comment by vchuravy** [comment]
What is `]status -m`

But yeah very unsure what to do here. What Virus scanner is this? I am pretty sure it is a miss-detection...

**Comment by rtdietrich** [comment]
![Detail-2](https://user-images.githubusercontent.com/13079745/227812272-5925c25d-4089-480d-8437-2ac3ff3fa8a5.png)

There was once a very similar problem with another programming language named "nim". Unfortunately, it was very difficult to solve.

The error was triggered by the on-board Windows scanner.

There is a reporting center at MS but it can take time until something is done. Unfortunately I don't know the address anymore.

The whole thing could be circumvented by excluding the folder for the affected area from the virus scan.

In my case: C:\Users\rtdie\AppData\Local\Temp

I have now tested this for this case and the workaround works. It only unfortunately a stopgap solution

Proof: 
![Proof](https://user-images.githubusercontent.com/13079745/227812353-0b763068-8909-4502-801a-1e04136ea7a5.png)

**Comment by maleadt** [comment]
> There is a reporting center at MS but it can take time until something is done. Unfortunately I don't know the address anymore.

I'm not sure what else we can do though. What are you suggesting? The archives contain essential binaries from NVIDIA, which we can't recompile or otherwise modify.
