### ISSUE TITLE
Unexpexted memory allocation when using `randn!`

### ISSUE THREAD

**Issue by Yangyang-Tan** [JuliaGPU/CUDA.jl#1856]
**Describe the bug**
Unexpexted Memory allocation when using `randn!` 

**To reproduce**

The Minimal Working Example (MWE) for this bug:

```julia
using Random, CUDA
a = CUDA.zeros(2^10, 1000)
CUDA.@time CUDA.randn!(a)
```
which give the output
```
0.000080 seconds (7 CPU allocations: 256 bytes) (1 GPU allocation: 4.000 MiB, 28.40% memmgmt time)
```

**Expected behavior**
This should gives no GPU  allocation.

**Version info**

Details on Julia:

```
julia> versioninfo()
Julia Version 1.9.0-rc1
Commit 3b2e0d8fbc1 (2023-03-07 07:51 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 48 × Intel(R) Xeon(R) Gold 6146 CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake-avx512)
  Threads: 48 on 48 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 48
```

Details on CUDA:

```
julia> CUDA.versioninfo()
CUDA runtime 11.8, artifact installation
CUDA driver 12.1
NVIDIA driver 530.30.2

Libraries: 
- CUBLAS: 11.11.3
- CURAND: 10.3.0
- CUFFT: 10.9.0
- CUSOLVER: 11.4.1
- CUSPARSE: 11.7.5
- CUPTI: 18.0.0
- NVML: 12.0.0+530.30.2

Toolchain:
- Julia: 1.9.0-rc1
- LLVM: 14.0.6
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0, 7.1, 7.2, 7.3, 7.4, 7.5
- Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80, sm_86

4 devices:
  0: NVIDIA GeForce RTX 4090 (sm_89, 23.646 GiB / 23.988 GiB available)
  1: NVIDIA GeForce RTX 4090 (sm_89, 23.646 GiB / 23.988 GiB available)
  2: NVIDIA TITAN V (sm_70, 11.770 GiB / 12.000 GiB available)
  3: NVIDIA GeForce RTX 2080 Ti (sm_75, 10.750 GiB / 11.000 GiB available)
```

**Additional context**

This behaviour may comes from https://github.com/JuliaGPU/GPUArrays.jl/blob/cd237a4f77ddfaeea6d01c6ea84ca02e71da3108/src/host/random.jl#L110
where the `A` should be deleted.

**Comment by maleadt** [comment]
> This behaviour may comes from https://github.com/JuliaGPU/GPUArrays.jl/blob/cd237a4f77ddfaeea6d01c6ea84ca02e71da3108/src/host/random.jl#L110
> where the `A` should be deleted.

I'm not sure what you mean. `A` there refers to the input array, so it's not because the in-place function returns its input (as most in-place functions do) that this would result in an allocation.

Regardless, the allocation here is needed because CURAND expect pow2-sized inputs: https://github.com/JuliaGPU/CUDA.jl/blob/5c51766d0a9e7819ea79f314e37ed6a8a5d24369/lib/curand/random.jl#L80-L93

You can avoid this by manually padding your array:

```
julia> a = CUDA.zeros(2^10, 1000);

julia> CUDA.@time CUDA.randn!(a);
  0.000091 seconds (5 CPU allocations: 192 bytes) (1 GPU allocation: 4.000 MiB, 14.36% memmgmt time)

julia> a = CUDA.zeros(2^10, 1024);

julia> CUDA.@time CUDA.randn!(a);
  0.000055 seconds
```

Or by using CUDA.jl's native RNG (which isn't used by default for operations that can be performed using CURAND):

```julia
julia> a = CUDA.zeros(2^10, 1000);

julia> rng = CUDA.RNG();

julia> CUDA.@time CUDA.randn!(rng, a);
  0.000060 seconds (23 CPU allocations: 944 bytes)
```

The additional CPU allocations here are due to kernel launches.

**Comment by Yangyang-Tan** [comment]
I get it. Thanks a lot.
