### ISSUE TITLE
Creating a sparse diagonal matrix of CuArray(u) 

### ISSUE THREAD

**Issue by HamMoh94** [JuliaGPU/CUDA.jl#1857]
If we have a vector (u), we can easily convert it into a sparse diagonal matrix using the command spdiagm(u).

If we want to do the same operation on the GPU using CUDA where u is defined as CuArray(u). The command spdiagm(u) gives the scalar indexing error and therefore it does not work.

 CuSparseMatrixCSC(Diagonal(u)) works but it is quite slow. Is there a way to perform this task efficiently?

Regards

**Comment by maleadt** [comment]
Currently not. It should be possible to do so quite easily by manually constructing the necessary inner arrays (colptr, rowval, nzval).

**Comment by HamMoh94** [comment]
Thank you for your reply. 
After understanding the way sparse matrices are stored, one can easily build a diagonal sparse matrix of size N with vector u as diagonal as follows:

```julia
Diag_u   = CuSparseMatrixCSC{Float64,Int32}( colptr, rowval ,  nzval ,dims)
where,
nzval = CuArray(u)
colptr  = CuArray(1:1:N)
rowval = CuArray(1:1:N) 
dims = (N,N)
```

**Comment by maleadt** [comment]
Would be great to have that as an implementation of the `SparseArrays.spdiagm` method.
