### ISSUE TITLE
Passing tests using Github CI workflow errors with `libcuda not defined`

### ISSUE THREAD

**Issue by b-fg** [JuliaGPU/CUDA.jl#1867]
Together with @weymouth, we are trying to port [Waterlily.jl](https://github.com/weymouth/WaterLily.jl/) to multi-threaded CPU and GPU backends using CUDA.jl and KernelAbstractions.jl (check our [CUDA branch](https://github.com/weymouth/WaterLily.jl/tree/CUDA) if interested). The process has been fairly smooth and we are pretty much there already, thanks for these awesome packages!

Still an annoying thing is that we cannot currently run the unit tests in the Github CI workflow, even if the tests pass without any problems in our local machines. The error is simple: `UndefVarError: libcuda not defined`, but please see the [full error log](https://github.com/weymouth/WaterLily.jl/actions/runs/4702111682/jobs/8338988433?pr=45) for further details. I have tried to use the latest CUDA.jl@4.1.4 (since it was apparently fixing related issues) with no luck so far. Can you spot something wrong in our way to set up the workflow? Any help would be appreciated, thanks!

**Comment by maleadt** [comment]
> The error is simple: `UndefVarError: libcuda not defined`, but please see the [full error log](https://github.com/weymouth/WaterLily.jl/actions/runs/4702111682/jobs/8338988433?pr=45) for further details.

That's expected, as you're trying to execute CUDA code on a system without CUDA. Or what were you expecting?

Admittedly, the error isn't terribly clear. I've tried to improve it here, https://github.com/JuliaGPU/CUDA.jl/pull/1868, please try this out.

**Comment by b-fg** [comment]
Thanks! Still, how is one supposed to run CI tests using Github workflows with CUDA.jl then?

**Comment by maleadt** [comment]
> Still, how is one supposed to run CI tests using Github workflows with CUDA.jl then?

You don't? You need a CI system that has a GPU, so if you want to use Github actions you'll need to provide your own runner. JuliaGPU has its own CI system based on buildkite, which we use for community packages (like CUDA.jl), https://github.com/JuliaGPU/buildkite.

**Comment by b-fg** [comment]
Ah okay, I was expecting Github to provide such runner I guess... thanks for the information :)
