### ISSUE TITLE
Runtime not re-selected after driver upgrade

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CUDA.jl#1877]
We're currently embedding the selected driver in the precompilation image. For example, here I just upgraded my driver, but didn't recompile the Runtime JLL:

```julia
❯ julia +1.9
julia> using CUDA
CUDA.versioninfo()

julia> CUDA.versioninfo()
CUDA runtime 11.8, artifact installation
CUDA driver 12.1
NVIDIA driver 530.41.3


❯ jl +1.9 --pkgimages=no --compiled-modules=no
julia> using CUDA
  Downloaded artifact: CUDA_Runtime

julia> CUDA.versioninfo()
CUDA runtime 12.1, artifact installation
CUDA driver 12.1
NVIDIA driver 530.41.3
```

That's not great. cc @vchuravy

**Comment by maleadt** [comment]
Forcibly recompiling the relevant packages didn't help:

```julia
julia> Base.compilecache(Base.PkgId(Base.UUID("76a88914-d11a-5bdc-97e0-2f5a05c973a2"), "CUDA_Runtime_jll"))
[ Info: Precompiling CUDA_Runtime_jll [76a88914-d11a-5bdc-97e0-2f5a05c973a2]
("/home/tim/Julia/depot/compiled/v1.9/CUDA_Runtime_jll/Hs50y_u396q.ji", nothing)

julia> Base.compilecache(Base.PkgId(Base.UUID("052768ef-5323-5732-b1bb-66c8b64840ba"), "CUDA"))
[ Info: Precompiling CUDA [052768ef-5323-5732-b1bb-66c8b64840ba]
("/home/tim/Julia/depot/compiled/v1.9/CUDA/oWw5k_u396q.ji", nothing)

❯ jl +1.9 --pkgimages=no
julia> using CUDA

julia> CUDA.versioninfo()
CUDA runtime 11.8, artifact installation
CUDA driver 12.1
NVIDIA driver 530.41.3
```

Removing all images did:

```
❯ rm -rf /home/tim/Julia/depot/compiled/v1.9/CUDA*

❯ jl +1.9 --pkgimages=no
julia> using CUDA
[ Info: Precompiling CUDA [052768ef-5323-5732-b1bb-66c8b64840ba]

julia> CUDA.versioninfo()
CUDA runtime 12.1, artifact installation
CUDA driver 12.1
NVIDIA driver 530.41.3
```

**Comment by MariusDrulea** [comment]
Just had this issue. I have added CUDA.jl while using nouveau driver on Ubuntu, then switched to an Nvidia Driver. I had to remove the compiled CUDA stuff, just like in the previous comment.

**Comment by vchuravy** [comment]
We could use `Base.include_dependency` to invalidate the cache-files when a file on disk changes.

x-ref: https://github.com/JuliaLang/julia/pull/49866#issuecomment-1747041990

**Comment by maleadt** [comment]
> We could use `Base.include_dependency` to invalidate the cache-files when a file on disk changes.

I know, but manually invalidating the CUDA_Runtime_jll compilecache didn't help; see initial post. Adding an include dependency does seem to work, even though that just invalidates the compilecache... Not sure what's happening, but I added the change in https://github.com/JuliaPackaging/Yggdrasil/pull/7514
