### ISSUE TITLE
Cannot construct CuDeviceArray

### ISSUE THREAD

**Issue by cruzgodar** [JuliaGPU/CUDA.jl#1887]
**Describe the bug**

It seems to be impossible to create useful non-shared arrays in a kernel. Defining one with e.g. `x = [1, 2, 3, 4]` throws an error (that there’s an unsupported call through a literal pointer), which makes sense — it’s not a bits type. It seems as though `CuDeviceArray` is designed to fix this problem and its definition in the documentation describes it being used to construct arrays, but it has no methods.

**To reproduce**

The Minimal Working Example (MWE) for this bug:

```julia
methods(CuDeviceArray)
# Output: # 0 methods for type constructor
```

<details><summary>Manifest.toml</summary>
<p>

CUDA.jl: v4.1.4
GPUArrays.jl: v8.6.6
GPUCompiler.jl: v0.19.3
LLVM.jl: v5.0.0

</p>
</details>

**Expected behavior**

To be able to construct mutable, fixed-length, non-shared arrays inside of a kernel.

**Version info**

Details on Julia:

```
# Julia Version 1.8.5
Commit 17cfb8e65e (2023-01-08 06:45 UTC)
Platform Info:
 OS: Windows (x86_64-w64-mingw32)
 CPU: 4 x Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
 WORD_SIZE: 64
 LIBM: libopenlibm
 LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
 Threads: 1 on 4 virtual cores
```

Details on CUDA:

```
CUDA runtime 11.8, artifact installation
CUDA driver 11.7
Unknown NVIDIA driver

Libraries:
- CUBLAS: 11.11.3
- CURAND: 10.3.0
- CUFFT: 10.9.0
- CUSOLVER: 11.4.1
- CUSPARSE: 11.7.5
- CUPTI: 18.0.0
- NVML: missing

Toolchain:
- Julia: 1.8.5
- LLVM: 13.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0, 7.1, 7.2
- Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80, sm_86

1 device:
  0: NVIDIA GeForce GTX 1070 (sm_61, 7.068 GiB / 8.000 GiB available)
```

**Comment by vchuravy** [comment]
`CuDeviceArray` is indeed not intended to be constructed directly. It's memory needs to be backed by either a allocation that happened outside the kernel, or shared memory.

> To be able to construct mutable, fixed-length, non-shared arrays inside of a kernel.

What you want is probably something like a stack array in C? With a lot of care you can use a MArray from StaticArrays.jl, but it is often better to express the problem using `SArray` (static-sized non-mutable arrays) since MArray on the GPU heavily depends on escape analysis.

**Comment by maleadt** [comment]
Yeah this is what StaticArrays.jl is for.
