### ISSUE TITLE
Insufficient coverage of CuArrays in the documentation

### ISSUE THREAD

**Issue by emojjon** [JuliaGPU/CUDA.jl#1901]
This issue is about the documentation, so it would be good if it could be labelled with _documentation_.

**Description**

In [the documentation](https://cuda.juliagpu.org/stable/usage/overview/#The-CuArray-type) it says 

> The CuArray type is an essential part of the toolchain. Primarily, it is used to manage GPU memory, and copy data from and back to the CPU

Leaving apart whether it really is the CPU we copy data to or from, I can see that creating a CuArray from an Array would copy the latter's data to GPU memory. It is then not mentioned anything about how one uses CuArrays to copy data back to the CPU, nor is it treated in the code example.

I suspect this is because `CuArrays.jl` used to be a separate package and presumably you could read more about it in _its_ documentation. Seeing as this is no longer the case and accessing the documentation seems to require one to log into gitlab, I think that this should be explained in the CUDA documentation. In general it seems like a lot of basic, useful information about CuArrays is missing (or is hard to navigate to?). I suspect that just inserting parts of the old `CuArrays.jl` documentation would alleviate the problem.

**How to reproduce**

Make sure you do not know how CuArrays work beforehand! Go to [the documentation](https://cuda.juliagpu.org/stable/usage/overview/#The-CuArray-type) and observe the epiphany you're not having!

**Version Information**

I've tried different versions of Julia and several of its packages but it doesn't seem to affect the current online documentation of CUDA. Still:

```
versioninfo()
```
```
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 72 × Intel(R) Xeon(R) CPU E5-2697 v4 @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, broadwell)
  Threads: 1 on 72 virtual cores
```
```
CUDA.versioninfo()
```
```
CUDA toolkit 11.7, artifact installation
NVIDIA driver 525.116.3, for CUDA 12.0
CUDA driver 12.0

Libraries: 
- CUBLAS: 11.10.1
- CURAND: 10.2.10
- CUFFT: 10.7.2
- CUSOLVER: 11.3.5
- CUSPARSE: 11.7.3
- CUPTI: 17.0.0
- NVML: 12.0.0+525.116.3
- CUDNN: 8.30.2 (for CUDA 11.5.0)
- CUTENSOR: 1.4.0 (for CUDA 11.5.0)

Toolchain:
- Julia: 1.8.5
- LLVM: 13.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0, 7.1, 7.2
- Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80, sm_86

3 devices:
  0: Quadro RTX 8000 (sm_75, 47.207 GiB / 48.000 GiB available)
  1: Quadro RTX 8000 (sm_75, 47.451 GiB / 48.000 GiB available)
  2: Quadro RTX 8000 (sm_75, 529.375 MiB / 48.000 GiB available)
```

**Comment by maleadt** [comment]
> Make sure you do not know how CuArrays work beforehand! Go to [the documentation](https://cuda.juliagpu.org/stable/usage/overview/#The-CuArray-type) and observe the epiphany you're not having!

You're looking at the wrong section: this is the 'Overview' part of the docs, which is intended to briefly introduce things. You should check out the 'Array programming' section right below: https://cuda.juliagpu.org/stable/usage/array/.

**Comment by emojjon** [comment]
OK, I see. This is admittedly the section I was asking for. What happened was that I:

1. read Usage>Overview>Arrays
2. looked at the end for a more complete reference, found and read API reference>Array programming (one sentence)
3. felt unsatisfied

While my original complaint was unfounded, I would still recommend a "read more" link to Usage>Arrays at the bottom of Usage>Overview>Arrays and API reference>Array programming. Perhaps the latter should be scrapped altogether (API reference gives the impression of something a bit more substantial) and the sentence moved to one of the other two places.

Now, that I have read more about `CuArray`, can I ask: Is it a new thing that you can do logical indexing on a `CuArray` without it reverting to CPU operations? I seem to recall that I tried something very much like it a year ago or so without success.

Does the logical Array have to have the exact same dimensions as the `CuArray` or does it do some form of broadcasting (otherwise it should)?

Anyway, thanks for a quick answer (even though I felt a bit silly about missing the section when I read it)!

**Comment by maleadt** [comment]
I'll add a pointer to the section. I realize that documentation is a bit of a weak point, any help here would be greatly appreciated!

> Is it a new thing that you can do logical indexing on a `CuArray` without it reverting to CPU operations? I seem to recall that I tried something very much like it a year ago or so without success.

It has been supported for quite a while, yeah 🙂  https://github.com/JuliaGPU/CuArrays.jl/pull/290
