### ISSUE TITLE
Disable 'No CUDA-capable device found' error log

### ISSUE THREAD

**Issue by simonbyrne** [JuliaGPU/CUDA.jl#1955]
**Is your feature request related to a problem? Please describe.**

I'm using a HPC system, some nodes of which have GPUs attached. If I request a job _without_ GPU resources that happens to be scheduled on a GPU node, then I get the error log mesage
```
┌ Error: No CUDA-capable device found
└ @ CUDA /central/scratch/esm/slurm-buildkite/climacore-ci/2208/depot/default/packages/CUDA/pCcGc/src/initialization.jl:105
```
This is particularly annoying during precompilation, when I can get quite a few of these.

**Describe the solution you'd like**

Either get rid of [this error](https://github.com/JuliaGPU/CUDA.jl/blob/a719eb32e482dcc88657c6d195469b8efbba77bf/src/initialization.jl#L105) (leave it to first use?), or provide an option to disable it.

**Comment by maleadt** [comment]
Hmm, the idea was to move in the opposite direction actually, and ultimately make `__init__` (and thus loading the package) fail if CUDA fails to initialize, e.g., because of a missing device. Making the error visible seemed like a good first step to raise awareness.

That said, given the number of complaints about this, the inability for some downstream packages to switch to package extensions / preferences, and load-time considerations where we may not want `__init__` to perform loads of work, maybe I should reconsider that.

Regardless, the error should not show up during precompilation. That should be easy to fix.

**Comment by simonbyrne** [comment]
In this specific case, we are using a session without a GPU for precompilation: we could switch to one using a GPU if necessary, but it is kind of nice to be able to build without one.

The alternative (requiring a GPU to load CUDA.jl) we could also make work; it would be helpful if we had a small CUDA-detection package (or maybe there already is one?) to determine if a CUDA GPU is available.

**Comment by maleadt** [comment]
> In this specific case, we are using a session without a GPU for precompilation

The quick fix for that is just to use the `precompiling` variable that's already available in `__init__`, and not print a log message if its set. We cannot bail out of `__init__` altogether, because nowadays people may use SnoopPrecompile + a precompile-time workload that actually uses CUDA.jl.

**Comment by simonbyrne** [comment]
We also see it sometimes at runtime, e.g.
https://buildkite.com/clima/climacore-ci/builds/2228#0188bbb7-5575-4999-8429-133e837fdf36/138-140

Having a way to disable it would be very helpful.

**Comment by maleadt** [comment]
> We also see it sometimes at runtime, e.g.
> https://buildkite.com/clima/climacore-ci/builds/2228#0188bbb7-5575-4999-8429-133e837fdf36/138-140

Well, at run-time it's expected, right? If you load CUDA.jl on a system with the CUDA driver, we expect you'll want to use CUDA.jl, and warn about it being nonfunctional.

To avoid that kind of message, we'd have to go all the way back to lazy initialization. Which may be what we want, as I mentioned above.

**Comment by simonbyrne** [comment]
> If you load CUDA.jl on a system with the CUDA driver, we expect you'll want to use CUDA.jl, and warn about it being nonfunctional.

In this case: no, we just happen to have the job scheduled on a machine with GPUs attached, but don't have access to them. I realize it's a bit of an edge case.
