### ISSUE TITLE
Support of Orin GPU from Nvidia ?

### ISSUE THREAD

**Issue by RGerzaguet** [JuliaGPU/CUDA.jl#1966]
Hello there,

First of all, thank you for the incredible work you've done with CUDA and GPUCompiler :)

I recently acquired a Jetson AGX Orin with Ubuntu, and Julia is running smoothly on it (in 1.9). I wanted to deploy GPU applications, but I'm having trouble performing tasks on it. When I try to test CUDA on it, I get a recurring error:

 `CUDA error: device kernel image is invalid (code 300, ERROR_INVALID_SOURCE)
  `

With the following configuration:

    Testing Running tests...
    ┌ Warning: Your Orin GPU (compute capability 8.7) is not fully supported by CUDA 11.4.0.
    │ Some functionality may be broken. Ensure you are using the latest version of CUDA.jl in combination with an up-to-date NVIDIA driver.
    │ If that does not help, please file an issue to add support for the latest CUDA toolkit.
    └ @ CUDA ~/.julia/packages/CUDA/QsM9L/lib/cudadrv/state.jl:238
    ┌ Info: System information:
    │ CUDA runtime 11.4, local installation
    │ CUDA driver 11.4
    │ Unknown NVIDIA driver
    │
    │ CUDA libraries:
    │ - CUBLAS: 11.6.6
    │ - CURAND: 10.2.5
    │ - CUFFT: 10.6.0
    │ - CUSOLVER: 11.2.0
    │ - CUSPARSE: 11.6.0
    │ - CUPTI: 14.0.0
    │ - NVML: missing
    │
    │ Julia packages:
    │ - CUDA.jl: 4.3.2
    │ - CUDA_Driver_jll: 0.5.0+1
    │ - CUDA_Runtime_jll: 0.6.0+0
    │ - CUDA_Runtime_Discovery: 0.2.2
    │
    │ Toolchain:
    │ - Julia: 1.9.1
    │ - LLVM: 14.0.6
    │ - PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0, 7.1, 7.2, 7.3, 7.4
    │ - Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80, sm_86
    │
    │ Environment:
    │ - JULIA_CUDA_USE_BINARYBUILDER: false
    │
    │ 1 device:
    └   0: Orin (sm_87, 52.051 GiB / 61.325 GiB available)
    [ Info: Testing using 1 device(s): 0. Orin (UUID 0f41a476-5904-5aad-b93f-dc0c74d4cfb0)
    [ Info: Running 8 tests in parallel. If this is too many, specify the `--jobs` argument to the tests, or set the JULIA_CPU_THREADS environment variable.
    [ Info: Skipping the following tests: cufft, nvml

And note also that  I have this warning message 

    ┌ Warning: Your Orin GPU (compute capability 8.7) is not fully supported by CUDA 11.4.0.
    │ Some functionality may be broken. Ensure you are using the latest version of CUDA.jl in combination with an up-to-date NVIDIA driver.
    │ If that does not help, please file an issue to add support for the latest CUDA toolkit.
    
that convince me to open this issue :D 

Note that I get similar errors when using artifacts or a local installation. Is this related to the support for Orin? Are there any possible workarounds?

Kudos 
Robin

**Comment by maleadt** [comment]
You need to use CUDA#master, that will resolve the `ERROR_INVALID_SOURCE` error.

EDIT: Oh, looks like https://github.com/JuliaGPU/CUDA.jl/pull/1931 is already part of 4.3.2 which you are using. I'm not actually sure what the issue is then. I'm looking getting some Orin hardware myself, so hopefully I'll be able to debug it then.

**Comment by maleadt** [comment]
Can you post the output of: `ptxas --help | grep gpu-name -A 15`

**Comment by RGerzaguet** [comment]
Hello @maleadt 
Many thanks for the very quick answer.
Not sure if it can help but the output is 

```
--gpu-name <gpu name>                               (-arch)
        Specify name of NVIDIA GPU to generate code for. This option also takes virtual
        compute architectures, in which case code generation is suppressed. This
        can be used for parsing only.
        Allowed values for this option:  'compute_35','compute_37','compute_50',
        'compute_52','compute_53','compute_60','compute_61','compute_62','compute_70',
        'compute_72','compute_75','compute_80','compute_86','compute_87','lto_35',
        'lto_37','lto_50','lto_52','lto_53','lto_60','lto_61','lto_62','lto_70',
        'lto_72','lto_75','lto_80','lto_86','lto_87','sm_35','sm_37','sm_50','sm_52',
        'sm_53','sm_60','sm_61','sm_62','sm_70','sm_72','sm_75','sm_80','sm_86',
        'sm_87'.
        Default value:  'sm_52'.
```

Do not hesitate if you need anything else !

**Comment by maleadt** [comment]
Ah, I see, that's useful. Please try out https://github.com/JuliaGPU/CUDA.jl/pull/1967

**Comment by RGerzaguet** [comment]
It solves the issue 🎉
On my side, everything is fine (all my script runs without issues)
If I run all the CUDA tests, there is still an issue (but to be honest, this is not a problem for me atm ):

```
Expression: Array(d_A \ d_b) ≈ Af \ bf
CUSOLVERError: An internal operation failed (code 7, CUSOLVER_STATUS_INTERNAL_ERROR)
```

(note : it arrives for all tests related to CUSOLVER)

If you need any assistance or additional attempts, please don't hesitate to ask. However, everything works fine on my side.
Many thanks again :)

**Comment by maleadt** [comment]
Great! Thanks for verifying that change.
