### ISSUE TITLE
Memory allocations during in-place sparse matrix-vector multiplication

### ISSUE THREAD

**Issue by albertomercurio** [JuliaGPU/CUDA.jl#1982]
**Describe the bug**

Benchmarking a simple in-place multiplication `mul!(y, A, x)` between a sparse matrix and a dense vector, I noticed some memory allocations, which are obviously absent in the dense case or in the CPU analogues.

**To reproduce**

The Minimal Working Example (MWE) for this bug:

```julia
using LinearAlgebra
using SparseArrays
using BenchmarkTools
using CUDA
CUDA.allowscalar(false)

# Dense case works
A = CUDA.rand(ComplexF64, 1000, 1000)
x = CUDA.rand(ComplexF64, 1000)
y = similar(x)

@btime mul!($y, $A, $x);

11.800 μs (0 allocations: 0 bytes)
```

```julia
A = cu(sprand(ComplexF64, 1000, 1000, 0.01))
x = CUDA.rand(ComplexF64, 1000)
y = similar(x)

@btime mul!($y, $A, $x);

14.600 μs (57 allocations: 1.44 KiB)
```

**Version info**

Details on Julia:

```
# please post the output of:
versioninfo()

Julia Version 1.9.1
Commit 147bdf428cd (2023-06-07 08:27 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 7 on 12 virtual cores
Environment:
  LD_LIBRARY_PATH = /opt/intel/oneapi/mkl/2023.0.0/lib/intel64
  JULIA_NUM_THREADS = 6
```

Details on CUDA:

```
# please post the output of:
CUDA.versioninfo()

CUDA runtime 12.1, artifact installation
CUDA driver 12.0
NVIDIA driver 528.79.0

CUDA libraries: 
- CUBLAS: 12.1.3
- CURAND: 10.3.2
- CUFFT: 11.0.2
- CUSOLVER: 11.4.5
- CUSPARSE: 12.1.0
- CUPTI: 18.0.0
- NVML: 12.0.0+525.104

Julia packages: 
- CUDA: 4.4.0
- CUDA_Driver_jll: 0.5.0+1
- CUDA_Runtime_jll: 0.6.0+0

Toolchain:
- Julia: 1.9.1
- LLVM: 14.0.6
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0, 7.1, 7.2, 7.3, 7.4, 7.5
- Device capability support: sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80, sm_86

1 device:
  0: NVIDIA GeForce GTX 1650 Ti (sm_75, 3.500 GiB / 4.000 GiB available)
```

**Comment by maleadt** [comment]
> ```julia
> 14.600 μs (57 allocations: 1.44 KiB)
> ```

Are these allocations a problem? They are obviously unrelated to the in-place nature multiplication, as the size of the allocations are much smaller than the size of the inputs.

**Comment by albertomercurio** [comment]
The should not be a problem in the single use case. However, I need to implement this function in an interative algorithm, executing `mul!` many times, and the memory allocation increase.

**Comment by maleadt** [comment]
In any case, this is not a bug. There's plenty room of optimization of the host code in CUDA.jl, but that's plain Julia optimization; the allocations here do not relate to the CUSPARSE operation, which is just in place.

If you care greatly about the host-side performance, I'd recommend having a look at `@code_warntype` or use Cthulhu to find type instabilities or other patterns that may cause CPU allocations.
