### ISSUE TITLE
`CUSPARSE.sum_dim1` sums the absolute values of elements

### ISSUE THREAD

**Issue by lpawela** [JuliaGPU/CUDA.jl#1983]
Both functions `sum_dim1` and `sum_dim2` calculate the sums of absolute values of appropriate elements. Is this by design? If this is the case maybe the name should be changed?

**Comment by maleadt** [comment]
cc @albertomercurio @Roger-luo

**Comment by lpawela** [comment]
Just FYI, to solve this I'm using a modified version of these
```julia
function sum_dim1f(A::CUDA.CUSPARSE.CuSparseMatrixCSR{T}; f=identity) where {T}
    function kernel(T, out, dA, f)
        idx = (blockIdx().x-1) * blockDim().x + threadIdx().x
        idx < length(dA.rowPtr) || return
        s = zero(T)
        for k in dA.rowPtr[idx]:dA.rowPtr[idx+1]-1
            s += f(dA.nzVal[k])
        end
        out[idx] = s
        return
    end

    m, n = size(A)
    rowsum = CuVector{T}(undef, m)
    kernel_f = @cuda launch=false kernel(T, rowsum, A, f)

    config = launch_configuration(kernel_f.fun)
    threads = min(n, config.threads)
    blocks = cld(n, threads)
    kernel_f(T, rowsum, A, f; threads, blocks)
    return rowsum
end
```
and similiarly for `sum_dim2f`. Seems to work fine. If the `abs` is in fact needed, mybe something like this could be used?

**Comment by albertomercurio** [comment]
Yes it should be fine i think. Of course if such feature is implemented, we need to insert abs every time we already called these functions.
