### ISSUE TITLE
CuSparseMatrix constructors allocate too much memory?

### ISSUE THREAD

**Issue by ma-sadeghi** [JuliaGPU/CUDA.jl#2015]
I haven't done rigorous profiling, but by monitoring GPU memory usage, it seems that when creating a sparse matrix on GPU, some memory is being allocated, then freed. Here's my pseudo-recipe:

```julia
# Suppose `ijv` contains row/column/value triplets required to create a COO matrix

# Step 1: Move I, J, and V to GPU
I = cu(ijv[1])
J = cu(ijv[2])
V = cu(ijv[3])
# At this stage, GPU memory usage is increased by ~ 2GB

# Step 2: Create a COO matrix on GPU using `ijv` data
A = CuSparseMatrixCOO(I, J, V, shape)
# At this stage, GPU memory usage shows another ~ 2GB jump, but upon calling 
# CUDA.GC.gc() and CUDA.reclaim(); goes back to ~ 2GB.
```

Here's my question: Is there a way to reduce the internal allocation? I need to create a very large sparse matrix on GPU, so every GB counts. In my experience, if the storage requirement of a matrix is X GB, I at least need 1.5-2 X GB available VRAM.

Thanks!

**Comment by ma-sadeghi** [comment]
~~**Update**: I just realized this is not true! The jump in memory usage was because I was evaluating the sparse matrix in the REPL. I'll close this issue and open a new one!~~

**Comment by ma-sadeghi** [comment]
For future reference: Indeed there's a memory surge; To avoid it, need to use `CuVector{Cint}()` instead of `cu()`.

**Comment by maleadt** [comment]
The situation is more complex. The index typevar is actually configurable (and usable with the new generic cuSPARSE APIs), but we currently default to `Cint` for compatibility with the older cuSPARSE APIs: https://github.com/JuliaGPU/CUDA.jl/blob/966974c979a87ba51208cabb5e0645fb2cef33b5/lib/cusparse/array.jl#L184-L215
