### ISSUE TITLE
libLLVM-15jl.so

### ISSUE THREAD

**Issue by StxGuy** [JuliaGPU/CUDA.jl#2018]
Hello, I installed Julia 1.9.2 and CUDA v4.4.0/CUDA_Driver_jll 0.5.0+1/CUDA_Runtime_jll 0.6.0+0 in a fresh installation of Arch Linux that contains NVIDIA driver 535.86.05 and CUDA version 12.2/runtime 12.1. When I try to run simple commands such as:

using CUDA
x = CUDA.randn(128)
y = x.*2

I get a message: could not load library ./julia/artifacts/.../lib/libLLVMExtra-15.so. An ldd on this file returns: libLLVM-15jl.so => not found. I tried removing and reinstalling CUDA, LLVM (6.1.0), GPUArrays (8.8.1), but nothing works. I have libcuda on /usr/lib and this shows in my /etc/ld/so.conf.d/cuda.conf.

I appreciate any help.

**Comment by maleadt** [comment]
Julia 1.9 uses LLVM 14; if you're using LLVM 15 then you're using an unsupported build (e.g. from your distribution). Please try again with Julia from the official webpage.
