### ISSUE TITLE
More prominently document JULIA_CUDA_USE_BINARYBUILDER

### ISSUE THREAD

**Issue by simonbyrne** [JuliaGPU/CUDA.jl#204]
Runtime downloading of artifacts at module `__init__` is a real pain for deployment, especially for parallel workloads. Would it be possible to move the lazy downloading of the artifact to `Pkg.build()`? 

It would also be useful to have a mechanism to save these preferences so that they persist between sessions/versions ([FFTW.jl](https://github.com/JuliaMath/FFTW.jl/blob/master/deps/build.jl) and [MPI.jl](https://github.com/JuliaParallel/MPI.jl/blob/master/deps/build.jl) save their preferences to a file in `.julia/prefs/`, but https://github.com/JuliaLang/Pkg.jl/pull/1835 will hopefully provide a more systematic way to do this).

cc: @vchuravy @jakebolewski

**Comment by maleadt** [comment]
Why not call `CUDA.version()` or something when you install the package? I'd rather not add even more functionality that should really live in Pkg here to support (pretty niche) use cases, the current set-up is complex enough already.

**Comment by maleadt** [comment]
This is now mentioned on the main installation overview docs: https://juliagpu.gitlab.io/CUDA.jl/installation/overview/
