### ISSUE TITLE
Binaries for Jetson

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CUDA.jl#2105]
We shouldn't be using the SBSA binaries, which are incompatible with Jetson.

Ref: https://threedots.ovh/blog/2022/04/cuda-on-nvidia-jetson-just-not-the-same/#comment-1097

**Comment by stemann** [comment]
Related to #1978

**Comment by maleadt** [comment]
Yeah let's close this in favor of https://github.com/JuliaGPU/CUDA.jl/issues/1978
