### ISSUE TITLE
atomic min, max for Float32 and Float64

### ISSUE THREAD

**Issue by ArturPrzybysz** [JuliaGPU/CUDA.jl#2129]
**Is your feature request related to a problem? Please describe.**
Not described to a specific problem. I just think that atomic min and max are very common operations and it would be convenient for developers to have it out of the box. Currently only integers are supported.

**Describe the solution you'd like**
Including atomic min, max for Float32 and Float64 in CUDA.jl interface.

**Comment by maleadt** [comment]
The low level atomic operations, i.e. those prefixed by `atomic_`, only provide what the hardware implements. For a wider set of operations, potentially falling back to a slow CAS loop, you can use the `CUDA.@atomic` macro, which supports `min` just fine:

```julia
julia> function kernel(a)
           CUDA.@atomic a[1] = min(a[1], 1)
           return
       end
kernel (generic function with 1 method)

julia> a = cu([42])
1-element CuArray{Int64, 1, CUDA.Mem.DeviceBuffer}:
 42

julia> @cuda kernel(a)
CUDA.HostKernel for kernel(CuDeviceVector{Int64, 1})

julia> a
1-element CuArray{Int64, 1, CUDA.Mem.DeviceBuffer}:
 1
```
