### ISSUE TITLE
First test for Julia/CUDA with 15 failures

### ISSUE THREAD

**Issue by waywardpidgeon** [JuliaGPU/CUDA.jl#2158]
I have begun testing my new hardware for Julia with CUDA using the introductory tutorial. Quite a few things work for my device like CUDA.fill, CUDA.@sync, @cuda, but the package invocation test CUDA gives some errors. Maybe an expert can pick up from the excerpt  (attached) of the report what is wrong or missing from my installation.  If you need more detail please ask.

I did the testing twice with the same result each time. 

Thanks - Kevin 
waywardpidgeon
[CUDAtest8Nov23.txt](https://github.com/JuliaGPU/CUDA.jl/files/13290321/CUDAtest8Nov23.txt)

**Comment by maleadt** [comment]
You are using a 3-month old version of CUDA.jl; please test the latest version.

**Comment by maleadt** [comment]
Going to close this for lack of response; please open a new issue if you still run into this on the latest master.
