### ISSUE TITLE
High CPU load during GPU syncronization

### ISSUE THREAD

**Issue by anj00** [JuliaGPU/CUDA.jl#2161]
Migrating from CUDA 4.4.1 to 5.0.0 (and 5.1.0) causes 100% CPU load while waiting for GPU results

I run `Win10, Julia 1.9.3, Nvidia 2070`

```
using CUDA
CUDA.device!(0)

function long_gpu_compute(x, num)
   for i = 1:2000000000 x[i % 2 + 1] = num end
   return
end

function f(x) 
    @cuda threads=1 long_gpu_compute(x, 42.0f0)
    return x 
end 

x = cu(rand(Float32, 2))
for i = 1:3
   println("$i **************************")
   @time( begin x_out = f(x); synchronize(blocking = false) end)
end
```
Above is of course minimal artificial code. yet it shows Julia is using a whole CPU core 100% while waiting for the GPU to return (which for multicore CPU might mean 7-9% load of the julia process). 

In my compute server with 5 GPUs and real code the new CUDA translates to about 45% CPU load (up from single digits) with overall about 10-20% more power draw with no corresponding gain in performance (for my setup/processing type with relatively long GPU processing, other algorithms of course can experience different effects). If that is not a bug but a feature: would be great to continue having an option to choose "most performant wait" vs "less performant wait yet with lower CPU load/power draw"

2 years back we had similar issue with migration to CUDA 3.x [here] (https://github.com/JuliaGPU/CUDA.jl/issues/893) :)

**Comment by maleadt** [comment]
This is expected, as it's the default behavior of CUDA. It spins when synchronizing the stream or context.

To change that behavior, you need to configure the appropriate context (here, the device-default primary context) using the `CU_CTX_SCHED_BLOCKING_SYNC` flag. In CUDA.jl, you do so by calling `device!` before everything else:

```julia
using CUDA
device!(0, CUDA.CTX_SCHED_BLOCKING_SYNC)
```

I'm not a fan of this being the default behavior either, but it's how it is, and I don't think CUDA.jl should pick different defaults than CUDA itself.
