### ISSUE TITLE
Add a CuSparseMatrixCOO type

### ISSUE THREAD

**Issue by irhum** [JuliaGPU/CUDA.jl#220]
It appears that the generic `cusparseSpMM` method offered by the C++ CUSPARSE API also allows the usage of a COO matrix (https://docs.nvidia.com/cuda/cusparse/index.html#cusparse-generic-function-spmm) and as of today, CUDA.jl doesn't seem to have a wrapper COO type that would allow higher level access in Julia to the API (kind of like how, since CuSparseMatrixCSR is defined to have a `mul!` method)

How would one go around defining a new `CuSparseMatrixCOO` type to implement similar functionality as well?

**Comment by irhum** [comment]
On a related note, I tried initializing a COO matrix in the format required by the generic function API (https://docs.nvidia.com/cuda/cusparse/index.html#cusparse-generic-spmat-create-coo), but this ended up segfaulting Julia. Any ideas on what might be going wrong here?

```julia
using CuArrays
CuArrays.allowscalar(false)

nnz = 30000
num_rows = 10000
num_cols = num_rows

rows = rand(1:num_rows, nnz)
cols = rand(1:num_cols, nnz)
nnzvals = zeros(Float32, nnz)

M = CUSPARSE.cusparseCreateCoo(CUSPARSE.cusparseSpMatDescr_t(),
                                num_rows,
                                num_cols,
                                nnz,
                                cu(rows),
                                cu(cols),
                                cu(nnzvals),
                                CUSPARSE.CUSPARSE_INDEX_64I,
                                CUSPARSE.cusparseindex('O'),
                                cudaDataType(Float32))

```

**Comment by marius311** [comment]
FWIW I also tried once to create a COO matrix like this and similarly was getting segfaults. I don't recall if its exactly what you did above, but I confirm that when I run your code above with CuArrays 2.2.0 / CUDA version 10.1 I get a segfault. 

Would be great to have a solution to this, since COO is often logically the easiest to construct, and for now I'm having to do that on CPU, convert to CSC, then convert to CuSparseMatrixCSC, which is leaving alot of performance on the table.

**Comment by kshyatt** [comment]
Hello @marius311 and @irhum, I can try to take a crack at this.

**Comment by marius311** [comment]
Fyi I have a `CuSparseMatrixCOO` type working on https://github.com/marius311/CUDA.jl/tree/coo. Currently just the constructor and `switch2csr` implemented, but it'd be pretty trivial to do `cusparseSpMM` as well based on `cusparseSpMV` which is in there. I'm going to wait to see how https://github.com/JuliaGPU/CUDA.jl/pull/351 fleshes out (on which this branch depends), but then could contribute a PR as well, or help with whatever anyone else here may have made progress on too.
