### ISSUE TITLE
`--debug-info=2` makes `NNlibCUDACUDNNExt` precompilation run forever

### ISSUE THREAD

**Issue by prbzrg** [JuliaGPU/CUDA.jl#2225]
When I do  `]add CUDA, cuDNN, NNlib` with `julia --debug-info=2` precompilation for `NNlibCUDACUDNNExt` doesn't finish.
I reported it to NNlib as https://github.com/FluxML/NNlib.jl/issues/558, but I wonder if it's rooted in CUDA. I would appreciate your help to know more about the problem and eventually fix it.

**Comment by maleadt** [comment]
Let's not open issues for what *may* be a CUDA.jl issue; there's a perfectly fine issue on NNlib.jl to track this problem already. The use of `-g2` as mentioned in the CUDA.jl docs only affects run-time code generation, which shouldn't be done from top level anyway.

Having a quick look, Julia seems to be waiting for a task to finish. This is a new phenomenon in 1.10, and there's some docs on how to debug this: https://docs.julialang.org/en/v1/devdocs/precompile_hang/
