### ISSUE TITLE
Test failures on Nvidia GH200

### ISSUE THREAD

**Issue by giordano** [JuliaGPU/CUDA.jl#2227]
Some test fails on Nvidia GH200, according to Tim these are known issues due to new dynamic parallelism API , but I'm opening this ticket to track them.

Here is the full output of `Pkg.test("CUDA")` on this GPU:  [`cuda-tests-gh200.log`](https://github.com/JuliaGPU/CUDA.jl/files/13904429/cuda-tests-gh200.log)

Main issue, repeated several times, is
```
  CUDA error: limit is not supported on this architecture (code 215, ERROR_UNSUPPORTED_LIMIT)
```

**Comment by maleadt** [comment]
Dup of https://github.com/JuliaGPU/CUDA.jl/issues/1846? I don't see new errors in the log.

**Comment by giordano** [comment]
Ah, I searched for "GH200" in the repo but didn't find anything before opening the issue :stuck_out_tongue:

Not mentioned in that page I see
```
  Failed to compile PTX code (ptxas exited with code 255)
  Invocation arguments: --generate-line-info --compile-only --verbose --gpu-name sm_90 --output-file /tmp/jl_HKnQTqFMVs.cubin /tmp/jl_hEHiJKzsJy.ptx
  ptxas /tmp/jl_hEHiJKzsJy.ptx, line 291; fatal   : Unsupported Function 'cudaDeviceSynchronize' on arch 'sm_90' or higher
  ptxas fatal   : Ptx assembly aborted due to errors
```
which I guess is related to #2052
