### ISSUE TITLE
Please add support for older cuda versions (cuda 8 and older)

### ISSUE THREAD

**Issue by superchargez** [JuliaGPU/CUDA.jl#2231]
**Is your feature request related to a problem? Please describe.**

Trying to install this package however getting error: Error: CUDA driver 8.0.0 is not compatible with any supported CUDA toolkit (11.4.4, 11.5.2, 11.6.2, 11.7.1, 11.8.0, 12.0.1, 12.1.1, 12.2.2 or 12.3.1)

**Describe the solution you'd like**

Currently I have old GPU (quadro 600) which has support of cuda till version 8 only and have also installed Visual Studio 2015 professional with compiler x64. **Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64**.

**Describe alternatives you've considered**

If however, older version of CUDA.jl could be installed please guide how to do that without uninstalling currently installed julia (I've julia 1.10 latest right now, and don't want to remove it from system because I have installed a few other packages and it would be bothersome to remove and reinstall them again.)

**Additional context**

If there is a way to use CUDA with my GPU and cuda toolkit version 8, please tell me.

**Comment by maleadt** [comment]
Sorry, that's not going to happen. CUDA 8 was released in 2016; it is sadly not realistic for an open-source project to provide support for such old software. We limit our support to what NVIDIA (publicly) support, which is CUDA 11.4+.
