### ISSUE TITLE
BUG: sortperm! seems to perform much slower than it should

### ISSUE THREAD

**Issue by AhmedSalih3d** [JuliaGPU/CUDA.jl#2293]
For full thread see:

https://discourse.julialang.org/t/how-to-sort-an-array-based-on-another-on-gpu-cuda-efficiently/111693/2

Code to reproduce:

```julia

using CUDA
using BenchmarkTools

function reorder_vectors!(sorted_indices, vec1, vec2, vec3)
    sortperm!(sorted_indices, vec1)
    vec1 .= vec1[sorted_indices]
    vec2 .= vec2[sorted_indices]
    vec3 .= vec3[sorted_indices]
end

### GPU TEST
# Initialize vectors
n = 10_000_000
vec1 = CUDA.rand(n)
vec2 = CUDA.rand(n)
vec3 = CUDA.rand(n)
sorted_indices = CUDA.zeros(Int, n)

# Benchmark memory allocation and execution time
mem_allocated = CUDA.@allocated reorder_vectors!(sorted_indices, vec1, vec2, vec3)
execution_time = @benchmark CUDA.@sync reorder_vectors!($sorted_indices, $vec1, $vec2, $vec3)

println("GPU Memory allocated: $mem_allocated bytes")
display(execution_time)

### CPU Test
vec1 = Array(vec1)
vec2 = Array(vec2)
vec3 = Array(vec3)
sorted_indices = zeros(Int, n)

# Benchmark memory allocation and execution time
mem_allocated  = @allocated reorder_vectors!(sorted_indices, vec1, vec2, vec3)
execution_time = @benchmark reorder_vectors!($sorted_indices, $vec1, $vec2, $vec3)

println("CPU Memory allocated: $mem_allocated bytes")
display(execution_time)
###

```

Results:

![image](https://github.com/JuliaGPU/CUDA.jl/assets/36305327/11326a0b-7e2f-4691-b08b-190d814090e5)

Hope I haven't done something silly :)

Kind regards

**Comment by maleadt** [comment]
This is not the kind of issue I was suggesting in https://discourse.julialang.org/t/how-to-sort-an-array-based-on-another-on-gpu-cuda-efficiently/111693/2?u=maleadt; if anything, it shows that GPU `sort` in isolation performs better than CPU sort. At the very least, the benchmarking problem needs to be cleared up, as it doesn't make sense that adding additional operations speeds up the sort (which is non-lazy).

Right now, this issue doesn't offer any additional information over https://github.com/JuliaGPU/CUDA.jl/issues/937, so closing in favor of that issue.
