### ISSUE TITLE
`@device_code_sass` broken

### ISSUE THREAD

**Issue by eschnett** [JuliaGPU/CUDA.jl#2343]
`@device_code_sass` is broken for me. It does not output anything any more. This is with `CUDA.jl` 5.3.1. Downgrading to version 5.2.0 makes it work again.

I am using CUDA.jl on an x86 system with and A40 Nvidia GPU.

This is my test case:
```
julia> using CUDA
julia> f(r,x,y) = (r[] = x[]+y[]; return)
julia> @device_code_sass @cuda f(CuArray(fill(0.0f0)), CuArray(fill(1.0f0)), CuArray(fill(2.0f0)))
```

**Comment by eschnett** [comment]
This might be related to https://github.com/JuliaGPU/CUDA.jl/pull/2247 @maleadt.

**Comment by maleadt** [comment]
This is probably https://github.com/JuliaGPU/CUDA.jl/issues/2328. Bug in CUDA 12.4 Update 1, worked around on master.

**Comment by eschnett** [comment]
I tried using `CUDA #master` but this didn't resolve the problem. There is still no SASS output and no error message.
