### ISSUE TITLE
Readme says Cuda 11 is supported but also the last version to support it is v4.4

### ISSUE THREAD

**Issue by Zentrik** [JuliaGPU/CUDA.jl#2345]
These seem to be contradictory:

"CUDA.jl currently also requires ... a accompanying NVIDIA driver with support for CUDA 11.0 or newer. 

-    CUDA.jl v4.4 is the last version with support for CUDA 11.0-11.3 (deprecated in v5.0)"

**Comment by maleadt** [comment]
That isn't contradictory. CUDA 11.x works fine on an NVIDIA driver with support for 11.0, because of semantic versioning, hence the "or newer".
