### ISSUE TITLE
Unable to use local CUDA runtime toolkit

### ISSUE THREAD

**Issue by ttsHub** [JuliaGPU/CUDA.jl#2367]
Hi All,

I am trying to use the local CUDA runtime (12.4) toolkit but get the following error.

```julia
└ @ CUDA_Runtime_Discovery C:\Users\mohitt\.julia\packages\CUDA_Runtime_Discovery\ZGnCZ\src\CUDA_Runtime_Discovery.jl:139
┌ Debug: Could not discover CUDA toolkit
│   exception =
│    Could not find library 'nvToolsExt' in your local CUDA installation.
│    Stacktrace:
│      [1] error(s::String)
│        @ Base .\error.jl:35
│      [2] get_library(dirs::Vector{String}, name::String; optional::Bool)
```
I have all the required libraries installed in CUDA toolkit, and CUDA runtime is able to discover them, except for this one. Here [NVTX - NVIDIA Tools Extension Library](https://nvidia.github.io/NVTX/), it is mentioned that NVTX is no longer a compiled library (it is now header-only). This makes sense, as I could not find Nsight NVTX installation option in the NVIDIA CUDA 12.4 installer.

```julia
julia> versioninfo()
Julia Version 1.10.0
Commit 3120989f39 (2023-12-25 18:01 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 16 × 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, tigerlake)
  Threads: 1 on 16 virtual cores
Environment:
  JULIA_DEBUG = CUDA_Runtime_Discovery
  JULIA_DIR = C:\Users\AppData\Local\Programs\julia-1.10.0\lib\julia
  JULIA_IMAGE_THREADS = 4
  JULIA_NUM_THREADS = 1
```

[Post on discourse](https://discourse.julialang.org/t/unable-to-use-local-cuda-runtime-toolkit/113980)

**Comment by maleadt** [comment]
https://github.com/JuliaGPU/CUDA_Runtime_Discovery.jl/commit/3cd282d6453c961bae34bbc73e2fc329a9a5f7ba
