### ISSUE TITLE
How to load CUDA.jl conditional on the computer having a CUDA-compatible GPU?

### ISSUE THREAD

**Issue by jonathan-laurent** [JuliaGPU/CUDA.jl#237]
The following pattern used to be useful to load CuArrays conditional on the computer having a CUDA-compatible GPU:

```
using CUDAapi
if has_cuda()
    try
        using CuArrays
    catch ex
        @warn "CUDA is installed, but CuArrays.jl fails to load" exception=(ex,catch_backtrace())
    end
end
```

What is the new way to do this?

**Comment by Moelf** [comment]
https://juliagpu.gitlab.io/CUDA.jl/installation/conditional/#Scenario-2:-GPU-is-optional-1

is this what you're looking for?

**Comment by jonathan-laurent** [comment]
This is exactly what I was looking for, thanks!
