### ISSUE TITLE
Kron Support for CuSparseMatrixCSC

### ISSUE THREAD

**Issue by ZhongyuXie921** [JuliaGPU/CUDA.jl#2370]
I'm trying to convert my code from CPU implementation to GPU implementation. However, my code require lots of kron products for sparse arrays. I could not find implementation of kron in CUDA.jl. Could you please consider this in the next version? Many thanks

**Comment by maleadt** [comment]
> Could you please consider this in the next version?

It's a good feature request, but this is very unlikely to happen. If you rely on this functionality, it's best to try and implement it yourself. Some pointers: CUSPARSE does not support Kronecker product, so this needs a native implementation. cupy has one: https://github.com/cupy/cupy/blob/4c9821bf219026340e976d090b259e370e3ecddd/cupyx/scipy/sparse/_construct.py#L496-L546.

**Comment by albertomercurio** [comment]
But `kron` product should be already implemented [here](https://github.com/JuliaGPU/CUDA.jl/blob/19a08efa06bcb0b5aa88b3a25bb0b336b6538a9a/lib/cusparse/linalg.jl#L262).

```julia
T = Float32
N = 1000

A = cu(sprand(T, N, N, 2 / N))

kron(A, A)
```

```julia
1000000×1000000 CUDA.CUSPARSE.CuSparseMatrixCSC{Float32, Int32} with 4084441 stored entries:
⎡⣻⣧⣞⡌⡟⠰⣶⡏⠹⡟⡖⣖⣳⣼⣷⣐⢖⡆⣧⡄⢢⣾⎤
⎢⡬⢿⣵⡯⢧⡏⢿⡨⡮⡞⢙⡦⠭⣾⠷⡽⡿⣭⣼⣽⠏⠕⎥
⎢⣶⢟⢬⡏⣯⢫⣳⠊⢿⡹⣶⡻⡕⢿⣻⣶⣿⠯⣳⡻⣼⡚⎥
⎢⡑⣿⣯⡮⣧⣌⢝⢿⣾⣞⣑⣻⢏⣟⣝⣟⢵⣲⢶⢳⣷⡲⎥
⎢⡼⣿⣷⣽⣾⢿⣾⢗⣚⡿⡾⣳⢱⣿⣿⠸⡪⠨⣿⡖⣗⣍⎥
⎢⣯⡦⣷⢫⡭⣻⡴⡏⣏⣿⣿⣖⣻⣕⣿⢝⢿⡶⣧⢟⡿⠌⎥
⎢⢺⣽⡟⡏⢳⣻⣷⡏⢿⢖⣯⡯⣧⣹⡽⣳⣺⣻⣬⣹⣲⣃⎥
⎢⠥⡽⣵⠶⡿⢔⣸⢏⣎⠘⣻⢷⣆⣏⡜⣽⣲⢧⢯⣯⡼⡑⎥
⎢⢞⡓⣹⡟⠫⡳⢷⢻⣷⣧⡛⣽⢷⣷⢾⣘⣱⢯⣧⡻⠿⠇⎥
⎢⢦⣐⢦⠎⠫⠫⣳⡛⢮⣣⢷⣿⣾⢭⡯⡛⣏⡵⣻⣿⣽⢧⎥
⎣⢸⠬⠵⢻⢵⣳⡤⡹⡶⠧⠡⡞⡵⠾⢳⡿⡿⢽⡐⠺⡻⠣⎦
```

**Comment by maleadt** [comment]
Good catch; this should be covered by https://github.com/JuliaGPU/CUDA.jl/pull/1603.

@ZhongyuXie921 Please open a new issue with a MWE, if this is still a problem.
