### ISSUE TITLE
CUSOLVER.heevd! returning Float and not Complex

### ISSUE THREAD

**Issue by NoelAraujo** [JuliaGPU/CUDA.jl#238]
Hello,
I have a piece of code to compute eigendecomposition:
```
using CUDA, CUDA.CUSOLVER, LinearAlgebra

a_GPU = CUDA.rand(ComplexF64,4,4)
A = Array(a_GPU)

f1, f2 = eigen(A);
e1, e2 = CUDA.CUSOLVER.heevd!('V','U',a_GPU);

display(f1)
display(e1)

display(f2)
display(e2)
```
The eigenvectors are Complex, therefore I don't need to show them here.
However, eigenvalues are **Real**:
```
julia> display(f1)
4-element Array{Complex{Float64},1}:
   -0.5689781280312203 + 0.55596931759833im
    -0.352388407356525 - 0.14069005809200708im
 -0.041697581169206285 - 0.4788150292843128im
    2.4053118053272446 + 2.369375221972039im
julia> display(e1)
4-element CuArray{Float64,1,Nothing}:
 -1.4096544583203676
 -0.4565704540469433
  0.5381505718192985
  2.770322029318308
```

 I don't know if I'm doing the wrong syntax, or it actually a bug.
Any help ?

**Comment by maleadt** [comment]
IIUC, `heevd!` computes "the eigenvalues and eigenvectors of a symmetric (Hermitian) matrices", which have real eigenvalues.

**Comment by NoelAraujo** [comment]
I discovered that 'Hermitian part' after posting this message, my mistake - from coding at night without coffee.

But I did not figure out which function to call to solve for Complex Numbers. At Intel MKL Documentation, I should call `geevx`, but I don't know in cuSolver what needs to be done.

**Comment by maleadt** [comment]
@kshyatt you have some thoughts?

**Comment by maleadt** [comment]
@NoelAraujo Did you find out which API call you need? I'm not too familiar with the library myself. But seeing how this isn't a bug, I think I'll close this.
