### ISSUE TITLE
EnzymeCore is an unconditional dependency.

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CUDA.jl#2380]
I just noticed that https://github.com/JuliaGPU/CUDA.jl/pull/2281 also added EnzymeCore as a full dependency, next to it being a weak dependency. That defeats most of the point of it being a package extension. I guess it can just be removed from being a full dependency?

@wsmoses This blocks a 5.3.4 backport release, which shouldn't introduce new dependencies.

**Comment by vchuravy** [comment]
Hm that's the default extension pattern to make things work prior to 1.10

We can drop it of course, but it will gate functionality on that.

**Comment by maleadt** [comment]
> Hm that's the default extension pattern to make things work prior to 1.10

I don't think it is? Pre 1.9 we used Requires, which doesn't require a dependency
https://pkgdocs.julialang.org/v1/creating-packages/#Backwards-compatibility

**Comment by wsmoses** [comment]
I think it should just be removable then?

**Comment by maleadt** [comment]
> Pre 1.9 we used Requires, which doesn't require a dependency

For completeness: https://github.com/JuliaGPU/CUDA.jl/blob/a0b1b8d200d4bfd45a1ac2c553204aeb9090003d/src/initialization.jl#L158-L160
