### ISSUE TITLE
Memory pinning needs more features

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CUDA.jl#242]
I started looking at `unpin`:

```
function unregister(registered, low, high)
    @warn "Actually unregister $(low) -> $(high)"

    intersections = [intersect(registered, Interval{Int}(low, high))...]
    isempty(intersections) && error("Unregistering an unregistered range")
    intersection = first(intersections)
    if first(intersection) > low || last(intersection) < high
        throw(ArgumentError("Unregistering a partially-unregistered range."))
    end
    delete!(registered, intersection)
    @show intersection

    if first(intersection) != low
        push!(registered, Interval{Int}(first(intersection), low))
    end
    if last(intersection) != high
        push!(registered, Interval{Int}(high, last(intersection)))
    end

    @info "Remove $low -> $high"
    display(registered)
    println()
    println()
end
```

However, we can't just unregister anything, it needs to match the originally-requested range. So the pinning needs to change in order to preserve the original ranges, so that we can unregister then when completely unused.

cc @kshyatt

**Comment by maleadt** [comment]
@vchuravy Did you ever benchmark the lazy memory pinning in KernelAbstractions? I wonder if the pinning itself isn't going to take significant time, esp. if we're unlikely to come across the same pinned buffer again.

Wouldn't it be better to create a function a la:
```julia
PinnedArray(args...) = x = Array(args) && Mem.pin(x)
```

... and let the user determine pinning?

**Comment by vchuravy** [comment]
I only benchmarked in the context of ClimateMachine and there we are guaranteed to see the same memory region over and over again. Last time I tried switching to the CUDA.jl pinning something didn't work (but I have completely forgotten what the issue was)
