### ISSUE TITLE
CUDA.Mem.unregister fails with CUDA.jl 5.4 (not with 5.3)

### ISSUE THREAD

**Issue by omlins** [JuliaGPU/CUDA.jl#2452]
It seems like the method `register(::CUDA.HostMemory)` required by `CUDA.Mem.unregister` has been removed.

The error message is the following (observed in the unit tests from ImplicitGlobalGrid.jl):

```julia
  MethodError: no method matching register(::CUDA.HostMemory)
  
  Closest candidates are:
    register(::Type{CUDA.HostMemory}, ::Ptr, ::Integer, ::Any)
     @ CUDA /scratch/snx3000tds/julia/omlins/daint-gpu/packages/CUDA/Tl08O/lib/cudadrv/memory.jl:167
    register(::Type{CUDA.HostMemory}, ::Ptr, ::Integer)
     @ CUDA /scratch/snx3000tds/julia/omlins/daint-gpu/packages/CUDA/Tl08O/lib/cudadrv/memory.jl:167
  
  Stacktrace:
    [1] unregister(args::CUDA.HostMemory)
      @ CUDA.Mem ./deprecated.jl:105
```

**Comment by maleadt** [comment]
This is a typo in the method deprecation. I'd advise moving away from those deprecated functions though.

**Comment by omlins** [comment]
@maleadt : thanks!
>  I'd advise moving away from those deprecated functions though.

Could you tell me how this functionality is exposed in future? Which order functions to be used?

**Comment by maleadt** [comment]
See https://juliagpu.org/post/2024-05-28-cuda_5.4/; the `Mem` submodule has been removed.

**Comment by omlins** [comment]
@maleadt Could you release soon a new version? We keep running into this error here... Thanks!

**Comment by maleadt** [comment]
Sure, there's a couple of PRs I want merged, but I'll tag a release after that.

Isn't it easier to just fix the use of the deprecated function though?
