### ISSUE TITLE
Request: Option to disable the "full GC when under very high memory pressure".

### ISSUE THREAD

**Issue by murrellb** [JuliaGPU/CUDA.jl#2467]
We recently noticed a substantial (over 2x) slowdown when switching to the latest CUDA.jl version for a big complicated Flux model we're working on (no MWE - sorry!). We tracked it down to [this commit](https://github.com/JuliaGPU/CUDA.jl/pull/2421/commits/23b03915a8b7c9ae2780223b0200d64a7ea608af).

With CUDA#a72a133 (the parent) I get consistent, high, GPU usage:
![image](https://github.com/user-attachments/assets/8d38d41d-c4fb-48ea-9793-91d32d4fc279)

But with CUDA#84bb117 I get this:
![image](https://github.com/user-attachments/assets/4c47da79-629b-4cf6-8332-5c34c7eb70de)
and each batch takes a over twice as long.

I know nothing about anything here, but I guess there are some tradeoffs in deciding when to trigger GC, so maybe this commit was expected to cause a slowdown in some cases? If so, it would be neat if there were some way to optionally disable it, recovering the previous behavior.

In case it is relevant, the slowdown was first noticed on a 48gb RTX6000 Ada, and then narrowed to this commit on a 48gb A6000.  Other relevant packages are at `Flux v0.14.19` and `cuDNN v1.3.2`.

**Comment by maleadt** [comment]
That kind of slowdown wasn't expected. Running a full GC a little early may still be worth it though, especially when expecting to block (i.e., when synchronizing the GPU). Because of that, maybe it's worth tuning the heuristic as follows:

```patch
diff --git a/src/memory.jl b/src/memory.jl
index 7d7a80513..b6c99fe6d 100644
--- a/src/memory.jl
+++ b/src/memory.jl
@@ -128,9 +128,13 @@ function maybe_collect(will_block::Bool=false)
   end
   Base.@atomic stats.last_time = current_time

+  # determine the collection type
+  ## only when blocking, we can afford a full GC
+  full_gc = pressure > 0.95 && will_block
+
   # finally, call the GC
   pre_gc_live = stats.live
-  gc_time = Base.@elapsed GC.gc(pressure > 0.9 ? true : false)
+  gc_time = Base.@elapsed GC.gc(full_gc)
   post_gc_live = stats.live
   memory_freed = pre_gc_live - post_gc_live
   Base.@atomic stats.last_freed = memory_freed
```

Can you try that version?

**Comment by murrellb** [comment]
No luck:
<img width="859" alt="image" src="https://github.com/user-attachments/assets/abb1fa4c-fbf6-49aa-96b6-59dafe342a59">

`full_gc = pressure > 0.99 && will_block` does ok:
<img width="571" alt="image" src="https://github.com/user-attachments/assets/c7964adf-0253-4127-b585-5781653d9236">
but I'm not sure if that neuters the positive benefit?

In case it matters: this making those changes upon the 5.4.3 release (current master doesn't run for me - some cuDNN error).

**Comment by maleadt** [comment]
0.99 seems very late indeed, especially because at that point it may be better to just trigger the OOM failure path and do a full reclaim (which also considers, e.g., handle caches and other reclaim hooks that aren't covered by the early collection logic here).

I'll just revert the change for now.
cc @pxl-th, as this change was based on AMDGPU.jl

**Comment by pxl-th** [comment]
> I'll just revert the change for now. cc @pxl-th, as this change was based on AMDGPU.jl

My goal was to prevent crashes on systems where you do compute and render your desktop environment on the same GPU, so yeah, it had an impact on performance.
But since it crashes machine most of the time anyway (if you leave computations running for a long enough time) it makes sense to revert it to help with performance in other cases.

**Comment by murrellb** [comment]
Thanks folks!!
