### ISSUE TITLE
CUDA code does not return when running under VSC Debugging mode

### ISSUE THREAD

**Issue by JuanVargas** [JuliaGPU/CUDA.jl#2558]
Ubuntu 24.04 LTS
VSC 1.95.3
Julia 1.11.1
CUDA 12.6

The code example given in the Flux documentation (NeuralNetInOneMinute) available at

https://fluxml.ai/Flux.jl/stable/guide/models/quickstart/

Works OK under VSC as long as the debugging option is NOT used.
If the debugging option is selected, the code never returns. The failure happens somewhere in this loop:

```

  # Training loop, using the whole data set 1000 times:
  losses = []

  # code in line below does not work under debugger
  #   @showprogress for epoch in 1:1_000
  # try this instead run the  for epoch in 1:1_000.
 # code never ends in VSC under debug mode. 
  for epoch in 1:1_000    
      for (x, y) in loader
          loss, grads = Flux.withgradient(model) do m
              # Evaluate model and loss inside gradient context:
              y_hat = m(x)
              Flux.logitcrossentropy(y_hat, y)
          end
          Flux.update!(optim, model, grads[1])
          push!(losses, loss)  # logging, outside gradient context
      end
  end
````

**Comment by maleadt** [comment]
Looks like a VSCode Debugger issue then? Or why do you think CUDA.jl is to blame?

**Comment by JuanVargas** [comment]
because the VSC debugger works fine with all the other languages I have
tried, It only fails with Julia.

**Comment by maleadt** [comment]
Again, that doesn't point to CUDA.jl. If anything, this is likely just the overhead of interpretation of very compute-intensive code that has been written with compilation in mind. I suggest you open a discussion on Discourse, or file an issue on the VSCode Julia integration repository. Feel free to re-open or file a new issue when you have a CUDA.jl reproducer.

**Comment by JuanVargas** [comment]
will do. Thank you for your comments.

**Comment by JuanVargas** [comment]
BTW, Python, which is also interpretation-heavy, does not have that problem.
