### ISSUE TITLE
UndefVarError: `backend` not defined in `GPUArrays`

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGPU/CUDA.jl#2564]
We are seeing in Flux's cuda CI runs a `UndefVarError: backend not defined in GPUArrays` error
https://buildkite.com/julialang/flux-dot-jl/builds/5197#0193677c-c51b-46fe-b985-d393adee576f/375-655 
Possibly it is a GPUArrays v10.3 problem, but posting here since I think current CUDA.jl release is blocking the upgrade to GPUArrays v11. Can we tag a new CUDA.jl release?

**Comment by maleadt** [comment]
> Can we tag a new CUDA.jl release?

Not right now, no. It will take a couple of weeks, or longer, to iron out the performance issues resulting from the move to KA.jl.


> UndefVarError: backend not defined in GPUArrays

The `backend` function was removed from GPUArrays v11 / GPUArraysCore v0.2. How did you end up with these versions installed?  The latest CUDA.jl does explicitly not support this version: https://github.com/JuliaGPU/CUDA.jl/blob/a1db081cbc3d20fa3cb28a9f419b485db03a250f/Project.toml#L63

**Comment by CarloLucibello** [comment]
This is actually a problem with the way in which tests in Flux work, adding `CUDA` after the environment is loaded
https://github.com/FluxML/Flux.jl/blob/cb76e9d9c56f9ba7695b62a7505db010dbcf4961/test/runtests.jl#L73
which ends up installing incompatible versions of packages. 
I will patch this by adding the compact bound `GPUArraysCore=0.1`.
