### ISSUE TITLE
Non-artifact initialization of CUDA.jl using CUDA 11 fails on Windows

### ISSUE THREAD

**Issue by clintonTE** [JuliaGPU/CUDA.jl#262]
First discussed in the Slack channel. This bug does not affect artifact installations. For a local installation, CUDA.jl looks for `$name_$majorversion` when seeking CUDA files (I think from the code this is only true on Windows?). 

Unfortunately, the latest version of CUDA (11) includes a mix of files with a major release of 10 and 11. In my case, the installation failed on cuSOLVER. You can see which files correspond to which release from the below table, pulled from the CUDA release notes:

CUDA Runtime (cudart) | 11.0.171 | x86_64, POWER, Arm64
-- | -- | --
cuobjdump | 11.0.167 | x86_64, POWER, Arm64
CUPTI | 11.0.167 | x86_64, POWER, Arm64
CUDA Demo Suite | 11.0.167 | x86_64
CUDA GDB | 11.0.172 | x86_64, POWER, Arm64
CUDA Memcheck | 11.0.167 | x86_64, POWER
CUDA NVCC | 11.0.167 | x86_64, POWER, Arm64
CUDA nvdisasm | 11.0.167 | x86_64, POWER, Arm64
CUDA NVML Headers | 11.0.167 | x86_64, POWER, Arm64
CUDA nvprof | 11.0.167 | x86_64, POWER, Arm64
CUDA nvprune | 11.0.167 | x86_64, POWER, Arm64
CUDA NVRTC | 11.0.167 | x86_64, POWER, Arm64
CUDA NVTX | 11.0.167 | x86_64, POWER, Arm64
CUDA NVVP | 11.0.167 | x86_64, POWER
CUDA Samples | 11.0.167 | x86_64, POWER, Arm64
CUDA Compute Sanitizer API | 11.0.167 | x86_64, POWER, Arm64
CUDA cuBLAS | 11.0.0.191 | x86_64, POWER, Arm64
**CUDA cuFFT** | **10.1.3.191** | **x86_64, POWER, Arm64**
**CUDA cuRAND** | **10.2.0.191** | **x86_64, POWER, Arm64**
**CUDA cuSOLVER** | **10.4.0.191** | **x86_64, POWER, Arm64**
CUDA cuSPARSE | 11.0.0.191 | x86_64, POWER, Arm64
CUDA NPP | 11.0.0.191 | x86_64, POWER, Arm64
CUDA nvJPEG | 11.0.0.191 | x86_64, POWER, Arm64
Nsight Eclipse Plugins | 11.0.167 | x86_64, POWER
Nsight Compute | 2020.1.0.33 | x86_64, POWER, Arm64
Nsight Windows NVTX | 1.21018621 | x86_64, POWER, Arm64
Nsight Systems | 2020.2.5.8 | x86_64, POWER, Arm64
Nsight Visual Studio Edition (VSE) | 2020.1.0.20115 | x86_64 (Windows)
NVIDIA Linux Driver | 450.36.06 | x86_64, POWER, Arm64
NVIDIA Windows Driver | 451.22 | x86_64 (Windows)

**Comment by maleadt** [comment]
Try adding v11.0 here: https://github.com/JuliaGPU/CUDA.jl/blob/a58ddf7092413a4da6f9bddfb6cbd4d28cdfd8b3/deps/discovery.jl#L155-L164

EDIT: ah no the v10-versioned ones won't be discovered.

**Comment by clintonTE** [comment]
Yeah, from the debug output it successfully found the v11 files without specifically adding v11 to the list- the v10 files are where it fails.

**Comment by charleskawczynski** [comment]
I think I'm running into this too, [here](https://gist.github.com/charleskawczynski/115c21698499aab1b4b71b3e9e80ec41) is a gist of the error I'm seeing.
