### ISSUE TITLE
Strange reordering of struct fields with dynamic parallelism

### ISSUE THREAD

**Issue by andreasKroepelin** [JuliaGPU/CUDA.jl#263]
Values of types that are `isbits` can be given as arguments to kernel functions.
However, I noticed that there is some strange behaviour for structs with many fields.
This should suffice to reproduce the behaviour:
```julia
using CUDA
 
struct Foo
    a::Float32
    b::Float32
    c::Float32
    d::Float32
    e::Float32
    f::Float32
    g::Float32
    h::Float32
end

function child!(x, foo)
    x[1] += foo.a
    x[2] += foo.b
    x[3] += foo.c
    x[4] += foo.d
    x[5] += foo.e
    x[6] += foo.f
    x[7] += foo.g
    x[8] += foo.h
    return
end

function parent!(x, foo)
    @cuda dynamic=true child!(x, foo)
    return
end

function host1()
    x = CUDA.zeros(10)
    @cuda child!(x, Foo(1, 2, 3, 4, 5, 6, 7, 8))
    Array(x)
end

function host2()
    x = CUDA.zeros(10)
    @cuda parent!(x, Foo(1, 2, 3, 4, 5, 6, 7, 8))
    Array(x)
end
```
Now, executing `host1()` yields
```
10-element Array{Float32,1}:
 1.0
 2.0
 3.0
 4.0
 5.0
 6.0
 7.0
 8.0
 0.0
 0.0
```
while `host2()` yields
```
10-element Array{Float32,1}:
 0.0
 0.0
 0.0
 0.0
 1.0
 2.0
 3.0
 4.0
 0.0
 0.0
```
So `host1` which calls `child!` directly works as expected, and `host2` which calls `parent!` which calls `child!` does not.

Remarks:
* I'm aware that `child!` is not how a GPU kernel should look like.
* This problem occurs when storing simulation parameters in a struct and passing a value of that struct as an argument to a kernel.

**Comment by maleadt** [comment]
Interesting, thanks for the clear repro! Generated code looks OK, so this is probably the kernel launch buffers being badly populated. Also reproduces with a simple `NTuple{8,Int}`, as expected.

**Comment by andreasKroepelin** [comment]
For anybody stumbling over this, who also needs to pass many parameters to a kernel using dynamic parallelism:
I ended up defining all parameters as global constants.
This has several drawbacks (most importantly, you can't change them using Revise.jl), but it works.
Just passing them as individual arguments to the kernel did not work either, at least I got an error when using too many arguments.
