### ISSUE TITLE
On the use of @sync during benchmarking in the documentation

### ISSUE THREAD

**Issue by denizyuret** [JuliaGPU/CUDA.jl#279]
The documentation suggests: you need to ensure the GPU is synchronized at the end of every sample, e.g. by calling synchronize(). However this is generally overkill -- the overhead from @sync can be at the same order of magnitude as the actual cost of the kernel call or even higher which makes the measurement highly inaccurate. I usually end up calling @sync every N kernel calls to mitigate this. Also @benchmark generally gives a good estimate without the sync if you ignore the minimum time and use the median.

**Comment by maleadt** [comment]
Interestingly, `@sync` is slower than the coarse `synchronize`, even though it's supposed to be a much more find-grained operation:

```
julia> @benchmark CUDA.synchronize()
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     460.602 ns (0.00% GC)
  median time:      465.556 ns (0.00% GC)
  mean time:        465.714 ns (0.00% GC)
  maximum time:     536.923 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     196

julia> @benchmark CUDA.@sync begin end
BenchmarkTools.Trial: 
  memory estimate:  80 bytes
  allocs estimate:  4
  --------------
  minimum time:     6.855 μs (0.00% GC)
  median time:      9.122 μs (0.00% GC)
  mean time:        15.554 μs (0.00% GC)
  maximum time:     579.770 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     3
```

That said, this would require integration with BenchmarkTools to sync every sample, and not every evaluation. I don't see what to suggest users they can do differently; not suggesting to use `@sync` at all is strictly worse (and I've seen lots of user reports on Discourse or Slack reporting awfully short timings, so no `@benchmark` does not generally give a good estimate without it).

**Comment by denizyuret** [comment]
OK, here are some experiments, the median time seems pretty stable. I typically use the last option to amortize the sync cost for more accuracy in smaller ops.
```
julia> @benchmark c = a * b
BenchmarkTools.Trial: 
  memory estimate:  432 bytes
  allocs estimate:  11
  --------------
  minimum time:     6.592 μs (0.00% GC)
  median time:      543.710 μs (0.00% GC)
  mean time:        488.991 μs (1.33% GC)
  maximum time:     32.963 ms (80.18% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> @benchmark CUDA.@sync c = a * b
BenchmarkTools.Trial: 
  memory estimate:  512 bytes
  allocs estimate:  15
  --------------
  minimum time:     631.551 μs (0.00% GC)
  median time:      837.657 μs (0.00% GC)
  mean time:        1.090 ms (0.74% GC)
  maximum time:     47.150 ms (62.21% GC)
  --------------
  samples:          4523
  evals/sample:     1

julia> @benchmark (c = a * b; synchronize())
BenchmarkTools.Trial: 
  memory estimate:  432 bytes
  allocs estimate:  11
  --------------
  minimum time:     551.096 μs (0.00% GC)
  median time:      562.029 μs (0.00% GC)
  mean time:        580.329 μs (1.64% GC)
  maximum time:     37.431 ms (80.70% GC)
  --------------
  samples:          8584
  evals/sample:     1

julia> @benchmark (for i in 1:100; c = a * b; end; synchronize())
BenchmarkTools.Trial: 
  memory estimate:  42.19 KiB
  allocs estimate:  1100
  --------------
  minimum time:     54.588 ms (0.00% GC)
  median time:      54.735 ms (0.00% GC)
  mean time:        55.377 ms (1.61% GC)
  maximum time:     82.353 ms (34.93% GC)
  --------------
  samples:          91
  evals/sample:     1

```

**Comment by maleadt** [comment]
Are you using the correct `@sync`? It needs to be `CUDA.@sync`. That minimum time seems invalid.

**Comment by denizyuret** [comment]
You are right, I replaced @sync with CUDA.@sync above and results make more sense. Some observations:
1. Without sync, the minimum does not make sense but the median does: ~540 μs
2. With CUDA.@sync the overhead seems to be high: ~300 μs
3. With synchronize() the overhead is still there but much smaller: ~20 μs
4. It is possible to eliminate this overhead using synchronize once every N trials, amortizing its cost.

**Comment by maleadt** [comment]
> With synchronize() the overhead is still there but much smaller: ~20 μs

See the linked PR.

> It is possible to eliminate this overhead using synchronize once every N trials, amortizing its cost.

That requires BenchmarkTools.jl integration. Not sure it's worth the effort to save on 600ns of overhead (on my system).
