### ISSUE TITLE
Faced some errors while testing cuda in Julia

### ISSUE THREAD

**Issue by dnabanita7** [JuliaGPU/CUDA.jl#3]
Specs :
Device : Ubuntu 19.10(eaon)
Driver : 03:00.0 3D controller: NVIDIA Corporation GM108M [GeForce 920MX] (rev a2)
nvidia driver : 440.33.01
nvidia cuda toolkit :10.2
gcc version : 7.4
 
While running ``Pkg.test(["CUDAnative", "CUDAdrv", "CuArrays"])``
I faced few errors which is listed as [CUDAnative errors](https://gist.github.com/Naba7/9757752c6095abb0635598cb5953829c) and [CUDAdrv errors](https://pastebin.com/Q7rrhHZ3). CuArrays passed all the tests.

**Comment by maleadt** [comment]
Both errors are `ERROR_OUT_OF_MEMORY`, so I assume you're just running very close to the limits of your system.

**Comment by dnabanita7** [comment]
Yes. Can it be solved by using parallelization? Is there any methods to parallelize the tests?

**Comment by maleadt** [comment]
Parallelizing the tests would only increase memory usage, since there'd be multiple ones running at the same time. These are fairly low-level tests creating contexts, and there's no way around requiring some memory for those.

**Comment by dnabanita7** [comment]
I rebooted the system and closed some of the tabs. All the tests passed.
