### ISSUE TITLE
CUDA 11 libraries incorrectly looked up in artifact

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CUDA.jl#300]
Our code looks for `cupti64_110.dll`, but it's `cupti64_2020.1.0.dll` nowadays. This is correct in the CUDA_jll, but not updated here.

**Comment by SimonWoods** [comment]
I have several libraries at version 10 in the artifact, but CUDA.jl is looking for version 11.

- cufft64
- cufftw64
- curand64
- cusolver64

**Comment by XingjiaHan** [comment]
https://github.com/tensorflow/tensorflow/issues/43030#issuecomment-725850692

**Comment by maleadt** [comment]
That is not relevant?
