### ISSUE TITLE
API for fast math-like mode

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CUDA.jl#354]
Currently much of the accuracy/performance trade-off flags (to, e.g., CUBLAS and CUDNN) are toggled based on Julia's fast math mode, which is a Bad Thing to enable globally. For CUDNN we can get by doing the "inaccurate"/fast thing by default, i.e. https://github.com/JuliaGPU/CUDA.jl/pull/321, because most ML users won't need the accuracy. But for CUBLAS I don't think CUDA.jl should do the same globally.

Instead of piggybacking on Julia's global fast math mode (`@fastmath` doesn't work here either because it's a syntactical transformation), we should probably have a better API that Flux/Knet then can use to configure the handles.

cc @DhairyaLGandhi @denizyuret

**Comment by maleadt** [comment]
Alternatively CuArray could track fast-mathiness, but it seems hard to make sure that propagates everywhere.

**Comment by DhairyaLGandhi** [comment]
How would CUDA track this? I agree that CUDA shouldn't turn this on globally. How do you see this API looking like? Would it perhaps be a singleton that every effected kernel would accept that would choose the strategy or would that be closer to a flag inside CUDA that Flux sets? In that case, it would have a more far reaching effect, which would be undesirable for other parts of user code.
