### ISSUE TITLE
Bug in julia 1.5.0 I have CUDA 11.0 installed in Ubuntu 18.04

### ISSUE THREAD

**Issue by EddieCueto** [JuliaGPU/CUDA.jl#360]
I have already removed .julia directory and did add CUDA in the package manager.
The package precompiles when I do using CUDA but when I use any command for example CUDA.version() the package fails.

This is the complete error message:

julia> CUDA.version()
┌ Warning: Recursion during initialization of CUDA.jl
└ @ CUDA ~/.julia/packages/CUDA/7vLVC/src/initialization.jl:41
┌ Error: Could not initialize CUDA
│   exception =
│    CUDA error (code 999, CUDA_ERROR_UNKNOWN)
│    Stacktrace:
│     [1] throw_api_error(::CUDA.cudaError_enum) at /home/eddie/.julia/packages/CUDA/7vLVC/lib/cudadrv/e$
ror.jl:103
│     [2] __configure__(::Bool) at /home/eddie/.julia/packages/CUDA/7vLVC/src/initialization.jl:96
│     [3] (::CUDA.var"#609#610"{Bool})() at /home/eddie/.julia/packages/CUDA/7vLVC/src/initialization.jl$
29
│     [4] lock(::CUDA.var"#609#610"{Bool}, ::ReentrantLock) at ./lock.jl:161
│     [5] _functional(::Bool) at /home/eddie/.julia/packages/CUDA/7vLVC/src/initialization.jl:26
│     [6] functional(::Bool) at /home/eddie/.julia/packages/CUDA/7vLVC/src/initialization.jl:19
│     [7] libcuda() at /home/eddie/.julia/packages/CUDA/7vLVC/src/initialization.jl:50
│     [8] (::CUDA.var"#676#cache_fptr!#7")() at /home/eddie/.julia/packages/CUDA/7vLVC/lib/utils/call.jl:
31
│     [9] macro expansion at /home/eddie/.julia/packages/CUDA/7vLVC/lib/utils/call.jl:39 [inlined]
│     [10] macro expansion at /home/eddie/.julia/packages/CUDA/7vLVC/lib/cudadrv/libcuda.jl:28 [inlined]
│     [11] macro expansion at /home/eddie/.julia/packages/CUDA/7vLVC/lib/cudadrv/error.jl:108 [inlined]
│     [12] cuDriverGetVersion(::Base.RefValue{Int32}) at /home/eddie/.julia/packages/CUDA/7vLVC/lib/utils
/call.jl:93
│     [13] version() at /home/eddie/.julia/packages/CUDA/7vLVC/lib/cudadrv/version.jl:10
│     [14] top-level scope at REPL[3]:1
│     [15] eval(::Module, ::Any) at ./boot.jl:331
│     [16] eval_user_input(::Any, ::REPL.REPLBackend) at /buildworker/worker/package_linux64/build/usr/sh
are/julia/stdlib/v1.5/REPL/src/REPL.jl:134
│     [17] repl_backend_loop(::REPL.REPLBackend) at /buildworker/worker/package_linux64/build/usr/share/j
ulia/stdlib/v1.5/REPL/src/REPL.jl:195
│     [18] start_repl_backend(::REPL.REPLBackend, ::Any) at /buildworker/worker/package_linux64/build/usr
/share/julia/stdlib/v1.5/REPL/src/REPL.jl:180
│     [19] run_repl(::REPL.AbstractREPL, ::Any; backend_on_current_task::Bool) at /buildworker/worker/pac
kage_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:292
│     [20] run_repl(::REPL.AbstractREPL, ::Any) at /buildworker/worker/package_linux64/build/usr/share/ju
lia/stdlib/v1.5/REPL/src/REPL.jl:288
│     [21] (::Base.var"#806#808"{Bool,Bool,Bool,Bool})(::Module) at ./client.jl:399
│     [22] #invokelatest#1 at ./essentials.jl:710 [inlined]
│     [23] invokelatest at ./essentials.jl:709 [inlined]
│     [24] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:383
│     [25] exec_options(::Base.JLOptions) at ./client.jl:313
│     [26] _start() at ./client.jl:506
└ @ CUDA ~/.julia/packages/CUDA/7vLVC/src/initialization.jl:99
ERROR: AssertionError: CUDA.jl did not successfully initialize, and is not usable.
Stacktrace:
 [1] libcuda() at /home/eddie/.julia/packages/CUDA/7vLVC/src/initialization.jl:50
 [2] (::CUDA.var"#676#cache_fptr!#7")() at /home/eddie/.julia/packages/CUDA/7vLVC/lib/utils/call.jl:31
 [3] macro expansion at /home/eddie/.julia/packages/CUDA/7vLVC/lib/utils/call.jl:39 [inlined]
 [4] macro expansion at /home/eddie/.julia/packages/CUDA/7vLVC/lib/cudadrv/libcuda.jl:28 [inlined]
 [5] macro expansion at /home/eddie/.julia/packages/CUDA/7vLVC/lib/cudadrv/error.jl:108 [inlined]
 [6] cuDriverGetVersion(::Base.RefValue{Int32}) at /home/eddie/.julia/packages/CUDA/7vLVC/lib/utils/call.
jl:93
 [7] version() at /home/eddie/.julia/packages/CUDA/7vLVC/lib/cudadrv/version.jl:10
 [8] top-level scope at REPL[3]:1

**Comment by maleadt** [comment]
Please don't just ignore the bug template and/or the documentation: https://juliagpu.gitlab.io/CUDA.jl/installation/troubleshooting/#UNKNOWN_ERROR(999)-1
