### ISSUE TITLE
CUDA.jl fails to find libcudadevrt.a due on a cluster install with multi-arch target

### ISSUE THREAD

**Issue by jakebolewski** [JuliaGPU/CUDA.jl#376]
**Describe the bug**

On a cluster install of CUDA 10.1 and 10.2, libcudadevrt.a is installed under the multiarch target location `.../CUDA/10.1/targets/x86_64-linux/lib/libcudadevrt.a`  instead of the assumed search path of `.../CUDA/10.0/lib64/libcudadevrt.a`.  Is this a build/config installation error or should the library initialization lookup also search multi-arch target locations if that is a valid CUDA build / install location?

Ex: 
```
 ┌ Debug: Looking for CUDA device runtime library libcudadevrt.a
│   locations =
│    6-element Array{String,1}:
│     "/central/software/CUDA/10.2"
│     "/central/software/CUDA/10.2/lib"
│     "/central/software/CUDA/10.2/lib64"
│     "/central/software/CUDA/10.2/extras/CUPTI"
│     "/central/software/CUDA/10.2/extras/CUPTI/lib"
│     "/central/software/CUDA/10.2/extras/CUPTI/lib64"
└ @ CUDA ~/.julia/packages/CUDA/7vLVC/deps/discovery.jl:390
┌ Debug: Could not find libcudadevrt
└ @ CUDA ~/.julia/packages/CUDA/7vLVC/deps/bindeps.jl:202
ERROR: Could not find a suitable CUDA installation

[jbolewsk@hpc-23-28 10.2]$ find $(pwd) -type f -name "libcudadevrt.a"
/central/software/CUDA/10.2/targets/x86_64-linux/lib/libcudadevrt.a

[jbolewsk@hpc-23-28 10.2]$ cd /central/software/CUDA/10.1/
[jbolewsk@hpc-23-28 10.1]$ find $(pwd) -type f -name "libcudadevrt.a"
/central/software/CUDA/10.1/targets/x86_64-linux/lib/libcudadevrt.a

[jbolewsk@hpc-23-28 10.1]$ cd /central/software/CUDA/10.0/
[jbolewsk@hpc-23-28 10.0]$ find $(pwd) -type f -name "libcudadevrt.a"
/central/software/CUDA/10.0/lib64/libcudadevrt.a
```

**Comment by maleadt** [comment]
I think `lib`/`lib64` should be symlinks to the target-specific directories, or at least that's how NVIDIA used to package it.

**Comment by jakebolewski** [comment]
It looks like the lib64 -> target symlink is not being generated for this module so this looks to be a module build / packaging error.  Can confirm this works for CUDA 11, thanks for the help.
