### ISSUE TITLE
View with array indices causes memory copy before broadcast

### ISSUE THREAD

**Issue by jgreener64** [JuliaGPU/CUDA.jl#384]
**Describe the bug**

I'm really enjoying the GPU features in Julia, particularly broadcasting.

It seems you have to explicitly move a `view` of a CuArray onto the GPU for broadcasting to be fast.

**To reproduce**

Here I set up a `CuArray`, some indices and a placeholder function to broadcast over.

```julia
using CUDA
using BenchmarkTools
CUDA.allowscalar(false)

n = 1_000
coords = CuArray(rand(Float32, n))
is = repeat(1:n, inner=n)
js = repeat(1:n, outer=n)

f(coord_i, coord_j) = 0.0
```
Now
```julia
coords_i = view(coords, is)
coords_j = view(coords, js)
typeof(coords_i)
```
```
SubArray{Float32,1,CuArray{Float32,1},Tuple{Array{Int64,1}},false}
```
and
```julia
@benchmark f.($coords_i, $coords_j)
```
```
BenchmarkTools.Trial:
  memory estimate:  7.69 KiB
  allocs estimate:  194
  --------------
  minimum time:     6.659 ms (0.00% GC)
  median time:      7.246 ms (0.00% GC)
  mean time:        7.635 ms (0.10% GC)
  maximum time:     25.252 ms (0.00% GC)
  --------------
  samples:          655
  evals/sample:     1
```
which seems rather slow. However if I do
```julia
coords_i = cu(view(coords, is))
coords_j = cu(view(coords, js))
typeof(coords_i)
```
```
SubArray{Float32,1,CuArray{Float32,1},Tuple{CuArray{Int64,1}},false}
```
I get
```julia
@benchmark f.($coords_i, $coords_j)
```
```
BenchmarkTools.Trial:
  memory estimate:  4.75 KiB
  allocs estimate:  118
  --------------
  minimum time:     8.499 μs (0.00% GC)
  median time:      9.101 μs (0.00% GC)
  mean time:        18.177 μs (10.32% GC)
  maximum time:     2.091 ms (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1
```
which seems much better.

<details><summary>Manifest.toml</summary>
<p>

```
CUDA 1.3.0
GPUArrays 5.1.0
GPUCompiler 0.6.0
LLVM 2.0.0
```

</p>
</details>

**Expected behavior**

Ideally I wouldn't need to explicitly move the view onto the GPU, as this code is intended to be generic code in a package that does not depend on CUDA.jl.

**Version info**

Details on Julia:

```
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
```

Details on CUDA:

```
CUDA toolkit 11.0.3, artifact installation
CUDA driver 11.0.0
NVIDIA driver 445.87.0

Libraries:
- CUBLAS: 11.2.0
- CURAND: 10.2.1
- CUFFT: 10.2.1
- CUSOLVER: 10.6.0
- CUSPARSE: 11.1.1
- CUPTI: 13.0.0
- NVML: 11.0.0+445.87
- CUDNN: 8.0.2 (for CUDA 11.0.0)
- CUTENSOR: 1.2.0 (for CUDA 11.0.0)

Toolchain:
- Julia: 1.5.0
- LLVM: 9.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4
- Device support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75

1 device:
  0: GeForce GTX 1660 SUPER (sm_75, 4.442 GiB / 6.000 GiB available)
```

**Additional context**

Looking through the profiling results of the slower run turns up a lot of time in https://github.com/JuliaGPU/CUDA.jl/blob/master/src/subarray.jl#L45-L49:
```julia
# upload the SubArray indices when adapting to the GPU
# (can't do this eagerly or the view constructor wouldn't be able to boundscheck)
# FIXME: alternatively, have users do `cu(view(cu(A), inds))`, but that seems redundant
Adapt.adapt_structure(to::Adaptor, A::SubArray) =
    SubArray(adapt(to, parent(A)), adapt(to, adapt(CuArray, parentindices(A))))
```
In fact the comment led me to work out that I had to move it onto the GPU explicitly for it to be fast.

**Comment by maleadt** [comment]
Since your view contains CPU indices, `SubArray{Float32,1,CuArray{Float32,1},Tuple{Array{Int64,1}},false}`, we should probably just reject calling kernels like that. What happens now, is that the upload to the GPU happens as part of `cudaconvert` when calling the kernel (this is arguably unwanted, since it's costly, and we otherwise never automatically upload when calling kernels):

```julia
julia> typeof(coords_i)
SubArray{Float32,1,CuArray{Float32,1},Tuple{Array{Int64,1}},false}

julia> typeof(cudaconvert(coords_i))
SubArray{Float32,1,CuDeviceArray{Float32,1,CUDA.AS.Global},Tuple{CuDeviceArray{Int64,1,CUDA.AS.Global}},false}
```

So your slow time includes the time it takes to upload the indices.

The problem with rejecting CPU indices is that its currently nontrivial to create a view with GPU indices:
```julia
# slow
julia> typeof(view(coords, is))
SubArray{Float32,1,CuArray{Float32,1},Tuple{Array{Int64,1}},false}

# broken
julia> typeof(view(coords, cu(is)))
ERROR: scalar getindex is disallowed
```

Adapt.jl (what's used by `cu(view(...))`) works around this by using the SubArray constructor:

```julia
julia> typeof(SubArray(coords, cu((is,))))
SubArray{Float32,1,CuArray{Float32,1},Tuple{CuArray{Int64,1}},false}

julia> typeof(cu(view(coords, is)))
SubArray{Float32,1,CuArray{Float32,1},Tuple{CuArray{Int64,1}},false}
```

**Comment by jgreener64** [comment]
Thanks for looking into it and for the report.

If anyone has ideas of how to make a workaround for a package, i.e. call `cu` without importing CUDA.jl, let me know. `coords` is available (on CPU or GPU) so it might be possible to extract the type and do something with it.

**Comment by maleadt** [comment]
We should probably specialize `view` here.

**Comment by jgreener64** [comment]
Great, thanks a lot.
