### ISSUE TITLE
Can't precompile CUDA.jl on Kubuntu 20.04

### ISSUE THREAD

**Issue by protogeezer** [JuliaGPU/CUDA.jl#396]
The issue seems to be that the package manager is installing CUDA 0.1
2019 HP laptop
Julia 1.5.1
NVidia Driver 440.1 CUDA 10.2
GTX 1650 (Compute 7.5)
================
julia> using CUDA
[ Info: Precompiling CUDA [052768ef-5323-5732-b1bb-66c8b64840ba]
ERROR: LoadError: LoadError: LoadError: UndefVarError: AddrSpacePtr not defined
================
Please let me know if there is anything more I can do to help.
Stephen

**Comment by maleadt** [comment]
You probably have another package holding back CUDA 1.x. Try explicitly installing a newer version and look at the error.

Please format your bug report next time. And since this isn't a bug, it's better to use Discourse or Slack for such support questions.
