### ISSUE TITLE
CuPtr should be Ptr in cudnnGetDropoutDescriptor

### ISSUE THREAD

**Issue by denizyuret** [JuliaGPU/CUDA.jl#397]
https://github.com/JuliaGPU/CUDA.jl/blob/892e649670781e1119ae4d54caf548a4a8c4de40/lib/cudnn/libcudnn.jl#L1355

**Comment by maleadt** [comment]
And `states` should be a `CuPtr`, right? Feel free to directly edit this, both in `libcudnn.jl` and in the `pointer.json` (used during wrapper generation).

**Comment by denizyuret** [comment]
I cannot seem to locate the pointer.json file. Can you explain how wrappers are generated so my fixes don't disappear when we generate wrappers for the next cudnn version? I found another issue with `cudnnMultiHeadAttnForward` at libcudnn.jl:1991 -- the first two pointers should be `CuPtr`s.

**Comment by vchuravy** [comment]
> I cannot seem to locate the pointer.json file.

https://github.com/JuliaGPU/CUDA.jl/blob/master/res/wrap/pointers.json and https://github.com/JuliaGPU/CUDA.jl/tree/master/res/wrap has docs.
