### ISSUE TITLE
Tag for LLVM 3?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaGPU/CUDA.jl#412]
https://github.com/JuliaGPU/CUDA.jl/blob/master/Project.toml#L38 master seems to support LLVM 3 while https://github.com/JuliaGPU/CUDA.jl/blob/v1.3.3/Project.toml the latest release does not and this gives issues with trying to use KernelAbstractions.jl + DataStructures v0.18

**Comment by maleadt** [comment]
CUDA#master is currently very breaking, so I don't intend to release anything soon. Besides, the next release is probably going to be 1.6 only, so no users are going to be able to use it for months.

Why do you need LLVM 3? No package depends on it?

**Comment by ChrisRackauckas** [comment]
>Why do you need LLVM 3? No package depends on it?

KernelAbstractions.jl seems to not allow LLVM 2. @vchuravy  https://github.com/JuliaGPU/KernelAbstractions.jl/blob/v0.3.3/Project.toml#L19

**Comment by vchuravy** [comment]
Fixed by KA 0.4
