### ISSUE TITLE
Prevent CUDA.@cufunc to transform the type's Int parameter to Int32.

### ISSUE THREAD

**Issue by N5N3** [JuliaGPU/CUDA.jl#420]
At present `CUDA.@cufunc` transform all the Int in the function definition, including the `Int` parameter of type like `SMatix{3,3,T,9} where T`(`StaticArrays.jl` only allow Int parameter to define the size.)

As a result, if we want tranform a `NTuple{9,T}` to `SMatix{3,3,T,9}`, we have to predefine the `const type1{T} = SMatix{3,3,T,9}` outside the `CUDA.@cufunc`ed function, or write `SMatix{Int(3),Int(3),T,Int(9)}`.

Since the Type's parameter is only used during compile, such transformation could be eliminated for better compatibility?

Possible solution: insert another postwork before the present one to preserve the `Int`s in `Expr(:curly)` by replacing `n` with `Int(n)` if `n isa Int`

**Comment by maleadt** [comment]
`@cufunc` is gone now.
