### ISSUE TITLE
InitError: Cannot use memory pool 'binned' when CUDA.jl was precompiled for memory pool 'split'.

### ISSUE THREAD

**Issue by jonathan-laurent** [JuliaGPU/CUDA.jl#446]
I got the following error when using my AlphaZero.jl package with CUDA v1.3.3:

```
InitError: Cannot use memory pool 'binned' when CUDA.jl was precompiled for memory pool 'split'.
```

Does this mean that it is no longer possible to alternate between different types of memory pools by running the same program with different values for `JULIA_CUDA_MEMORY_POOL`?

**Comment by maleadt** [comment]
Correct, you need to precompile again. This as part of the (ongoing) effort to speed up the memory allocator, and make the `alloc` function somewhat simpler. The whole idea of multiple memory pools is hopefully going away at some point too, we just need one reasonably fast implementation (if necessary tunable).
