### ISSUE TITLE
New version not available yet?

### ISSUE THREAD

**Issue by VarLad** [JuliaGPU/CUDA.jl#452]
I can't use CUDA.jl. 
![Screenshot from 2020-09-28 17-38-25](https://user-images.githubusercontent.com/51269425/94430541-b86e2f00-01b1-11eb-9e90-2338bbf2635a.png)
![Screenshot from 2020-09-28 17-42-20](https://user-images.githubusercontent.com/51269425/94430731-03884200-01b2-11eb-8656-920f9d7bf7fe.png)
![Screenshot from 2020-09-28 17-43-06](https://user-images.githubusercontent.com/51269425/94430832-1ef34d00-01b2-11eb-843a-3b92850c8911.png)
Any idea when the update will support my version of cuda?

**Comment by maleadt** [comment]
Working on it, expect a release today or tomorrow.

**Comment by VarLad** [comment]
Great! 
I hope it comes along fast, the update.
