### ISSUE TITLE
Missing dispatch for indexing of reshaped arrays

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaGPU/CUDA.jl#556]
```julia
x = cu(rand(8))
W = @view p[reshape(1:4,2,2)]
W' # fails
```

This is because `W` is a SubArray`. However, the other method works:

```julia
x = cu(rand(8))
W = reshape(@view(p[1:4]),2,2)
W'
```

This is different from Array semantics:

```julia
x = rand(8)
W = reshape(@view(x[1:4]),2,2)
W'

x = rand(8)
W = @view x[reshape(1:4,2,2)]
W'
```

where the latter is more optimized with BLAS due to some of @mbauman 's fanciness.

**Comment by maleadt** [comment]
What do you expect here exactly? `@view x[reshape(1:4,2,2)]` is a non-contiguous SubArray, both on the CPU and the GPU, because of the indices. Calling transpose on that falls back to the generic implementation on the CPU, and can't possibly work on the GPU because of https://github.com/JuliaGPU/Adapt.jl/issues/21 once again.

**Comment by ChrisRackauckas** [comment]
It's contiguous:

```julia
julia> x = reshape(1:100,10,10)
10×10 reshape(::UnitRange{Int64}, 10, 10) with eltype Int64:
  1  11  21  31  41  51  61  71  81   91
  2  12  22  32  42  52  62  72  82   92
  3  13  23  33  43  53  63  73  83   93
  4  14  24  34  44  54  64  74  84   94
  ⋮                   ⋮
  7  17  27  37  47  57  67  77  87   97
  8  18  28  38  48  58  68  78  88   98
  9  19  29  39  49  59  69  79  89   99
 10  20  30  40  50  60  70  80  90  100

julia> @view x[reshape(1:4,2,2)]
2×2 view(::UnitRange{Int64}, [1 3; 2 4]) with eltype Int64:
 1  3
 2  4
```

**Comment by maleadt** [comment]
It may be in practice, but `view` with indices like that cannot be detected as such:

```
julia> W = @view x[reshape(1:4,2,2)]
2×2 view(::UnitRange{Int64}, [1 3; 2 4]) with eltype Int64:
 1  3
 2  4

julia> ans isa Base.FastContiguousSubArray
false
```

vs

```
julia> W = @view x[1:4]
4-element view(::UnitRange{Int64}, 1:4) with eltype Int64:
 1
 2
 3
 4

julia> ans isa Base.FastContiguousSubArray
true
```

**Comment by ChrisRackauckas** [comment]
I think I can work around it: https://github.com/SciML/DiffEqFlux.jl/pull/451

**Comment by ChrisRackauckas** [comment]
Note that on CPUs, that other form is treated as a contiguous array by BLAS via https://github.com/JuliaLang/julia/pull/34729

**Comment by maleadt** [comment]
That's a good reference, thanks. I'm wary to copy it here though, because these unions have a tendency of wrecking package import latency...

**Comment by maleadt** [comment]
The original MWE here seems to work now.
