### ISSUE TITLE
c[3:4]=0 leads to exception

### ISSUE THREAD

**Issue by denizyuret** [JuliaGPU/CUDA.jl#580]
CUDA@2.3.0
```
julia> c = CUDA.rand(4,4,4)
julia> c[3:4] = 0
ERROR: a exception was thrown during kernel execution.
       Run Julia on debug level 2 for device stack traces.
```
Followed with subsequent launch failures for other cuda calls.

The same operation with a regular array just results in a regular error.

**Comment by maleadt** [comment]
```
julia> c = rand(4,4,4);

julia> c[3:4] = 0
ERROR: ArgumentError: indexed assignment with a single value to many locations is not supported; perhaps use broadcasting `.=` instead?
```

Exceptions are "regular errors". It's only sticky if you use older hardware.

**Comment by maleadt** [comment]
To elaborate some more: this is a `ptxas` bug on older hardware, pre sm_70: https://github.com/JuliaGPU/GPUCompiler.jl/blob/c32fe166787ba2f20845ff52058d9ff46515c002/src/ptx.jl#L287-L293
I guess you use an older GPU?

**Comment by denizyuret** [comment]
I tried it on a v100 and t4, both post sm_70.  In both cases the next command after the exception (e.g. `println(c)`) gets an exception, but the ones after that start working.

In earlier models, e.g. K80, the exceptions are sticky as you mentioned - I keep getting "illegal instruction" errors no matter how many commands I try.

**Comment by maleadt** [comment]
> In both cases the next command after the exception (e.g. `println(c)`) gets an exception, but the ones after that start working.

Yes, that's the expected behavior. The first is the GPU printing the exception, the second is the CPU detecting an exception happening. Then everything just works again. Do you have any problem with this?

**Comment by denizyuret** [comment]
No I think it is ok, may be worth documenting somewhere if not already.
