### ISSUE TITLE
Allow separate directories for cuda and cudnn

### ISSUE THREAD

**Issue by dsfenn** [JuliaGPU/CUDA.jl#590]
I'm working on a cluster that has `cuda` and `cudnn` installed in different locations. I don't have write permission to these locations, so I can't change how they're laid out. `CUDA.jl` successfully finds the `cuda` location, but it looks in the same place for `cudnn` and thinks it's not installed because it can't find it there. I can't figure out how to change that.

If there is a way to specify a separate `cudnn` directory, I haven't been able to find it. If there isn't, it would be helpful to have.

**Comment by maleadt** [comment]
Make sure those directories are part of the library search path (`LD_LIBRARY_PATH`), which your cluster's module management system probably ought to do. That should do the job. `CUDA_HOME` etc is a common shortcut, but generally libraries and binaries you want to use should just be available on standard paths, and CUDA.jl shouldn't be looking all across the system for them.
