### ISSUE TITLE
Difficulties installing CUDA on Julia 1.6.0 .

### ISSUE THREAD

**Issue by jruiseco** [JuliaGPU/CUDA.jl#591]
When running

`import Pkg; Pkg.add("CUDA")``

I receive this issue.

```
ERROR: Unsatisfiable requirements detected for package GPUArrays [0c68f7d7]:
 GPUArrays [0c68f7d7] log:
 ├─GPUArrays [0c68f7d7] has no known versions!
 └─found to have no compatible versions left with CUDA [052768ef]
   └─CUDA [052768ef] log:
     ├─possible versions are: 0.1.0-2.3.0 or uninstalled
     └─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-2.3.0
```

I have tried wiping out every tangentially related folder I could find, and reinstalling CUDA

**Comment by ali-ramadhan** [comment]
I don't think the latest tagged release of CUDA.jl (v2.3.0) supports Julia 1.6.

You might have better luck with the master branch of CUDA.jl since it includes PR https://github.com/JuliaGPU/CUDA.jl/pull/566

**Comment by maleadt** [comment]
What @ali-ramadhan said.
