### ISSUE TITLE
CUDA 11.2

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CUDA.jl#601]
Among the interesting new features:

```
Stream ordered memory allocator: Added new APIs cudaMallocAsync() and cudaFreeAsync() to enable applications to order memory allocation and deallocation with other work launched into a CUDA stream. Provides significant performance improvements compared to cudaMalloc()/cudaFree(). Introduces the concept of memory pools to provide the application with more control over memory management. Each device has a default memory pool and custom memory pools can be created as needed. 
```

**Comment by qin-yu** [comment]
I'm trying to add and use these in Julia but firstly I want to check `cudaDevAttrMemoryPoolsSupported`. It turns out `cudaDeviceAttr` doesn't have it. If we are updating `/src/device/intrinsics/libcudadevrt_common.jl`, should someone use Clang.jl to update the whole file or can I just add the missing ones to `cudaDeviceAttr` (because it is "manually cherry-picked from the generated wrappers" anyway)?

**Comment by maleadt** [comment]
As I mentioned on Slack, don't look at `/src/device/intrinsics/libcudadevrt_common.jl`. That's a minimal device runtime for on-device usage, nothing like the regular API calls I assume you're trying to perform on the host. For those, look at `/lib/cudadrv/libcuda_common.jl`. Those are generated using the tools from `/res/wrap` -- last I did so was for CUDA 11.0, so regenerating those should give you the device attribute enum you need (look for `CUdevice_attribute_enum` in that file).

**Comment by qin-yu** [comment]
> As I mentioned on Slack, don't look at `/src/device/intrinsics/libcudadevrt_common.jl`. That's a minimal device runtime for on-device usage, nothing like the regular API calls I assume you're trying to perform on the host. For those, look at `/lib/cudadrv/libcuda_common.jl`. Those are generated using the tools from `/res/wrap` -- last I did so was for CUDA 11.0, so regenerating those should give you the device attribute enum you need (look for `CUdevice_attribute_enum` in that file).

Ahh sorry I didn't see your reply so I created issue #637, I just closed it but then realised I still need to generate them. I'll check out `/res/wrap`, thanks! 

> As I mentioned on Slack, don't look at `/src/device/intrinsics/libcudadevrt_common.jl`.

gotcha!

**Comment by maleadt** [comment]
11.2 is supported now, with some experimental stuff landing in https://github.com/JuliaGPU/CUDA.jl/pull/679
