### ISSUE TITLE
similar(reinterpret(T, view(::CuArray, ...))) produces Array instead of CuArray

### ISSUE THREAD

**Issue by simeonschaub** [JuliaGPU/CUDA.jl#602]
It seems like this falls back to the generic implementation for `AbstractArrays` in `Base`, which always produces an `Array`:
```julia
julia> similar(reinterpret(SVector{4,Float32}, view(cu(rand(Float32, 10, 2)), 1:4, :)))
1×2 Array{SArray{Tuple{4},Float32,1,4},2}:
 [2.86328f16, 4.5768f-41, 0.0, 0.0]  [2.93855f16, 4.5768f-41, 2.86328f16, 4.5768f-41]

julia> similar(reinterpret(SVector{4,Float32}, cu(rand(Float32, 4, 2))))
1×2 CuArray{SArray{Tuple{4},Float32,1,4},2}:
 [0.683944, 0.111384, 0.644627, 0.645665]  [0.449726, 0.553998, 0.548373, 0.354193]
```
I think returning a `CuArray` would make more sense here, so generic code can still run on the GPU.

This is using CUDA 2.3.0 on Julia 1.5.3

**Comment by simeonschaub** [comment]
Alternatively, maybe this should be fixed upstream, so `similar(reinterpret(T, ::A), ...)` falls back to `similar(::A, T, ...)`?

**Comment by simeonschaub** [comment]
This should be fixed on Julia nightly, but would it be a good idea to try to fix this for `CuArrays` for older versions as well?

**Comment by maleadt** [comment]
We don't use ReinterpretArray anymore after https://github.com/JuliaGPU/CUDA.jl/pull/498, could you verify this works on master as expected?

**Comment by maleadt** [comment]
So this works with contiguous reinterpred views

```julia
julia> similar(reinterpret(Int32, view(CUDA.rand(2,2), :, 1)))
2-element CuArray{Int32, 1}:
 0
 0

julia> similar(reinterpret(Int32, view(CUDA.rand(2,2), 1, :)))
2-element Vector{Int32}:
 15
  0
```

**Comment by simeonschaub** [comment]
Awesome thanks! Works for me now.
