### ISSUE TITLE
sync_threads() appears to not be sync'ing threads

### ISSUE THREAD

**Issue by michaelghorgan** [JuliaGPU/CUDA.jl#61]
My setup:
GTX 1080 Ti
CUDA v9, driver v396.26
CUDAnative v0.9.1
Julia v1.0.2

I have been experimenting with @maetshju's implementation of CTC loss from [this Flux Pull Request](https://github.com/FluxML/Flux.jl/pull/342).  I noticed that when using multiple threads to execute one of the CUDA kernels, the results differ from single-thread.  After extensive debugging, I discovered that adding `@cuprintf` calls immediately after two of the `sync_threads()` calls causes the multi-threaded code to produce the same results as the single-threaded code.  It appears that the `sync_threads()` calls are not actually sync'ing the threads in this particular instance (and `@cuprintf` seems to have the side-effect of forcing thread synchronization).

Unfortunately, I haven't been able to reproduce this issue in a simple code example, so I have attached my version of the entire CTC implementation with a test case that reproduces the problem: 
[ctc.jl.txt](https://github.com/JuliaGPU/CUDAnative.jl/files/2816256/ctc.jl.txt)

To reproduce:
```
julia> include("ctc.jl")
single-thread intermediate printouts:
thread 1 accum[9] = -inf
thread 1 accum[7] = -inf
thread 1 accum[9] = -inf
thread 1 accum[8] = -3.782628
thread 1 accum[9] = -6.222818
thread 1 grad[7]: 0.665241   accum[7]: -inf
thread 1 grad[8]: -0.829811   accum[8]: -3.782628
thread 1 grad[9]: 0.164570   accum[9]: -6.222818

multi-thread intermediate printouts:
thread 2 grad[8]: 0.090031   accum[8]: -inf
thread 3 grad[9]: 0.244728   accum[9]: -inf
thread 1 accum[9] = -inf
thread 1 accum[7] = -inf
thread 1 accum[9] = -inf
thread 1 accum[8] = -3.782628
thread 1 accum[9] = -6.222818
thread 1 grad[7]: 0.665241   accum[7]: -inf

max grad diff: 9.20e-01
        single-thread grad: -0.82981
        multi-thread grad: 0.09003
```
The lines beginning with "thread" are printouts of intermediate results from the computeBetasAndGrads kernel.  In the multi-thread case, threads 2 and 3 should not be printing out values for `grad` and `accum` (line 168 in ctc.jl) before thread 1 has finished initializing `accum` (line 147).  The maximum difference between the single- and multi-thread gradients is about 0.9.

Then modify `ctc.jl` by uncommenting the two `@cuprintf` calls on lines 152 and 240 ("sync 1" and "sync 2" printouts) and re-run:
```
julia> include("ctc.jl")
single-thread intermediate printouts:
thread 1 accum[9] = -inf
thread 1 accum[7] = -inf
thread 1 accum[9] = -inf
thread 1 accum[8] = -3.782628
thread 1 accum[9] = -6.222818
sync 1 thread: 1
thread 1 grad[7]: 0.665241   accum[7]: -inf
thread 1 grad[8]: -0.829811   accum[8]: -3.782628
thread 1 grad[9]: 0.164570   accum[9]: -6.222818
sync 2 thread: 1
sync 2 thread: 1

multi-thread intermediate printouts:
thread 1 accum[9] = -inf
thread 1 accum[7] = -inf
thread 1 accum[9] = -inf
thread 1 accum[8] = -3.782628
thread 1 accum[9] = -6.222818
sync 1 thread: 1
sync 1 thread: 2
sync 1 thread: 3
thread 1 grad[7]: 0.665241   accum[7]: -inf
thread 2 grad[8]: -0.829811   accum[8]: -3.782628
thread 3 grad[9]: 0.164570   accum[9]: -6.222818
sync 2 thread: 1
sync 2 thread: 2
sync 2 thread: 3
sync 2 thread: 1
sync 2 thread: 2
sync 2 thread: 3

max grad diff: 0.00e+00
        single-thread grad: -0.31767
        multi-thread grad: -0.31767
```

Now thread 1 finishes initializing `accum` before the other threads begin calculating values for `grad`.  The single- and multi-thread gradients are now identical.

So, although I suspect the actual problem is something else, this example does seem to indicate that the `sync_threads()` calls on lines 151 and 239 are simply not working.  

Is a `ccall` within a CUDA kernel guaranteed to be synchronous with respect to the kernel thread?  
Do you have any suggestions for how to debug this further?

Thanks!

**Comment by maleadt** [comment]
Going to assume this was a case of https://github.com/JuliaGPU/CUDA.jl/issues/1746, which is fixed now.
