### ISSUE TITLE
Julia version requirement

### ISSUE THREAD

**Issue by jfimbett** [JuliaGPU/CUDA.jl#619]
Hello

I am not able to install the latest version of CUDA.jl since the Project.toml says the package is only compatible with Julia 1.6 but as far as I know by January 2021 the latest version out there is 1.5.3. 

I apologize if Im missing something, Im receiving the following message

`julia version requirement for package `CUDA [052768ef]` not satisfied`

I can always download the package and overcome that, but I prefer just to `] add`

Thank you in advance

**Comment by maleadt** [comment]
The latest version of CUDA does support 1.5, https://github.com/JuliaGPU/CUDA.jl/blob/e06704da5b3e804249f8a11834b5e311e56d59e4/Project.toml#L44, only the master branch required 1.6. If you do an `add` the resolver should select a compatible version, and never use the master branch unless you've specifically requested it to.
