### ISSUE TITLE
CUDA.jl version and CUDA capability 3 or 5

### ISSUE THREAD

**Issue by finmod** [JuliaGPU/CUDA.jl#627]
The docs does not list the older versions of CUDA.jl that should be installed for use with QUADRO architecture.

Specifically, witch CUDAver should be used with QUADRO GPU and CUDA toolkit 10.1?

**Comment by maleadt** [comment]
Please use Discourse for questions, this is an issue tracker.

CUDA v1.x supports compute capability below 5. But that doesn't have anything to do with a quadro GPU per se, I have a quadro with capability sm_75.
