### ISSUE TITLE
Can someone with push access run the TagBot workflow?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaGPU/CUDA.jl#644]
Now that https://github.com/JuliaRegistries/General/pull/27876 has been merged, can someone with push access go to https://github.com/JuliaGPU/CUDA.jl/actions?query=workflow%3ATagBot and manually run a new `workflow_dispatch` TagBot run?

Normally, this would happen automatically. But since I made https://github.com/JuliaRegistries/General/pull/27876 manually (instead of using Registrator), I don't think it will happen automatically.

cc: @maleadt

**Comment by vchuravy** [comment]
Triggered https://github.com/JuliaGPU/CUDA.jl/actions/runs/481700131

**Comment by DilumAluthge** [comment]
Try it again? The first time failed with a GitHub server error.

**Comment by DilumAluthge** [comment]
Thanks! 

https://github.com/JuliaGPU/CUDA.jl/releases/tag/v2.5.0
