### ISSUE TITLE
about the document of conditional use

### ISSUE THREAD

**Issue by norci** [JuliaGPU/CUDA.jl#689]
in file `docs/src/installation/conditional.md`

What about a generated function? 
https://docs.julialang.org/en/v1/manual/metaprogramming/#Generated-functions

```julia
@generated function to_gpu_or_not_to_gpu(x::AbstractArray)
    if CUDA.functional()
        return :(CuArray(x))
    else
        return :(x)
    end
end

function __init__()
    to_gpu_or_not_to_gpu(ones(2))
end
```

I'm not sure if this code is better?

**Comment by maleadt** [comment]
You cannot use complicated stateful functionality like that in a generated function.
https://docs.julialang.org/en/v1/base/base/#Base.@generated
