### ISSUE TITLE
GPU run out of memory if 2 workers use the same GPU

### ISSUE THREAD

**Issue by norci** [JuliaGPU/CUDA.jl#692]
**Describe the bug**

If I create 2 workers, and use the same GPU.
then run Flux on them.
then 1 of the workers will allocate all the GPU memory quickly.  so there's no memory left, for the 2nd worker.

this only happens in the ccall of CUDA libraries, or CUDNN.

**log**
```
ERROR: LoadError: TaskFailedException:
On worker 3:
CUDNNError: CUDNN_STATUS_INTERNAL_ERROR (code 4)
throw_api_error at /root/.julia/packages/CUDA/wTQsK/lib/cudnn/error.jl:19
cudnnCreate at /root/.julia/packages/CUDA/wTQsK/lib/cudnn/base.jl:9
#614 at /root/.julia/packages/CUDA/wTQsK/lib/cudnn/CUDNN.jl:59 [inlined]
get! at ./iddict.jl:152
handle at /root/.julia/packages/CUDA/wTQsK/lib/cudnn/CUDNN.jl:58
macro expansion at /root/.julia/packages/CUDA/wTQsK/lib/utils/call.jl:121 [inlined]
cudnnGetConvolutionForwardAlgorithmMaxCount at /root/.julia/packages/CUDA/wTQsK/lib/cudnn/conv.jl:62 [inlined]
#cudnnFindConvolutionForwardAlgorithmEx#528 at /root/.julia/packages/CUDA/wTQsK/lib/cudnn/conv.jl:124
#conv!#577 at /root/.julia/packages/CUDA/wTQsK/lib/cudnn/nnlib.jl:103
conv! at /root/.julia/packages/CUDA/wTQsK/lib/cudnn/nnlib.jl:91 [inlined]
#conv#83 at /root/.julia/packages/NNlib/KxOwM/src/conv.jl:91
conv at /root/.julia/packages/NNlib/KxOwM/src/conv.jl:89
Conv at /root/.julia/packages/Flux/goUGu/src/layers/conv.jl:147
applychain at /root/.julia/packages/Flux/goUGu/src/layers/basic.jl:36
Chain at /root/.julia/packages/Flux/goUGu/src/layers/basic.jl:38 [inlined]
```

**Expected behavior**

pass

**Version info**

Details on Julia:

```
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 9 3900X 12-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver2)

```

Details on CUDA:

```
CUDA toolkit 11.1.1, local installation
CUDA driver 11.2.0
NVIDIA driver 460.32.3

Libraries: 
- CUBLAS: 11.3.0
- CURAND: 10.2.2
- CUFFT: 10.3.0
- CUSOLVER: 11.0.1
- CUSPARSE: 11.3.0
- CUPTI: 14.0.0
- NVML: 11.0.0+460.32.3
- CUDNN: 8.0.5 (for CUDA 11.1.0)
- CUTENSOR: missing

Toolchain:
- Julia: 1.5.3
- LLVM: 9.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4
- Device support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75

Environment:
- JULIA_CUDA_USE_BINARYBUILDER: false

1 device:
  0: GeForce RTX 2080 SUPER (sm_75, 32.125 MiB / 7.762 GiB available)
```

**Comment by maleadt** [comment]
That's expected; we have a memory pool that consumes all of the available memory. You can limit it using `JULIA_CUDA_MEMORY_LIMIT=$bytes`, but there's other allocations outside of the memory pool (like CUDNN's, as you see here) we don't control. It's recommended to use multiple _threads_ instead of workers, so that the memory pool can be shared.

**Comment by norci** [comment]
Thanks for your suggestion. I have used `JULIA_CUDA_MEMORY_LIMIT`, it works.

I have tried using multiple threads to run Flux models, but Julia crashed, the error was from CUDA.jl. It seems CUDA.jl is not thread safe.
This has been documented in https://juliagpu.gitlab.io/CUDA.jl/usage/multigpu/#Scenario-3:-One-GPU-per-thread .

I think the best approach is, one cuda stream per thread. But is this implemented in CUDA.jl?

**Comment by maleadt** [comment]
> It seems CUDA.jl is not thread safe.

I have significantly improved that recently; make sure you're using the very latest version, it should work fine.

> I think the best approach is, one cuda stream per thread. But is this implemented in CUDA.jl?

Yes, but only on the master branch.
