### ISSUE TITLE
facing unknown errors while compiling exact similar code for parallelization on CPU

### ISSUE THREAD

**Issue by dnabanita7** [JuliaGPU/CUDA.jl#7]
```
julia> using BenchmarkTools

julia> @btime sequential_add!($y, $x)
  440.219 μs (0 allocations: 0 bytes)

julia> @btime parallel_add!($y, $x)
  464.534 μs (29 allocations: 3.00 KiB)

julia> @btime parallel_add!($y, $x)
  462.620 μs (29 allocations: 3.00 KiB)

julia> versioninfo()
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
```
Here, the time taken by parallel_add() is more than sequential_add(). I am not able to figure out why is this happening.

**Comment by vchuravy** [comment]
How big is your problem size? Parallelization requires setup time which is a constant overhead. SO what happens if you increase the amount of work by 10x? What is your code?

**Comment by dnabanita7** [comment]
Its a simple addition of N = 2^20 numbers. It is in the [docs](https://juliagpu.gitlab.io/CUDA.jl/tutorials/introduction/#A-simple-example-on-the-CPU-1)

**Comment by maleadt** [comment]
The bug tracker isn't a place for these questions, please open a Discourse thread with some more details (implementations of these functions, which GPU, etc) or drop by Slack if you have questions.

**Comment by dnabanita7** [comment]
Its resolved.
