### ISSUE TITLE
Supprt CUDA 11.2 Update 1

### ISSUE THREAD

**Issue by SimonWoods** [JuliaGPU/CUDA.jl#715]
With version 2.6.1 and the latest CUDA toolkit 11.2 installed on Windows 10, `CUDA.functional(true)` gives an error:
`CUDA.jl does not yet support CUDA with nvdisasm 11.2.135`

**Comment by maleadt** [comment]
I'll have a look later this week. Any reason you aren't using the CUDA artifacts?

**Comment by SimonWoods** [comment]
The artifact download hangs for me. I think it's my internet connection, as the download from Nvidia got stuck a couple of times, but I can just click the resume button in Chrome to get it going again.

**Comment by maleadt** [comment]
Try running with `JULIA_PKG_SERVER=""`, sometimes it's the Julia package servers that hang.

**Comment by maleadt** [comment]
Part 1: https://github.com/JuliaPackaging/Yggdrasil/pull/2556
