### ISSUE TITLE
CUBLAS_STATUS_ARCH_MISMATCH

### ISSUE THREAD

**Issue by cchan** [JuliaGPU/CUDA.jl#722]
dup #609

**Comment by maleadt** [comment]
Please put some more effort in when filing issues. Just listing them in de title does not suffice.
Dups of https://github.com/JuliaGPU/CUDA.jl/issues/715 and https://github.com/JuliaGPU/CUDA.jl/issues/609

**Comment by cchan** [comment]
Apologies; I'm currently editing it. ~I'll open a new issue.~ comment on #609
