### ISSUE TITLE
CuSparseMatrixCSC missing lu and interactions with UniformScaling

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaGPU/CUDA.jl#79]
```julia
using CuArrays, LinearAlgebra, SparseArrays, CuArrays.CUSPARSE
CuArrays.allowscalar(false)
nx = 1024
K = Tridiagonal(ones(nx-1), -2*ones(nx), ones(nx-1))
mK = CuSparseMatrixCSC(SparseMatrixCSC{Float32, Int32}(-K));
lu(mK)
mK + I
```

Xref: https://github.com/SciML/OrdinaryDiffEq.jl/issues/1136

**Comment by kshyatt** [comment]
Just tried this again, the `lu(mK)` works but `mK+I` does not.

**Comment by maleadt** [comment]
> `mK+I` does not.

That requires a proper broadcast, because it can change the structure.

I guess this is also a dup of https://github.com/JuliaGPU/CUDA.jl/issues/1372 then?

**Comment by ChrisRackauckas** [comment]
Yes, what's left is a dup.
