### ISSUE TITLE
Slow contiguous view() on a CuArray

### ISSUE THREAD

**Issue by koenvos** [JuliaGPU/CUDA.jl#802]
**Describe the bug**

A straightforward contiguous (large) view on a CuArray takes a long time, and comes with a big CPU allocation.

**To reproduce**

The Minimal Working Example (MWE) for this bug:

```
using BenchmarkTools, CUDA
x = cu(randn(100_000_000));
@btime view(x, 1:100_000_000);
-->  202.740 ms (6 allocations: 762.94 MiB)
```

<details><summary>Manifest.toml</summary>
<p>

CUDA v2.6.2
GPUArrays v6.2.0
GPUCompiler v0.10.0
LLVM v3.6.0

</p>
</details>

**Expected behavior**

You would think this should be almost instantaneous. And it used to be, about 6 months ago.

**Version info**

Details on Julia:
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Program Files\Microsoft VS Code\Code.exe"
  JULIA_NUM_THREADS = 6

Details on CUDA:
CUDA toolkit 11.1.1, artifact installation
CUDA driver 11.1.0
NVIDIA driver 456.71.0
Libraries:
- CUBLAS: 11.3.0
- CURAND: 10.2.2
- CUFFT: 10.3.0
- CUSOLVER: 11.0.1
- CUSPARSE: 11.3.0
- CUPTI: 14.0.0
- NVML: 11.0.0+456.71
- CUDNN: 8.10.0 (for CUDA 11.2.0)
- CUTENSOR: 1.2.2 (for CUDA 11.1.0)
Toolchain:
- Julia: 1.6.0
- LLVM: 11.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
- Device support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80
1 device:
  0: GeForce RTX 2070 (sm_75, 4.183 GiB / 8.000 GiB available)

**Comment by maleadt** [comment]
It's the bounds check that takes a while, but I agree it shouldn't be that slow. I've opened a PR.
