### ISSUE TITLE
Performance issue with Pluto.jl

### ISSUE THREAD

**Issue by zhangcx93** [JuliaGPU/CUDA.jl#815]
The background story is like this:
In order to use a new feature in master, i've been using CUDA.jl#master in my project, and changing the GPUCompiler in Manifest.toml into:
```
[[GPUCompiler]]
deps = ["DataStructures", "ExprTools", "InteractiveUtils", "LLVM", "Libdl", "Logging", "Scratch", "Serialization", "TimerOutputs", "UUIDs"]
git-tree-sha1 = "b6c3b8e2df6ffe0da0b10e2045ce35a3cf618b8a"
repo-rev = "1ecbe42"
repo-url = "https://github.com/JuliaGPU/GPUCompiler.jl.git"
uuid = "61eb1bfa-7361-4325-ad38-22787b887f55"
version = "0.10.1"
```
Because at that moment, the latest commit(24ca901c91128d6cc7ee3f87f6181eab49fcad03) would only run like this.
I've been developing with Pluto.jl all this time.

Everything is fine until i try to update the CUDA dependencies, and i noticed the GPUCompiler is now 0.11.1. Here is the problem:
After the update, running a normal cuda related function in a cell takes very long time to finish and running such function in a for loop, the time consumed would not scale linearly. I mean running it 1 time cost 1s, running it 50 times it take just around 1.s. running 5000 times takes 20s.
And this problem is not there if I just use normal REPL.

**To reproduce**
Start a pluto notebook, containing:

```julia
# the first cell
using CUDA
a = CUDA.rand(2000)
function test(x)
	x[x.>0.1] .= 2
	Nothing
end

# the second cell
test(a)
```
re-submit the second cell several times.

In the older version, the time is shown around 300 us, and in the latest version, it's like 500ms or more.(more than 1000x slower)
In a more complicated case(my real project), the originally running 170ms cell would take 1.2s to finish; but if I loop a lot in there, the slowdown is less obvious.

**Expected behavior**

the performance should be the same as it was in commit 24ca901c91128d6cc7ee3f87f6181eab49fcad03

**Version info**

I tested on latest #master 4e81f3d1f0386324465f10eefd6f74c67a92eb12 there is such slow down
and 24ca901c91128d6cc7ee3f87f6181eab49fcad03 does not

Details on Julia:

```
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
```

Details on CUDA:

```
CUDA toolkit 11.2.2, artifact installation
CUDA driver 11.3.0
NVIDIA driver 465.89.0

Libraries:
- CUBLAS: 11.4.1
- CURAND: 10.2.3
- CUFFT: 10.4.1
- CUSOLVER: 11.1.0
- CUSPARSE: 11.4.1
- CUPTI: 14.0.0
- NVML: 11.0.0+465.89
- CUDNN: 8.10.0 (for CUDA 11.2.0)
- CUTENSOR: 1.2.2 (for CUDA 11.1.0)

Toolchain:
- Julia: 1.6.0
- LLVM: 11.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
- Device support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80

1 device:
  0: NVIDIA GeForce RTX 2080 Ti (sm_75, 8.925 GiB / 11.000 GiB available)
```

**Comment by maleadt** [comment]
If it doesn't happen in the REPL, this looks like a Pluto bug?

Since you have an easy way to compare performance, could you narrow it down to the specific commit that introduced the slowdown? There aren't that many: https://github.com/JuliaGPU/CUDA.jl/compare/24ca901c91128d6cc7ee3f87f6181eab49fcad03...4e81f3d1f0386324465f10eefd6f74c67a92eb12

**Comment by zhangcx93** [comment]
> If it doesn't happen in the REPL, this looks like a Pluto bug?
> 
> Since you have an easy way to compare performance, could you narrow it down to the specific commit that introduced the slowdown? There aren't that many: [24ca901...4e81f3d](https://github.com/JuliaGPU/CUDA.jl/compare/24ca901c91128d6cc7ee3f87f6181eab49fcad03...4e81f3d1f0386324465f10eefd6f74c67a92eb12)

this one make it slow: 87b1f4aa256a290d203ba34d252ba5cd504ccd3f
It's just changing GPUCompiler into 0.11
I guess it's the problem between GPUCompiler and Pluto

**Comment by maleadt** [comment]
Yeah the kernel is getting compiled over and over...

**Comment by maleadt** [comment]
Probably caused by https://github.com/JuliaGPU/GPUCompiler.jl/pull/160.

**Comment by maleadt** [comment]
https://github.com/JuliaGPU/CUDA.jl/commit/e53382b381515d33d2d79735a944a03aef75111e
