### ISSUE TITLE
missing kernel for partialsort

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGPU/CUDA.jl#817]
`partialsort` is a Base's function that can be used to implement what is known as `topk` in pytorch and `maxk` in matlab (except for the fact that is missing a `dim` argument). It would be good to have a kernel here since Base's implementation resorts to scalar indexing:

```julia
julia> using CUDA

julia> x = CUDA.rand(10);

julia> partialsort(x, 1:3)
┌ Warning: Performing scalar operations on GPU arrays: This is very slow, consider disallowing these operations with `allowscalar(false)`
└ @ GPUArrays ~/.julia/packages/GPUArrays/bjw3g/src/host/indexing.jl:58
3-element CuArray{Float32, 1}:
 0.0065999134
 0.10481251
 0.30311054
```

**Comment by maleadt** [comment]
Dup of https://github.com/JuliaGPU/CUDA.jl/issues/93.
