### ISSUE TITLE
Native implementation of sparse arrays

### ISSUE THREAD

**Issue by zhangcx93** [JuliaGPU/CUDA.jl#829]
My current urgent need is to do elementwise broadcasting dot with SparseMatrix in cuda:
```julia
a = CuSparseMatrixCSR(sprand(Float32, 25, 1, 0.3))  # a is essentially a bool sparse vector, converted into this type/shape for demonstration
w = CuSparseMatrixCSR(sprand(Float32, 25, 20, 0.3))
m = a .* w
```
but this is scalar indexing, and also result in dense output.
I did some comparison between cpu and gpu version:

```julia
using CUDA
using CUDA.CUSPARSE
using SparseArrays

CUDA.allowscalar(false)

a = Float32.(rand(Float32, 1, 25) .> 0.7)
sa = sprand(Float32, 1, 25, 0.3)
w = sprand(Float32, 25, 20, 0.3)

#CPU verison:
# matrix mul
m0 = w * w' # sparse output
m = a * w # dense output
m1 = sa * w # sparse output

# broadcast and elementwise mul
m2 = reshape(a, 25, 1) .* w # sparse 2D output
m3 = sparse(reshape(sa, 25, 1)) .* w # sparse 2D output

# GPU version:
cu_a = cu(a)
cu_sa = CuSparseMatrixCSR(sa)
cu_w = CuSparseMatrixCSR(w)
flat_cu_b = cu(Float32.(rand(Float32, 20) .> 0.7)) # dense vector

# matrix mul
cu_m0 = @CUDA.allowscalar cu_w * cu_w' # scalar indexing, dense output
cu_m = @CUDA.allowscalar cu_a * cu_w # scalar indexing, dense output
cu_m1 = @CUDA.allowscalar cu_sa * cu_w # scalar indexing, dense output

cu_m1 =  cu_w * flat_cu_b # dense output  <---- this is the only working mul function works for CuSparseMatrixCSR without scalar indexing
@CUDA.allowscalar cu_w * CuSparseVector(sprand(Float32, 20, 0.3)) # scalar indexing, dense output

# broadcast and elementwise mul
try
    cu_m2 = reshape(cu_a, 25, 1) .* cu_w # Kernel fail to compile
catch
    #GPU compilation of kernel broadcast_kernel(CUDA.CuKernelContext, CuDeviceMatrix{Float32, 1}, Base.Broadcast.Broadcasted{Nothing, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}, typeof(*), Tuple{Base.Broadcast.Extruded{CuDeviceMatrix{Float32, 1}, Tuple{Bool, Bool}, Tuple{Int64, Int64}}, Base.Broadcast.Extruded{CuSparseMatrixCSR{Float32}, Tuple{Bool, Bool}, Tuple{Int64, Int64}}}}, Int64) failed
    #KernelError: passing and using non-bitstype argument
end
cu_m3 = @CUDA.allowscalar CuSparseMatrixCSR(reshape(cu_a, 25, 1)) .* cu_w # scalar indexing, dense output

# other basic operation:
@CUDA.allowscalar cu_w .+ 1. # scalar indexing
nonzeros(cu_w) .+= 1 # this allow me to do .+= and .*=, .=

cu_w1 = CuSparseMatrixCSR(sprand(Float32, 25, 20, 0.3))
try
    cu_w + cu_w1 # add 2 sparse matrix
catch
    # UndefVarError: geam not defined
    # https://github.com/JuliaGPU/CUDA.jl/issues/528
end

# elementwise dot of same size
@CUDA.allowscalar cu_w .* cu_w1 # scalar indexing, dense output


```

**Expected behavior**

All the mentioned functions above are quite common operations, which should work the same as CPU version without fallback to default scalar indexing.
Some should have sparse output but has dense output even with scalar indexing.
All above makes array programming for sparse matrix quite unusable.

**Version info**

Details on Julia:

```
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
```

Details on CUDA:

```
CUDA toolkit 11.2.2, artifact installation
CUDA driver 11.3.0
NVIDIA driver 465.89.0

Libraries:
- CUBLAS: 11.4.1
- CURAND: 10.2.3
- CUFFT: 10.4.1
- CUSOLVER: 11.1.0
- CUSPARSE: 11.4.1
- CUPTI: 14.0.0
- NVML: 11.0.0+465.89
- CUDNN: 8.10.0 (for CUDA 11.2.0)
- CUTENSOR: 1.2.2 (for CUDA 11.1.0)

Toolchain:
- Julia: 1.6.0
- LLVM: 11.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
- Device support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80

1 device:
  0: NVIDIA GeForce RTX 2080 Ti (sm_75, 8.248 GiB / 11.000 GiB available)
```

**Additional context**

Using latest master version of CUDA.jl

What i really want to do is having a sparse bool vector to filter an float sparse matrix along an axis, resulting in a sparse matrix of the same size, with less elements, how can i possibly to that on GPU? all kinds of converting is welcome.

**Comment by zhangcx93** [comment]
well after some search, and reading cuSparse documentation, there is no CUDA native support for many of these operations... but at least the part that fail to compile kernel is a bug.
Is there anyway we could write GPU kernels by hand on CuSparseMatrixCSR like the [CPU version](https://discourse.julialang.org/t/sparsematrix-is-very-slow/36809/6), can you provide a scheme for that?

**Comment by maleadt** [comment]
Correct, for broadcast to work we'd need a native implementation of the sparse array operations (notably indexing), by providing a device-counterpart of host array types (like how `CuDeviceArray` implements device-operations for `CuArray`). CUSPARSE can't help you here, this needs to be a Julia implementation.

**Comment by zhangcx93** [comment]
I read the lastest CUSPARSE doc a bit more, although i don't know how to do cuda programming at all, i found that all level1 function is deprecated(they're used in CUDA.jl), and many useful functions are there in the `Generic API Functions` section.
And all of the function there is only wrapped in `libcusparse.jl`, but not used to implement any methods for CuSparseMatrix.

for https://github.com/JuliaGPU/CUDA.jl/issues/528, it's because the missing function of `geam`, in CUDA doc, i found only `csrgeam2()`, with a mention of `csrgeam()` but nowhere to find.(in `Extra Function Reference` section)

And i found `cusparseSDDMM()` function, which is the only one with Hadamard product, which might help here.

**Comment by maleadt** [comment]
Yeah the generic functionality is pretty new, and we're still supporting CUDA 10.1, so we need to be careful relying on it. But it's definitely the way forward.

But again, those won't help you to broadcast over a sparse array. That requires a native implementation that works in kernels.

**Comment by maleadt** [comment]
https://github.com/JuliaGPU/CUDA.jl/pull/1380
