### ISSUE TITLE
CUDA.abs() on vector input: performance regression compared to CUDAdrv

### ISSUE THREAD

**Issue by anj00** [JuliaGPU/CUDA.jl#839]
Below code runs about 10% slower than using `CUDAnative.abs` and `CUDAdrv` in case the input is a vector (there is only about 1% performance difference in case of matrix input)
```
const threads = 256
function kernel_abs(n, x, y)
    i = (blockIdx().x-1) * blockDim().x + threadIdx().x
    if i <= n
        @inbounds y[i] = CUDA.abs(x[i])
    end
    return
end

function abs!(y, x)
    len = length(x)
    blocks = (len + threads - 1) ÷ threads
    @cuda blocks = blocks, 1 threads = threads kernel_abs(len, x, y)
end

#test setup
Random.seed!(1)
x1 = cu(randn(Float32, (1, 1536)) .+ Float32(0.5))
y1 = similar(x1)

abs!(y1, x1) #warmup
print("add!                       "); 
@btime begin abs!($y1, $x1); synchronize() end
```

with CUDAdrv.jl
`abs!                         18.000 μs (29 allocations: 976 bytes)`
with CUDA.jl
`abs!                         19.900 μs (12 allocations: 288 bytes)`

```
"CUDA"         => v"3.0.2"
"BenchmarkTools"  => v"0.6.0"
```
```
julia> CUDA.versioninfo()
CUDA toolkit 11.2.2, artifact installation
CUDA driver 11.3.0

Libraries:        
- CUBLAS: 11.4.1
- CURAND: 10.2.3
- CUFFT: 10.4.1
- CUSOLVER: 11.1.0
- CUSPARSE: 11.4.1
- CUPTI: 14.0.0
- NVML: missing
- CUDNN: 8.10.0 (for CUDA 11.2.0)
- CUTENSOR: 1.2.2 (for CUDA 11.1.0)

Toolchain:
- Julia: 1.6.0
- LLVM: 11.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
- Device support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80

1 device:
  0: NVIDIA GeForce RTX 2070 (sm_75, 6.847 GiB / 8.000 GiB available
```
```
julia> CUDA.versioninfo()
CUDA toolkit 11.2.2, artifact installation
CUDA driver 11.3.0

Libraries:        
- CUBLAS: 11.4.1
- CURAND: 10.2.3
- CUFFT: 10.4.1
- CUSOLVER: 11.1.0
- CUSPARSE: 11.4.1
- CUPTI: 14.0.0
- NVML: missing
- CUDNN: 8.10.0 (for CUDA 11.2.0)
- CUTENSOR: 1.2.2 (for CUDA 11.1.0)

Toolchain:
- Julia: 1.6.0
- LLVM: 11.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
- Device support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80

1 device:
  0: NVIDIA GeForce RTX 2070 (sm_75, 6.847 GiB / 8.000 GiB available](url)
```

full code (setup + run) is [here](https://1drv.ms/u/s!AkkVaBzPZViciaZHsZLXzcdnQ-_YlQ?e=B6nFZ6) you run it like this
```
C:\Bin\Julia-1.3.1\bin\julia.exe run_kernel_1.3.1_setup.jl
julia run_kernel_1.6.0_setup.jl

C:\Bin\Julia-1.3.1\bin\julia.exe run_kernel_1.3.1.jl
julia run_kernel_1.6.0.jl
```

Julia 1.3.1 setup
```
  [6e4b80f9] BenchmarkTools v0.5.0
  [c5f51814] CUDAdrv v5.0.1
  [be33ccc6] CUDAnative v2.7.0
  [3a865a2d] CuArrays v1.6.0
```

**Comment by maleadt** [comment]
See https://github.com/JuliaGPU/CUDA.jl/issues/838#issuecomment-824706136.

**Comment by anj00** [comment]
Here looks like the problem happened on transition from 2.6 to 3.0 branch
```
3.0.3 : 0.0000206
3.0.2 : 0.0000204
3.0.1 : 0.0000208
3.0.0 : 0.0000209
2.6.3 : 0.0000151
2.6.2 : 0.0000154
2.6.1 : 0.0000159
2.6.0 : 0.0000151
```
Here is the log of bisect (on 3.0 branch)
bad/good
```
27520e60d65e08e50e8c6ce30b2ec322d0fdecb8 : 0.0000207
d719a6f52b5fa11b816b03eec4fe47f059db1764 : 0.0000154
```
Log
```
818b5b78bfcdf07d6332c36b53e5d72e125351db : 0.0000203
1665b72c5cdf9cceb3f0b729c9760daed833aed1 : 0.0000202
1b4ebb20c041fe9e5cad26222df2630d99389e56 : 0.0000205
ff597f4a2661c81ffc4e4f613be5cae8654886e4 : 0.0000160
ff597f4a2661c81ffc4e4f613be5cae8654886e4 : 0.0000145
00333a8ceb31563fc68eb418c70fbc9c8e000622 : 0.0000200
9c0cd5394c8723a41795086ecb514c1f589aade9 : 0.0000149
9a1da4197090f2b6aacf6d8ac2740457ebfc763b : 0.0000143
653bb255b7338dae32fdd1dc7e38d4be575154a8 : 0.0000149
```
```
00333a8ceb31563fc68eb418c70fbc9c8e000622 is the first bad commit
commit 00333a8ceb31563fc68eb418c70fbc9c8e000622
Author: Tim Besard <tim@juliacomputing.com>
Date:   Thu Jan 21 17:24:04 2021 +0100

    Handle blocking during synchronization ourselves.

    That way we can yield to other tasks.

 lib/cudadrv/stream.jl  | 20 +++++++++++++-------
 src/array.jl           |  1 +
 src/utilities.jl       | 14 +++-----------
 test/cudadrv/stream.jl |  3 +++
 test/setup.jl          |  5 ++++-
 5 files changed, 24 insertions(+), 19 deletions(-)
```

**Comment by maleadt** [comment]
If that's the culprit, it's only the call to `synchronize()` that has become slower, not the actual computation. Could you verify by running under a profiler, e.g., `nvprof` or NSight Systems?

**Comment by anj00** [comment]
I probably need help on how exactly to run NSight. I have downloaded it and just run `julia test.jl` in NSight. Here is that I see for "last good commit"

![image](https://user-images.githubusercontent.com/2228878/115882276-e5837700-a44c-11eb-825d-78364361d695.png)


and this is with "first bad"
![image](https://user-images.githubusercontent.com/2228878/115882471-106dcb00-a44d-11eb-8f29-e6d0453abab3.png)


Looks like the cuStreamSyncronize is gone. 

here is is the capture settings
![image](https://user-images.githubusercontent.com/2228878/115881132-b9b3c180-a44b-11eb-8f06-b01451e2e686.png)

**Comment by maleadt** [comment]
> Looks like the cuStreamSyncronize is gone.

Correct, we now query the stream and do the blocking ourselves. That may be a little more expensive, but I'd be surprised if that ever matters in practice. If it does, could you elaborate?

For more info on profiling, see https://juliagpu.github.io/CUDA.jl/dev/development/profiling/#NVIDIA-Nsight-Systems. It's always better to perform a warm-up iteration and only capture a trace without any JIT compilation.

**Comment by anj00** [comment]
So inside checked out dir `CUDA.jl `I run this code (`test.jl`)
```
using Pkg
Pkg.activate(".")

using Printf, Random, CUDA


const threads = 256
function kernel_abs(n, x, y)
    i = (blockIdx().x-1) * blockDim().x + threadIdx().x
    if i <= n
        @inbounds y[i] = CUDA.abs(x[i])
    end
    return
end

function abs!(y, x)
    len = length(x)
    blocks = (len + threads - 1) ÷ threads
    @cuda blocks = blocks, 1 threads = threads kernel_abs(len, x, y)
end

Random.seed!(1)
x1 = cu(randn(Float32, (1, 1536)) .+ Float32(0.5))
y1 = similar(x1)

abs!(y1, x1); synchronize(); #warmup
NVTX.@range "second run" begin
	abs!(y1, x1); 
	synchronize();
end
```
I couldn't follow the manual. but at least this generates I presume the correct files
`nsys profile C:\Bin\Julia-1.6.0\bin\julia.exe test.jl`

The results looks similar and equably confusing to me ;) 
last good 
![image](https://user-images.githubusercontent.com/2228878/115904060-a2350280-a464-11eb-8e42-106f27778902.png)
and first bad
![image](https://user-images.githubusercontent.com/2228878/115904127-b842c300-a464-11eb-9ed4-743d28626058.png)

Here are the [files](https://1drv.ms/u/s!AkkVaBzPZVicial2jHDreK5ytaxOjg?e=koiG3A) . I guess you can make more sense of those and can point out what to look for

**Comment by maleadt** [comment]
You didn't answer my question though. The kernels perform identically, it's just the synchronization that is slightly higher-latency (not really 'slower', since it switches execution to a different Julia task). Is that a problem in a real application?

**Comment by anj00** [comment]
I guess I didn't understand the question. 

Let me try.
It is hard for me to say if that particular change matters in practice. Everyone's practice is different :)

Our system has a number of kernels (10-20+). They get combined to do a calculation. To monitor performance change we run tests on both overall system and kernel by kernel. 

As you probably noticed, we've been struggling migrating from Julia 1.3/CUDADrv to CUDA due to major performance issues. Now, our tests show that in our case/kernels/system we pretty much can move on to CUDA.jl now (we started with an order of magnitude system performance delta down to single digit % ). That is a major improvement. Greatly appreciate your help here.

However, several kernel tests are still slower. So I posted some examples which show the biggest delta still. Thinking, maybe something can be improved in case it got overlooked.
Of course, on the other hand some kernels got actually faster.
And line of thinking that "Yes, that particular modification makes some computations slower, but others faster" so this is not a bug, this is a decision from CUDA.jl team to improve overall performance. That line of thinking I sure can buy into. 

However, we could never have such a conclusion unless I post an issue and ask :) Some reports will result in performance improvements. Some, maybe will come back with "this is a not a bug. this is performance compromise the team took to speed up other scenarios "

**Comment by maleadt** [comment]
We're talking past one another. The change you bisected the regression to, does _not_ change how kernels are executed. That means the computations _do not_ run any slower. If that were the case, which profiling can help reveal (because you can look at the execution time of individual operations, like kernels, in the trace), that's a legitimate bug.

Instead, what 00333a8ceb31563fc68eb418c70fbc9c8e000622 does is change how we wait for a computation to finish. We used to do so by calling the blocking `cuStreamSynchronize` function, whereas now we query the status of the stream and `yield()` to another Julia task if the stream hasn't finished yet. That enables task-based concurrency, because a previously blocking operation now allows other Julia tasks to execute. That does introduce some variability, because instead of busy-waiting for the kernel to finish we may now spend some time in the Julia task scheduler. It however does not affect how kernels execute; the GPU just keeps executing in the background.

If you don't want to yield to other tasks, you can have `synchronize` busy-wait again by passing the `blocking=false` keyword argument. This doesn't go back to calling `cuStreamSynchronize`, but spins in Julia which is even faster.

I could make `synchronize()` first perform a couple of spins, which 'removes' the added latency here, but that just comes at the expense of added latency for users that *do* use multiple tasks so that feels like benchmark gaming:

```patch
diff --git a/lib/cudadrv/stream.jl b/lib/cudadrv/stream.jl
index 656fa607..80e5314a 100644
--- a/lib/cudadrv/stream.jl
+++ b/lib/cudadrv/stream.jl
@@ -113,10 +113,15 @@ asked to yield to any other scheduled task, otherwise it will spin indefinitely.
 See also: [`device_synchronize`](@ref)
 """
 function synchronize(s::CuStream=stream(); blocking::Bool=true)
-    # TODO: exponential back-off and sleep?
+    spins = 16  # < 5us
     while !query(s)
         if blocking
-            yield()
+            if spins > 0
+                # spin a couple of times before yielding to other tasks
+                spins -= 1
+            else
+                yield()
+            end
         else
             ccall(:jl_cpu_pause, Cvoid, ())
             # Temporary solution before we have gc transition support in codegen.
```

That's why I was asking whether this added latency really matters. We're talking about 200ns of added latency or so, only happening when doing costly blocking operations like synchronizing or copying memory from host to device or vice-versa. Both these operations are unlikely to be performed often and/or as part of the performance-critical path. And even then, the added latency is likely to be dwarfed by the time it takes to actually synchronize the GPU, or the time it takes to transfer memory.
