### ISSUE TITLE
Problem in reduce_block?

### ISSUE THREAD

**Issue by eschnett** [JuliaGPU/CUDA.jl#843]
There might be a small performance error in `reduce_block`. This line
https://github.com/JuliaGPU/CUDA.jl/blob/632f960a332f57aa8b885e39ab6fb7850e6a3bf5/src/mapreduce.jl#L57
allocates spaces for twice the number of threads, but the upper half of that array is never written.

**Comment by maleadt** [comment]
Nicely spotted, yeah there's a couple of issues with the non-shuffle reduction.
