### ISSUE TITLE
Support for CuSparseMatrixCSC{Float16} x CuVector{Float16}

### ISSUE THREAD

**Issue by dpmerrell** [JuliaGPU/CUDA.jl#849]
**Describe the bug**

I get the "Performing scalar operations" warning when I try to do sparse matrix/dense vector multiplication with Float16 precision.
When I set `CUDA.allowscalar(false)`, this becomes "ERROR: scalar getindex is disallowed." and crashes.

When I try the same thing in Float32 precision, the code works fine.

Note: dense matrix/dense vector multiplication _does_ work in Float16. So this seems fixable. 

**To reproduce**

```julia

using CUDA
using SparseArrays
using LinearAlgebra

# This works:
A_d = CUDA.CUSPARSE.CuSparseMatrixCSC{Float32}(sprand(10000,10000))
v_d = CuArray{Float32}(randn(10000))

println(A_d * v_d)
# 10000-element CuArray{Float32, 1}:
# etc.

# This doesn't work:
A_d_16 = CUDA.CUSPARSE.CuSparseMatrixCSC{Float16}(sprand(10000,10000))
v_d_16 = CuArray{Float16}(randn(10000))

println(A_d_16 * v_d_16)
```

<details><summary>Manifest.toml</summary>
<p>

```
[[CUDA]]
version = "3.0.3"

[[GPUArrays]]
version = "6.2.2"

[[GPUCompiler]]
version = "0.11.4"

[[LLVM]]
version = "3.6.0"
```

</p>
</details>

**Expected behavior**

Multiplication should work in Float16, just as it does in Float32

**Version info**

Details on Julia: 

```
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, sandybridge)
```

Details on CUDA:

```
CUDA toolkit 11.2.2, artifact installation
CUDA driver 11.3.0
NVIDIA driver 465.19.1

Libraries: 
- CUBLAS: 11.4.1
- CURAND: 10.2.3
- CUFFT: 10.4.1
- CUSOLVER: 11.1.0
- CUSPARSE: 11.4.1
- CUPTI: 14.0.0
- NVML: 11.0.0+465.19.1
- CUDNN: 8.10.0 (for CUDA 11.2.0)
- CUTENSOR: 1.2.2 (for CUDA 11.1.0)

Toolchain:
- Julia: 1.6.0
- LLVM: 11.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
- Device support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80

1 device:
  0: NVIDIA GeForce RTX 2070 (sm_75, 7.537 GiB / 7.795 GiB available)

```

Thanks for looking at this!

**Comment by maleadt** [comment]
Just because it's not implemented, doesn't mean this is a bug.

It should be pretty easy to implement this: the generic `cusparseSpMV` API supports mixed precision (Float16xFloat16xFloat32) multiplication, see https://docs.nvidia.com/cuda/cusparse/index.html#cusparse-generic-function-spmv. I don't have time to work on this though.

**Comment by dpmerrell** [comment]
@maleadt thanks for your correction. I'm newish to Julia and GPU programming, but I can try digging through the source and figuring out how to fix this.

Thanks for your work on CUDA.jl, it's an amazing package!
