### ISSUE TITLE
Support for `sm_80` `cp.async`: asynchronous on-device copies

### ISSUE THREAD

**Issue by JesseLu** [JuliaGPU/CUDA.jl#850]
I'm writing a 3D eletromagnetics FDTD code in CUDA, and it's been a lot of fun leaning on Julia's code generation utilities, combined with CUDA.jl. Thank you for all the amazing work, this definitely feels like a step forward from PyCUDA (which I previously used for a similar project).

I'm pretty sure you get this a lot (i.e. is X CUDA API exposed in CUDA.jl?), so I'm sorry if the answer is obvious. That said...

Is the `memcpy_async()` API exposed in CUDA.jl (https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#memcpy-async-api). This allows one to overlap compute and memory explicitly, and is looking to be an important optimization in my code (which is heavily memory bound). Critically, use of the API can alleviate register pressure and directly move data from global to shared memory (without going to registers first).

Thank you!

**Comment by maleadt** [comment]
No, these aren't supported yet as even LLVM doesn't have support for the necessary intrinsics: https://reviews.llvm.org/D100394.

**Comment by vchuravy** [comment]
CUDA C/C++ is implementing these with inlined assembly.

**Comment by JesseLu** [comment]
Thank you both. Is there a pointer to the CUDA reference Valentin?

**Comment by maleadt** [comment]
Look for `cp.async` in `$CUDA/targets/x86_64-linux/include/cuda/std/barrier`.

**Comment by JesseLu** [comment]
Thank you!!

**Comment by maleadt** [comment]
With Hopper, this is becoming more important to target.

**Comment by chengchingwen** [comment]
[nvvm](https://github.com/llvm/llvm-project/blob/ca2f53897a2f2a60d8cb1538d5fcf930d814e9f5/llvm/include/llvm/IR/IntrinsicsNVVM.td#L1292) seems to have intrinsic for asynchronous copy, would this help?

**Comment by maleadt** [comment]
> [nvvm](https://github.com/llvm/llvm-project/blob/ca2f53897a2f2a60d8cb1538d5fcf930d814e9f5/llvm/include/llvm/IR/IntrinsicsNVVM.td#L1292) seems to have intrinsic for asynchronous copy, would this help?

That's not NVVM, it's LLVM proper (implementing NVVM's intrinsics), so yes that would help.
It also seems to be supported from LLVM 13 onwards, so we could support this on Julia 1.8+.

**Comment by chengchingwen** [comment]
@maleadt Any pointer on where to start?

**Comment by maleadt** [comment]
Calling these intrinsics is easy, you can generally derive the names from the tablegen entries (see e.g. the tests, https://github.com/llvm/llvm-project/blob/ff0aabf14dfa0a369c38f6e267c56a83ee48d647/llvm/test/CodeGen/NVPTX/async-copy.ll#L37-L40), and simply `ccall` them like we do for many intrinsics already, e.g. https://github.com/JuliaGPU/CUDA.jl/blob/5c51766d0a9e7819ea79f314e37ed6a8a5d24369/src/device/intrinsics/misc.jl#L8

The tricky part is figuring out a good abstraction in Julia that exposes these intrinsics. Take a look at what CUDA C does, or if the CUDA C++ interface has something more high level.

**Comment by chengchingwen** [comment]
I was reading the [nvidia doc about async copy](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#data-movement-and-conversion-instructions-asynchronous-copy) and it seems llvm only support a small portion of the instructions? Here are some code translated from the `async-copy.ll`

```jl
@inline llvm_nvvm_cp_async_wait_group(i::Int32) = ccall("llvm.nvvm.cp.async.wait.group", llvmcall, Cvoid, (Int32,), i)
@inline llvm_nvvm_cp_async_wait_all() = ccall("llvm.nvvm.cp.async.wait.all", llvmcall, Cvoid, ())
@inline llvm_nvvm_cp_async_commit_group() = ccall("llvm.nvvm.cp.async.commit.group", llvmcall, Cvoid, ())
@inline llvm_nvvm_cp_async_mbarrier_arrive(ptr::LLVMPtr{T, A}) where {T, A} =
    ccall("llvm.nvvm.cp.async.mbarrier.arrive", llvmcall, Cvoid, (LLVMPtr{T, A},), ptr)
@inline llvm_nvvm_cp_async_mbarrier_arrive_shared(ptr::LLVMPtr{T, AS.Shared}) where T =
    ccall("llvm.nvvm.cp.async.mbarrier.arrive.shared", llvmcall, Cvoid, (LLVMPtr{T, AS.Shared},), ptr)
@inline llvm_nvvm_cp_async_mbarrier_arrive_noinc(ptr::LLVMPtr{T, A}) where {T, A} =
    ccall("llvm.nvvm.cp.async.mbarrier.arrive.noinc", llvmcall, Cvoid, (LLVMPtr{T, A},), ptr)
@inline llvm_nvvm_cp_async_mbarrier_arrive_noinc_shared(ptr::LLVMPtr{T, AS.Shared}) where T =
    ccall("llvm.nvvm.cp.async.mbarrier.arrive.noinc.shared", llvmcall, Cvoid, (LLVMPtr{T, AS.Shared},), ptr)
@inline llvm_nvvm_cp_async_ca_shared_global_4(dst::LLVMPtr{T, AS.Shared}, src::LLVMPtr{T, AS.Global}) where T =
    ccall("llvm.nvvm.cp.async.ca.shared.global.4", llvmcall, Cvoid,
          (LLVMPtr{T, AS.Shared}, LLVMPtr{T, AS.Global}), dst, src)
@inline llvm_nvvm_cp_async_ca_shared_global_8(dst::LLVMPtr{T, AS.Shared}, src::LLVMPtr{T, AS.Global}) where T =
    ccall("llvm.nvvm.cp.async.ca.shared.global.8", llvmcall, Cvoid,
          (LLVMPtr{T, AS.Shared}, LLVMPtr{T, AS.Global}), dst, src)
@inline llvm_nvvm_cp_async_ca_shared_global_16(dst::LLVMPtr{T, AS.Shared}, src::LLVMPtr{T, AS.Global}) where T =
    ccall("llvm.nvvm.cp.async.ca.shared.global.16", llvmcall, Cvoid,
          (LLVMPtr{T, AS.Shared}, LLVMPtr{T, AS.Global}), dst, src)
@inline llvm_nvvm_cp_async_cg_shared_global_16(dst::LLVMPtr{T, AS.Shared}, src::LLVMPtr{T, AS.Global}) where T =
    ccall("llvm.nvvm.cp.async.cg.shared.global.16", llvmcall, Cvoid,
          (LLVMPtr{T, AS.Shared}, LLVMPtr{T, AS.Global}), dst, src)
```

I have no idea how to use those `mbarrier` instructions. But for the other part, those `llvm_nvvm_cp_async_ca_shared_global_<n>` could be merged into a `async_copyto!` function and the commit/wait function is just a single function call. If these are the only functions we can use right now,  I think there aren't much things we could do for a more high level abstraction in Julia.

**Comment by maleadt** [comment]
What pieces are missing? You can always use inline assembly for those. Grep for `asmcall` in CUDA.jl.
And FWIW wrappers like the ones you added above aren't very useful, the idea is indeed to make something high-level like `async_copyto!` and have that `ccall` directly; no need for functions that directly map onto intrinsics.

**Comment by chengchingwen** [comment]
> What pieces are missing?

According to the doc, there are some extra argument of `cp.async.ca.shared.global`like `ignore-src`. 

> the idea is indeed to make something high-level like async_copyto! and have that ccall directly; no need for functions that directly map onto intrinsics.

I was imitating what `device/intrinsics/wmma.jl`do. And I think it would be better to somehow expose those `llvm_nvvm_cp_async_ca_shared_global_<n>` because it can be use to do some kind of vectorized copy depend on the bit size. I'm not sure if we have any common used abstraction in Julia for vectorized copy.

**Comment by maleadt** [comment]
`memcpy_async` is implemented now.
