### ISSUE TITLE
Profiling Julia with Nsight Systems on Windows results in blank window

### ISSUE THREAD

**Issue by anj00** [JuliaGPU/CUDA.jl#862]
```
Julia 1.6.0, Window 10
NVIDIA Nsight Systems version 2021.2.1.58-642947b 
CUDA 3.0.3 (but think it is independent of CUDA, as it is not even loaded yet)
```

When I follow the manual on profiling I end up with 2 windows. In one I type (top), the text and results show up in anther (original, bottom). The worst part is that text looks all broken, hard to see what are you typing (for instance I typed `VERSION`). 

![image](https://user-images.githubusercontent.com/2228878/115906331-aca4cb80-a467-11eb-9aa0-191cc6d682b8.png)

Running same command with profile instead of launch generates file file.

**Comment by maleadt** [comment]
I can reproduce what's reported on Discourse, https://discourse.julialang.org/t/why-i-am-not-getting-anything-in-repl-while-trying-to-use-nsight-systems-for-profiling/50667, but not the split-window issue here. I'll file an issue with NVIDIA.
EDIT: filed as NVIDIA bug #3300486.

**Comment by maleadt** [comment]
This has been fixed upstream.
