### ISSUE TITLE
CUDA.@sync seems to be using a lot of CPU while waiting

### ISSUE THREAD

**Issue by anj00** [JuliaGPU/CUDA.jl#893]
The following code seems to be loading a CPU thread fully. (1/16th on 16th thread CPU and if I run 6 processes like this it is using 50+% on the same cpu). The expectation is that while processing is happening in GPU there will be relatively low CPU load.
```
Win10
Julia 1.6.1
CUDA v3.1.0
```
```
using CUDA
CUDA.device!(0)

function long_gpu_compute(x, num)
   for i = 1:1000000000 x[i % 2 + 1] = num end
   return
end

function f() 
    @cuda threads=1 long_gpu_compute(x, 42.0f0)
    return x 
end 

x = cu(rand(Float32, 2))
for i = 1:3
   println("$i **************************")
   @time( x_out = CUDA.@sync(f(x)))
end
```

If I read documentation correctly @sync meant to be CPU friendly, i.e. equivalent of `CuArrays.@sync` from the past. and the "same" code but using  `CuArrays` i.e `CuArrays.@sync` for syncing is very gentle on CPU. (julia 1.3.1)

For reference the following code is more gentle on CPU (load drops down to practically nothing while waiting for GPU to return).
Also, not sure if that is a practical difference or just an "artificial benchmark effect" below code also runs much faster. 
on 2080Ti
above code 24sec/loop
below code 14sec/loop
```
using CUDAdrv: CuDevice, CuContext, synchronize
use_dev = 0
dev = CuDevice(use_dev)
ctx = CuContext(dev)
println("Running on ", dev)
using CUDAnative
CUDAnative.device!(use_dev)
using CuArrays

function long_gpu_compute(x, num)
    for i = 1:1000000000 x[i % 2 + 1] = num end
   return
end

function f(x) 
    @cuda threads=1 long_gpu_compute(x, 42.0f0)
    return x
end 

x = CuArray{Float32, 1}(undef, 2)

for i = 1:3
   println("$i **************************")
   @time( x_out = CuArrays.@sync(f(x)))
end
```

**Comment by maleadt** [comment]
It's funny you ask for better latency in https://github.com/JuliaGPU/CUDA.jl/issues/838 and https://github.com/JuliaGPU/CUDA.jl/issues/839 and complain about CPU usage while spinning in here :-P FWIW, CUDA also spins by default, using all available CPU time while waiting for a kernel to finish. I've tried a hybrid approach in https://github.com/JuliaGPU/CUDA.jl/pull/896.

**Comment by anj00** [comment]
Sorry, not trying to confuse nor contradict. As was saying migrating from CUDANative etc. Was posting those bugs past while checking individual kernel tests. Last week switched "production" server to CUDA.jl. And realized that CPU of the server is pretty loaded (as server has 6 cards and cpu load is jumping at you. say running 2-3 julia processes per GPU would load CPU 100% and one becomes CPU bound, and as icing on the cake. it is consumer grade HW. running CPU loaded 24/7 tend to destabilize the system over time). Thus this report.

And actually don't see contradiction between those reports. As I understand CUDA.jl is really a next generation for code/ideas used in CUDANative etc. So I imagine one wants to have CUDA.jl's performance to be on par or better with prev generation code. So while migrating to CUDA.jl every time I saw a "degradation" I share my experience. 

Now, what to do with this knowledge?
Of course in some cases it will not be possible to reach same performance due to different tradeoffs taken or some code is not implemented (yet?). That is fine by me. I understand. So long there is an understanding: ok in this case and that case (maybe corner) CUDA.jl is "slower". The development team is aware of that and fine with that fact. Maybe dev team would find, hmm we felt there was a perfect compromise but apparently it doesn't work for all, so lets introduce flags in the function so people can pick compromises the way it works for them, change the compromise etc.  And anything inbetween. And we as users learn in the process of this communication on important (for us) ways to use the CUDA.jl to achieve best performance for our cases.

**Comment by maleadt** [comment]
I didn't imply these contradict; I had a fix ready for this issue when I remembered another issue where "a" user was complaining about synchronization latency, only to find out it was you in both cases :slightly_smiling_face:

Anyway, https://github.com/JuliaGPU/CUDA.jl/pull/896 should remove any CPU load. It does further regress latency a bit (although not by much), but you can pass `blocking=false` if you want to improve that (at the expense of a loaded CPU). There is however a trade-off; while previous versions of CUDA.jl resulted in a busy-loop or a simple blocking synchronization inside of CUDA, we now consider other tasks for the purpose of multitasking, which does come at a certain cost: slightly lower latency when synchronizing. But as I mentioned in the other issues, GPU performance itself is not impacted.

**Comment by maleadt** [comment]
Just to be clear, the linked PR should fix all of your issues: no CPU load on long running kernel, and better latency for short ones. But in the end, it depends on your exact latency requirements. If you'd bump your problem size in one of those other two issues beyond the hard-coded thresholds if #896, you'd see the added latency of yielding to other tasks again.
