### ISSUE TITLE
Register `CUDA.jl` in the General registry

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaGPU/CUDA.jl#9]
It would be very convenient to register `CUDA.jl` in the General registry. That way, instead of running this:
```julia
] add CUDAdrv CUDAnative CuArrays
```

You could simply run this:
```julia
] add CUDA
```

and be done with it.

cc: @maleadt 

(The automerge bot won't like the name, but I can manually merge it.)

**Comment by maleadt** [comment]
I haven't worked out yet how the version of that package would work, and I'd also want to take it a step further and reexport all relevant functionality. So yeah, this is the plan, but not ready yet :slightly_smiling_face:

**Comment by maleadt** [comment]
https://github.com/JuliaRegistries/General/pull/15404
