### ISSUE TITLE
CUDNN convolution with Float16 always returns zeros 

### ISSUE THREAD

**Issue by DrChainsaw** [JuliaGPU/CUDA.jl#92]
**Sanity checks (read this first, then remove this section)**
This might be a feature request instead :)

**Describe the bug**
CuArrays.CUDNN.cudnnConvolutionForward outputs zeros () when invoked with Float16 arrays

**To Reproduce**
The Minimal Working Example (MWE) for this bug:
```julia
#Dummy data
ww_cpu = randn(5,4,3,2);
xx_cpu = randn(6,6,3,1);
yy_cpu = randn(2,3,2,1); #lazy copy-paste

# 32 Bit works
ww_32 = cu(ww_cpu);
xx_32 = cu(xx_cpu);
yy_32 = cu(yy_cpu);
 CuArrays.CUDNN.cudnnConvolutionForward(yy_32, xx_32, ww_32, CuArrays.CUDNN.DenseConvDims(xx_32, ww_32))
2×3×2×1 CuArray{Float32,4,Nothing}:
[:, :, 1, 1] =
 -7.26039  -2.08891  0.992969
 -8.32356   0.83666  3.50633

[:, :, 2, 1] =
 11.1538   -0.619833   0.97121
 -3.20547  -0.316545  -8.41101

# No such luck with 16 bit
ww_16 = CuArrays.adapt(CuArray{Float16}, ww_cpu);
xx_16 = CuArrays.adapt(CuArray{Float16}, xx_cpu);
yy_16 = CuArrays.adapt(CuArray{Float16}, yy_cpu);
CuArrays.CUDNN.cudnnConvolutionForward(yy_16, xx_16, ww_16, CuArrays.CUDNN.DenseConvDims(xx_16, ww_16))
2×3×2×1 CuArray{Float16,4,Nothing}:
[:, :, 1, 1] =
 -0.0  -0.0  0.0
 -0.0   0.0  0.0

[:, :, 2, 1] =
  0.0  -0.0   0.0
 -0.0  -0.0  -0.0
```

**Expected behavior**
Outputs should be (almost) equal

**Build log**
```
Pkg.build()
  Building NNlib → `E:\Programs\julia\.julia\packages\NNlib\FAI3o\deps\build.log`
false

# make sure the error still reproduces after that.
ww_16 = CuArrays.adapt(CuArray{Float16}, ww_cpu);
xx_16 = CuArrays.adapt(CuArray{Float16}, xx_cpu);
yy_16 = CuArrays.adapt(CuArray{Float16}, yy_cpu);
CuArrays.CUDNN.cudnnConvolutionForward(yy_16, xx_16, ww_16, CuArrays.CUDNN.DenseConvDims(xx_16, ww_16))
2×3×2×1 CuArray{Float16,4,Nothing}:
[:, :, 1, 1] =
 -0.0  -0.0  0.0
  0.0   0.0  0.0

[:, :, 2, 1] =
 0.0  -0.0  0.0
 0.0  -0.0  0.0
```

**Environment details (please complete this section)**
Details on Julia:
```
# please post the output of:
versioninfo()
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)
```

Julia packages:
add CuArrays
  Updating registry at `E:/Programs/julia/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
 Installed TerminalMenus ─ v0.1.0
 Installed Cthulhu ─────── v1.0.0
 Installed CUDAapi ─────── v4.0.0
 Installed GPUArrays ───── v3.1.0
 Installed CUDAdrv ─────── v6.2.2
 Installed CuArrays ────── v2.0.1
 Installed CUDAnative ──── v3.0.2
  Updating `E:\Programs\julia\.julia\dev\CuArraysFp16\Project.toml`
  [3a865a2d] + CuArrays v2.0.1
  Updating `E:\Programs\julia\.julia\dev\CuArraysFp16\Manifest.toml`
  [621f4979] + AbstractFFTs v0.5.0
  [79e6a3ab] + Adapt v1.0.1
  [b99e7846] + BinaryProvider v0.5.8
  [fa961155] + CEnum v0.2.0  
  [3895d2a7] + CUDAapi v4.0.0
  [c5f51814] + CUDAdrv v6.2.2
  [be33ccc6] + CUDAnative v3.0.2  
  [da1fd8a2] + CodeTracking v0.5.8
  [34da2185] + Compat v2.2.0      
  [f68482b8] + Cthulhu v1.0.0
  [3a865a2d] + CuArrays v2.0.1        
  [864edb3b] + DataStructures v0.17.11
  [0c68f7d7] + GPUArrays v3.1.0
  [929cbde3] + LLVM v1.3.4
  [1914dd2f] + MacroTools v0.5.5        
  [872c559c] + NNlib v0.6.6
  [bac558e1] + OrderedCollections v1.1.0
  [189a3867] + Reexport v0.2.0
  [ae029012] + Requires v1.0.1
  [dc548174] + TerminalMenus v0.1.0
  [a759f4b9] + TimerOutputs v0.5.3 
  [2a0f44e3] + Base64 
  [ade2ca70] + Dates 
  [8bb1440f] + DelimitedFiles   
  [8ba89e20] + Distributed      
  [b77e0a4c] + InteractiveUtils 
  [76f85450] + LibGit2 
  [8f399da3] + Libdl 
  [37e2e46d] + LinearAlgebra    
  [56ddb016] + Logging 
  [d6f4376e] + Markdown         
  [a63ad114] + Mmap 
  [44cfe95a] + Pkg 
  [de0858da] + Printf 
  [3fa0cd96] + REPL 
  [9a3f8284] + Random 
  [ea8e919c] + SHA 
  [9e88b42a] + Serialization    
  [1a1011a3] + SharedArrays     
  [6462fe0b] + Sockets      
  [2f01184e] + SparseArrays 
  [10745b16] + Statistics   
  [8dfed614] + Test         
  [cf7118a7] + UUIDs        
  [4ec0a83e] + Unicode    

CUDA: toolkit and driver version: Hmmm, I guess toolkit is built in now. Driver is 442.74

**Comment by hgt312** [comment]
Hi! Does someone know what cause this problem?

**Comment by maleadt** [comment]
Nope, not sure what's up here. The inputs look OK, but the documentation mentions:
> Note:CUDNN_DATA_HALF in cudnnSetConvolutionNdDescriptor() with HALF_CONVOLUTION_BWD_FILTER is not recommended as it is known to not be useful for any practical use case for training and will be considered to be blocked in a future cuDNN release. The use of CUDNN_DATA_HALF for input tensors in cudnnSetTensorNdDescriptor() and CUDNN_DATA_FLOAT in cudnnSetConvolutionNdDescriptor() with HALF_CONVOLUTION_BWD_FILTER is recommended and is used with the automatic mixed precision (AMP) training in many well known deep learning frameworks. 

@denizyuret do you know what's up here?

**Comment by hgt312** [comment]
I meet the same problem and just find the reason.

refer to https://docs.nvidia.com/deeplearning/cudnn/developer-guide/index.html#scaling-parameters, `alpha` and `beta` should be float type on host memory

> These parameters are passed using a host memory pointer. The storage data types for alpha and beta are:
> - float for HALF and FLOAT tensors, and
> - double for DOUBLE tensors.

in file: https://github.com/JuliaGPU/CUDA.jl/blob/master/lib/cudnn/conv.jl#L154-L156

**Comment by denizyuret** [comment]
If alpha/beta are the problem [here ](https://github.com/denizyuret/Knet.jl/blob/01ea152f4734fedad945079a6a626e4db93d9c67/src/cudnn/common.jl#L50)is the little function I wrote that converts Real values to appropriate alpha/beta containers.

**Comment by maleadt** [comment]
> If alpha/beta are the problem [here ](https://github.com/denizyuret/Knet.jl/blob/01ea152f4734fedad945079a6a626e4db93d9c67/src/cudnn/common.jl#L50)is the little function I wrote that converts Real values to appropriate alpha/beta containers.

See https://github.com/JuliaGPU/CUDA.jl/pull/454, I think it's good to be more strict and catch future issues sooner.
