### ISSUE TITLE
GPU Implementation of partialsort!

### ISSUE THREAD

**Issue by btmit** [JuliaGPU/CUDA.jl#93]
It would be great if there was an implementation of sort! and partialsort! for CuArrays.

A simple (1D array, radix-2) native Julia implementation would be really helpful as a good starting point.

Other issues have considered wrapping Thrust or CUB JuliaGPU/CuArrays.jl#525.

This should enable a number of higher level functions, such as the ability to generate statistics about data (median, quartiles, etc) on the GPU. 

A few (possibly) helpful links:
https://www.cse.chalmers.se/~tsigas/papers/GPU-Quicksort-jea.pdf
https://onlinelibrary.wiley.com/doi/full/10.1002/cpe.3611
https://sourceforge.net/projects/cuda-quicksort/

**Comment by xaellison** [comment]
I have an implementation of quicksort which may be of interest. It uses dynamic parallelism and gets pretty good thread usage for the partitioning. On my machine, for totally random input, it slightly outperforms sorting the equivalent list on the host side (so it would really beat transfer + CPU sort + transfer back). 

Using @maleadt 's implementation as a reference for performance:
```
BenchmarkTools.Trial: 
  memory estimate:  544 bytes
  allocs estimate:  24
  --------------
  minimum time:     568.765 ms (0.00% GC)
  median time:      3.030 s (0.00% GC)
  mean time:        2.710 s (0.00% GC)
  maximum time:     5.209 s (0.00% GC)
  --------------
  samples:          7
  evals/sample:     1
```

**Comment by xaellison** [comment]
I have an implementation of quicksort which may be of interest. It uses dynamic parallelism and gets pretty good thread usage  when partitioning. On my machine, for random input, it slightly outperforms sorting a `CuArray` compared to sorting the equivalent `Array` on the host (so it would really beat transferring to host, sorting, and transferring back).

Using @maleadt 's implementation above for comparison
```
function main(T, N)
    b = @benchmarkable (CUDA.@sync(sort!(c))) setup=(c = CuArray(rand($T, $N))) samples=7 seconds=30
    run(b)
end

main(Float64, 1000000)
```
gives
```
BenchmarkTools.Trial: 
  memory estimate:  544 bytes
  allocs estimate:  24
  --------------
  minimum time:     1.740 s (0.00% GC)
  median time:      3.407 s (0.00% GC)
  mean time:        4.920 s (0.00% GC)
  maximum time:     12.968 s (0.00% GC)
  --------------
  samples:          7
  evals/sample:     1
```
The same test on my quicksort is about roughly 50x faster
```
julia> speed_test(Float64, Int(1e6))
BenchmarkTools.Trial: 
  memory estimate:  720 bytes
  allocs estimate:  32
  --------------
  minimum time:     62.126 ms (0.00% GC)
  median time:      63.724 ms (0.00% GC)
  mean time:        67.051 ms (0.00% GC)
  maximum time:     82.177 ms (0.00% GC)
  --------------
  samples:          10
  evals/sample:     1
```
and it scales well
```
julia> speed_test(Float64, Int(1e8))
BenchmarkTools.Trial: 
  memory estimate:  720 bytes
  allocs estimate:  32
  --------------
  minimum time:     7.658 s (0.00% GC)
  median time:      7.663 s (0.00% GC)
  mean time:        7.663 s (0.00% GC)
  maximum time:     7.669 s (0.00% GC)
  --------------
  samples:          4
  evals/sample:     1

```
One of the last things I want to improve is make it handle [the worst case of all elements are equal](https://stackoverflow.com/questions/5126586/quicksort-complexity-when-all-the-elements-are-same). This should be feasible without killing performance.

It has plenty of room to improve but I think it could be a solid starting point. Comparing to bullet points above:
- It can do negative numbers
- No padding the length
- No extra memory
- Worst case can be well controlled by the strategy linked above, plus median is drawn from a pool of 1024.

Happy to open a branch if you want to consider it!

**Comment by maleadt** [comment]
That's great! Please do open a branch, even if it's an initial version. We can still do development there.

Going back to the bitonic timings from @wongalvis14, which are another order of magnitude better, maybe we should dispatch at run-time based on the input sizes.

**Comment by wongalvis14** [comment]
@xaellison I'm curious what's your approach to efficiently use dynamic parallelism. In my experience with CUDA it introduces way too much overhead during run-time that turns any efficient algorithm inefficient.

**Comment by xaellison** [comment]
@maleadt was about to commit when Github told me I need to be authorized if you don't mind setting me up.

@wongalvis14 Each quicksort kernel only launches one kernel (partition) that it needs to wait on. Partition happens in default stream (no stream arg is provided). Recursive quicksort kernels are launched on their own streams but aren't explicitly waited on. A lot of work happens in the quicksort kernel: selecting a pivot, half the partitioning logic, and sorting small sublists. That allows me to launch fewer kernels per recursive step. I hope that the performance I'm getting won't be limited to my hardware.

**Comment by vchuravy** [comment]
> was about to commit when Github told me I need to be authorized if you don't mind setting me up. 

You will need to fork the project, into your own account and push to there. Then you can open a PR.

**Comment by maleadt** [comment]
We have `sort!` now, so a large part of this is fixed. I'll leave the issue open still, `partialsort!` would be useful, and maybe we should also implement a bitonic sort (presumably much faster) for pow2-inputs.

**Comment by wongalvis14** [comment]
Glad to see that merge! I guess the trade-off was more parallel workers (quicksort) vs more memory (bitonic sort). I still find it amazing how quicksort can be so efficient.

**Comment by haozhangphd** [comment]
It would be great if `sortperm` is implemented as well...

**Comment by CarloLucibello** [comment]
So how hard would it be to implement [quicksort partial sorting](https://en.wikipedia.org/wiki/Partial_sorting)?
Assuming we are looking for the first `k` positions, it is just a matter of changing [this line](https://github.com/JuliaGPU/CUDA.jl/blob/65dc032059696051e4f78f565628ee5781b194e5/src/sorting.jl#L400)
to `partition < k`  instead of `partition < hi`?

**Comment by xaellison** [comment]
> So how hard would it be to implement [quicksort partial sorting](https://en.wikipedia.org/wiki/Partial_sorting)?
> Assuming we are looking for the first `k` positions, it is just a matter of changing [this line](https://github.com/JuliaGPU/CUDA.jl/blob/65dc032059696051e4f78f565628ee5781b194e5/src/sorting.jl#L400)
> to `partition < k`  instead of `partition < hi`?

It's a tiny bit more than that since julia's partial sort can also sort a range like 100:1000 but you're correct: it's just a matter of changing when child quick sort kernels are launched

**Comment by AhmedSalih3d** [comment]
> It would be great if `sortperm` is implemented as well...

Was sortperm! ever implemented?

**Comment by maleadt** [comment]
Yes, in https://github.com/JuliaGPU/CUDA.jl/pull/1217
