### ISSUE TITLE
Supporting union bits types 

### ISSUE THREAD

**Issue by ViralBShah** [JuliaGPU/CUDA.jl#934]
I tried to see what it might take to run DataFrames.jl on GPUs as discussed in https://github.com/JuliaData/DataFrames.jl/issues/2713

Working with the `neuro` dataset from RDatasets, I could not convert a vector with missing data into a `CuArray`:

```
julia> cu(neuro.V1)
ERROR: CuArray does not yet support union bits types
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] CuArray{Union{Missing, Float64}, 1}(#unused#::UndefInitializer, dims::Tuple{Int64})
    @ CUDA ~/.julia/packages/CUDA/Zmd60/src/array.jl:18
  [3] (CuArray{Union{Missing, Float64}, N} where N)(#unused#::UndefInitializer, dims::Tuple{Int64})
```

**Comment by ViralBShah** [comment]
cc @quinnj

**Comment by maleadt** [comment]
There is already an issue, https://github.com/JuliaGPU/CUDA.jl/issues/103, so I'll add your use-case there.
