### ISSUE TITLE
Quicksort kernel does not cope with reduced threads

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CUDA.jl#955]
The following fails when restricting `quicksort_kernel` to 256 threads:

```julia
using CUDA
using Test

function init()
    a = map(x -> x%UInt8, reverse(1:100000))
    c = CuArray(a)
    a, c
end

function check()
    original_arr, device_arr = init()
    sort!(device_arr)
    host_result = Array(device_arr)
    @assert issorted(host_result)
end

function main()
    for x in 1:100
        print("Iteration $x\r")
        check()
    end
    println()
end

isinteractive() || main()
```

```patch
diff --git a/src/sorting.jl b/src/sorting.jl
index 8f82ada4..b5f0ada5 100644
--- a/src/sorting.jl
+++ b/src/sorting.jl
@@ -469,6 +469,7 @@ function quicksort!(c::AbstractArray{T,N}; lt::F1, by::F2, dims::Int, partial_k=
     get_shmem(threads) = threads * (sizeof(Int) + sizeof(T))
     config = launch_configuration(kernel.fun, shmem=threads->get_shmem(threads))
     threads = prevpow(2, config.threads)
+    threads=256
 
     kernel(my_sort_args...;
            blocks=prod(otherdims), threads=threads, shmem=get_shmem(threads))
```

@xaellison, could you have a look? Thanks!

**Comment by xaellison** [comment]
This was weird. I originally based the device sync logic off the very simple example from [this section](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#global-memory) of the programming guide. I thought that `device_synchronize` then `sync_threads` would be sufficient. Does it make sense that `threadfence` is necessary instead?

**Comment by maleadt** [comment]
As I understand the docs, having a thread wait for the child grid with device_synchronize and then perform a sync_threads only makes the child grid's global modifications available to the block where it was launched from. With a global thread fence, those changes are made available to other blocks too. Does that explain the behavior? If so, maybe add some comments to the code.

`threadfence` is also exported so doesn't need the CUDA module prefix.

**Comment by xaellison** [comment]
Ok that was my understanding, too. The parent kernel is strictly a single block, though, so it seems as though sync_threads should be enough.
