### ISSUE TITLE
CUDA.jl cannot find installed CUPTI libraries with local installation on linux

### ISSUE THREAD

**Issue by galenlynch** [JuliaGPU/CUDA.jl#956]
I have a local installation of CUDA that I've been using successfully with CUDA.jl. The one caveat is that CUDA.jl doesn't seem to detect CUPTI even though it is installed. Here is the output of `CUDA.versioninfo`:

```
julia> CUDA.versioninfo()
CUDA toolkit 11.3.0, local installation
CUDA driver 11.3.0
NVIDIA driver 465.31.0

Libraries: 
- CUBLAS: 11.5.1
- CURAND: 10.2.4
- CUFFT: 10.4.2
- CUSOLVER: 11.1.2
- CUSPARSE: 11.6.0
- CUPTI: missing
- NVML: 11.0.0+465.31
- CUDNN: 8.20.0 (for CUDA 11.3.0)
- CUTENSOR: 1.3.0 (for CUDA 11.2.0)

Toolchain:
- Julia: 1.6.0
- LLVM: 11.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
- Device support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80

Environment:
- JULIA_CUDA_USE_BINARYBUILDER: false

1 device:
  0: NVIDIA GeForce RTX 3090 (sm_86, 22.306 GiB / 23.697 GiB available)
```

I've been trying to figure out why this might be. It seems like the root cause may be that the CUPTI version number is handled by CUDA.jl as a string instead of a version number, and as a consequence only the _exact_ version number for this library can be used, instead of compatible library versions (like mine).

It seems that the library versions that correspond to a particular toolkit version are defined in `cuda_library_versions`, and unlike the other libraries which have version numbers the CUPTI version number is a simple string, as shown here: https://github.com/JuliaGPU/CUDA.jl/blob/5d6127dbbef495c94d3dd8de98162188062e11b1/deps/discovery.jl#L277

This version number is then used by `CUDA.find_library` to generate the versioned library names that would be compatible with the specified library version. If the version is specified as a version number on a unix system then acceptable library files just have to match the major version number as shown here: https://github.com/JuliaGPU/CUDA.jl/blob/5d6127dbbef495c94d3dd8de98162188062e11b1/deps/discovery.jl#L53-L56

However for strings this is not the case: https://github.com/JuliaGPU/CUDA.jl/blob/5d6127dbbef495c94d3dd8de98162188062e11b1/deps/discovery.jl#L57-L58

My particular libcupti library is at `/usr/local/cuda-11.3/lib64/libcupti.so.2021.1.1`, which seems to be following semver with a rather unusual major version (the year), and I assume is compatible with `libcupti.so.2021.1.0` expected by CUDA.jl.

Happy to try to make a PR to fix this if you agree that this is the cause of the problem.

**Comment by maleadt** [comment]
CUPTI 2021.1.1 is part of CUDA 11.3 Update 1, and should be discovered _when_ your ptxas/nvdisasm versions are discovered as being from CUDA 11.3.1. Where did you get that CUDA distribution from? Could you show the version strings as reported by `ptxas` and `nvdisasm` from `/usr/local/cuda-11.3`?

**Comment by galenlynch** [comment]
I think I have CUDA 11.3 Update 1, if that's what you're saying.

```
$ /usr/local/cuda-11.3/bin/ptxas --version
ptxas: NVIDIA (R) Ptx optimizing assembler
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:14:31_PDT_2021
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0
$ /usr/local/cuda-11.3/bin/nvdisasm --version
nvdisasm: NVIDIA (R) CUDA disassembler
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Mar_21_19:13:56_PDT_2021
Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0
```

I thought CUDA.jl no longer differentiated between 11.3.1 and 11.3? https://github.com/JuliaGPU/CUDA.jl/blob/ad946c499315f54fa71cf2901812e3f451bd9723/deps/discovery.jl#L502-L511

I don't think this rounding down the toolkit version to the lowest compatible version would be a problem if the CUPTI version was a version number instead of a string.

**Comment by galenlynch** [comment]
Or rather, the nvdisasm version is used to determine the toolkit version, and it is the same between 11.3.0 and 11.3.1: https://github.com/JuliaGPU/CUDA.jl/blob/ad946c499315f54fa71cf2901812e3f451bd9723/deps/discovery.jl#L357-L364

At least that's what I understand. You'd obviously know better than me.

**Comment by maleadt** [comment]
That's all true, but it should be looking at `ptxas` then which can be used to disambiguate the CUDA toolkit version: https://github.com/JuliaGPU/CUDA.jl/commit/c2dfd606fc7757f12f8387aefce69f8b0d7c44e5#diff-a2e31525a9acaf0886979de31e8d7a41562932c21a82a0c080deb60f4e8641dbR174

**Comment by galenlynch** [comment]
Oh then maybe an update to CUDA.jl will fix it? Thanks!  I'll try that!

**Comment by maleadt** [comment]
Yes, please try the master branch.

**Comment by galenlynch** [comment]
Success! Thank you so much!

```julia
julia> CUDA.versioninfo()
CUDA toolkit 11.3.1, local installation
CUDA driver 11.3.0
NVIDIA driver 465.31.0

Libraries: 
- CUBLAS: 11.5.1
- CURAND: 10.2.4
- CUFFT: 10.4.2
- CUSOLVER: 11.1.2
- CUSPARSE: 11.6.0
- CUPTI: 14.0.0
- NVML: 11.0.0+465.31
- CUDNN: 8.20.0 (for CUDA 11.3.0)
- CUTENSOR: 1.3.0 (for CUDA 11.2.0)

Toolchain:
- Julia: 1.6.0
- LLVM: 11.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
- Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80

Environment:
- JULIA_CUDA_USE_BINARYBUILDER: false

1 device:
  0: NVIDIA GeForce RTX 3090 (sm_86, 23.001 GiB / 23.697 GiB available)
```

**Comment by maleadt** [comment]
Glad it works! FYI, I hope to create a release some time this week, so you won't have to use the master branch for long.

**Comment by galenlynch** [comment]
Unfortunately master is not passing tests locally, so I may just live without profiling until the new release. Seemed like most of the tests were failing for me. Also I noticed that the test dependencies are missing `FillArrays`, so I'll make a PR to add that.

Nonetheless, this issue seems to be solved so I'll close the issue. Thanks again!

**Comment by galenlynch** [comment]
Also using a version number wouldn't have worked, however it looks like the "real" version (11.3) is used for the library on my system (I installed from official NVIDIA repo):

```
$ ls -la /usr/local/cuda-11.3/lib64/libcupti*
lrwxrwxrwx. 1 root root       16 May  5 22:35 /usr/local/cuda-11.3/lib64/libcupti.so -> libcupti.so.11.3
lrwxrwxrwx. 1 root root       20 May  5 22:35 /usr/local/cuda-11.3/lib64/libcupti.so.11.3 -> libcupti.so.2021.1.1
-rwxr-xr-x. 1 root root  6748816 May  5 22:35 /usr/local/cuda-11.3/lib64/libcupti.so.2021.1.1
-rw-r--r--. 1 root root 16022554 May  5 22:35 /usr/local/cuda-11.3/lib64/libcupti_static.a
```
