### ISSUE TITLE
Linalg support for non-contiguous views of arrays

### ISSUE THREAD

**Issue by haampie** [JuliaGPU/CUDA.jl#96]
Currently high-level BLAS works for contiguous views because of a hacky dispatch in `view` that returns a new CuArray. There's no support for SubArray at the moment, which is what you get for non-contiguous views of CuArrays.

It's probably a lot better to define a StridedGPUArray similar as in Base and use that to dispatch to CUBLAS. That way we can remove the special `view` dispatch form CuArrays as well and rely on Base.

Unfortunately Base's StridedArray is a bit of an ugly beast, but probably it's best to just follow what they have there?

**Comment by maleadt** [comment]
There's a StridedCuArray now (not as fully generic as Base's due to the compilation cost involved with these array wrappers).
