### ISSUE TITLE
Bad conversion from QR to CuArray

### ISSUE THREAD

**Issue by theogf** [JuliaGPU/CUDA.jl#969]
When computing `Q, R = qr(X)` on a low-rank matrix `X` with dimensions `NxD` and then converting `Q` to a `CuMatrix` the final size of the matrix will be `NxN` instead of `NxD` (the matrix is padded with zeros).
I guess it just miss a conversion method

```julia
X = rand(100, 10)
Q, R = qr(X)
Q  = CuMatrix(Q)
```

That's on CUDA 3.2.1 and julia 1.6.0

**Comment by kshyatt** [comment]
Is this actually a CUDA.jl bug?

```
julia> using LinearAlgebra

julia> X = rand(100,10);

julia> Q, R = qr(X);

julia> size(Q)
(100, 100)
```

**Comment by maleadt** [comment]
This does look to be working as expected.

**Comment by theogf** [comment]
> Is this actually a CUDA.jl bug?
> 
> ```
> julia> using LinearAlgebra
> 
> julia> X = rand(100,10);
> 
> julia> Q, R = qr(X);
> 
> julia> size(Q)
> (100, 100)
> ```

That's true but 
```
julia> size(Matrix(Q))
(100, 10)
```

**Comment by maleadt** [comment]
That seems like a questionable API on the Base side:

```julia
julia> X = rand(2, 1)
2×1 Matrix{Float64}:
 0.7947208136565149
 0.9745030850677258

julia> Q, R = qr(X);

julia> Q
2×2 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}}:
 -0.631998  -0.77497
 -0.77497    0.631998

julia> collect(Q)
2×2 Matrix{Float64}:
 -0.631998  -0.77497
 -0.77497    0.631998

julia> Array(Q)
2×1 Matrix{Float64}:
 -0.631998494325047
 -0.7749696143532817
```

**Comment by theogf** [comment]
But it does make sense in the context of rectangular matrices, where a large part of `Q` is basically useless...
Generally, it would anyway be nice to have a common behavior between `CuMatrix` and `Matrix`, even if Base is questionable.

**Comment by maleadt** [comment]
> But it does make sense in the context of rectangular matrices, where a large part of `Q` is basically useless...

Even if it does, `size` shouldn't disagree with `Array(...)`. This breaks code: https://github.com/JuliaGPU/CUDA.jl/blob/b934949a1de445ec891b424ca893bbda09a72698/src/array.jl#L265-L269

```
julia> convert(Array{Float64}, Q)
2×1 Matrix{Float64}:
 -0.7114767625733938
 -0.7027096244666661

julia> size(Q)
(2, 2)
```

It seems like Base is well aware of this, https://github.com/JuliaLang/LinearAlgebra.jl/issues/513. cc @andreasnoack, what's the best approach here, specialize a `CuMatrix` constructor? The fact that `size` + `copyto!` cannot be relied on, is worrisome.

**Comment by andreasnoack** [comment]
Yeah. Unfortunately, I think you'd have to special case the constructor for the Q for now and leave a comment with a reference to https://github.com/JuliaLang/LinearAlgebra.jl/issues/513 such that the constructor can be deleted once we tidy things up in `LinearAlgebra`.

**Comment by axsk** [comment]
Is this really satisfactory now? There is no device-agnostic way to access the thin Q matrix, is it?
