### ISSUE TITLE
Is it possible to set cache config in CUDA.jl?

### ISSUE THREAD

**Issue by JesseLu** [JuliaGPU/CUDA.jl#988]
I would like to be able to config the L1 cache/shared memory sizes. Is there a way to do this in CUDA.jl? Thank you!

**Comment by JesseLu** [comment]
Just figured out that it is already exposed as CUDA.cufunccacheconfig. Closing, thanks!

**Comment by maleadt** [comment]
You can just use the C APIs, all of them are available (albeit not exported).
